export const MIN = "Min"
export const MAX = "Max"
export const SCARF = "Scarf"
export const BOOSTER = "Booster"
export const ACTUAL = "Actual"
export const DEFAULT_TERA_TYPE = "Water"
export const SELECT_POKEMON_LABEL = "Select a Pokémon"
export const MAX_BASE_SPEED_FOR_TR = 60
export const NEGATIVE_SPEED_NATURES = ["Brave", "Quiet", "Relaxed", "Sassy"]
