export const MIN = "Min"
export const MAX = "Max"
export const SCARF = "Scarf"
export const BOOSTER = "Booster"
export const ACTUAL = "Actual"
export const META = "Meta"
export const DEFAULT_TERA_TYPE = "Water"
export const SELECT_POKEMON_LABEL = "Select a Pokémon"
