import { Type } from "@vgc-types/calc-types"
import { toID } from "@lib/calc/engine/data-util"

export function getType(name: string): Type | undefined {
  return TYPES[toID(name)]
}

export const TYPES: Record<string, Type> = {
  "": {
    effectiveness: {
      Normal: 1,
      Grass: 1,
      Fire: 1,
      Water: 1,
      Electric: 1,
      Ice: 1,
      Flying: 1,
      Bug: 1,
      Poison: 1,
      Ground: 1,
      Rock: 1,
      Fighting: 1,
      Psychic: 1,
      Ghost: 1,
      Dragon: 1,
      Dark: 1,
      Steel: 1,
      Fairy: 1,
      Stellar: 1
    }
  },
  normal: {
    effectiveness: {
      "???": 1,
      Normal: 1,
      Grass: 1,
      Fire: 1,
      Water: 1,
      Electric: 1,
      Ice: 1,
      Flying: 1,
      Bug: 1,
      Poison: 1,
      Ground: 1,
      Rock: 0.5,
      Fighting: 1,
      Psychic: 1,
      Ghost: 0,
      Dragon: 1,
      Dark: 1,
      Steel: 0.5,
      Fairy: 1,
      Stellar: 1
    }
  },
  grass: {
    effectiveness: {
      "???": 1,
      Normal: 1,
      Grass: 0.5,
      Fire: 0.5,
      Water: 2,
      Electric: 1,
      Ice: 1,
      Flying: 0.5,
      Bug: 0.5,
      Poison: 0.5,
      Ground: 2,
      Rock: 2,
      Fighting: 1,
      Psychic: 1,
      Ghost: 1,
      Dragon: 0.5,
      Dark: 1,
      Steel: 0.5,
      Fairy: 1,
      Stellar: 1
    }
  },
  fire: {
    effectiveness: {
      "???": 1,
      Normal: 1,
      Grass: 2,
      Fire: 0.5,
      Water: 0.5,
      Electric: 1,
      Ice: 2,
      Flying: 1,
      Bug: 2,
      Poison: 1,
      Ground: 1,
      Rock: 0.5,
      Fighting: 1,
      Psychic: 1,
      Ghost: 1,
      Dragon: 0.5,
      Dark: 1,
      Steel: 2,
      Fairy: 1,
      Stellar: 1
    }
  },
  water: {
    effectiveness: {
      "???": 1,
      Normal: 1,
      Grass: 0.5,
      Fire: 2,
      Water: 0.5,
      Electric: 1,
      Ice: 1,
      Flying: 1,
      Bug: 1,
      Poison: 1,
      Ground: 2,
      Rock: 2,
      Fighting: 1,
      Psychic: 1,
      Ghost: 1,
      Dragon: 0.5,
      Dark: 1,
      Steel: 1,
      Fairy: 1,
      Stellar: 1
    }
  },
  electric: {
    effectiveness: {
      "???": 1,
      Normal: 1,
      Grass: 0.5,
      Fire: 1,
      Water: 2,
      Electric: 0.5,
      Ice: 1,
      Flying: 2,
      Bug: 1,
      Poison: 1,
      Ground: 0,
      Rock: 1,
      Fighting: 1,
      Psychic: 1,
      Ghost: 1,
      Dragon: 0.5,
      Dark: 1,
      Steel: 1,
      Fairy: 1,
      Stellar: 1
    }
  },
  ice: {
    effectiveness: {
      "???": 1,
      Normal: 1,
      Grass: 2,
      Fire: 0.5,
      Water: 0.5,
      Electric: 1,
      Ice: 0.5,
      Flying: 2,
      Bug: 1,
      Poison: 1,
      Ground: 2,
      Rock: 1,
      Fighting: 1,
      Psychic: 1,
      Ghost: 1,
      Dragon: 2,
      Dark: 1,
      Steel: 0.5,
      Fairy: 1,
      Stellar: 1
    }
  },
  flying: {
    effectiveness: {
      "???": 1,
      Normal: 1,
      Grass: 2,
      Fire: 1,
      Water: 1,
      Electric: 0.5,
      Ice: 1,
      Flying: 1,
      Bug: 2,
      Poison: 1,
      Ground: 1,
      Rock: 0.5,
      Fighting: 2,
      Psychic: 1,
      Ghost: 1,
      Dragon: 1,
      Dark: 1,
      Steel: 0.5,
      Fairy: 1,
      Stellar: 1
    }
  },
  bug: {
    effectiveness: {
      "???": 1,
      Normal: 1,
      Grass: 2,
      Fire: 0.5,
      Water: 1,
      Electric: 1,
      Ice: 1,
      Flying: 0.5,
      Bug: 1,
      Poison: 0.5,
      Ground: 1,
      Rock: 1,
      Fighting: 0.5,
      Psychic: 2,
      Ghost: 0.5,
      Dragon: 1,
      Dark: 2,
      Steel: 0.5,
      Fairy: 0.5,
      Stellar: 1
    }
  },
  poison: {
    effectiveness: {
      "???": 1,
      Normal: 1,
      Grass: 2,
      Fire: 1,
      Water: 1,
      Electric: 1,
      Ice: 1,
      Flying: 1,
      Bug: 1,
      Poison: 0.5,
      Ground: 0.5,
      Rock: 0.5,
      Fighting: 1,
      Psychic: 1,
      Ghost: 0.5,
      Dragon: 1,
      Dark: 1,
      Steel: 0,
      Fairy: 2,
      Stellar: 1
    }
  },
  ground: {
    effectiveness: {
      "???": 1,
      Normal: 1,
      Grass: 0.5,
      Fire: 2,
      Water: 1,
      Electric: 2,
      Ice: 1,
      Flying: 0,
      Bug: 0.5,
      Poison: 2,
      Ground: 1,
      Rock: 2,
      Fighting: 1,
      Psychic: 1,
      Ghost: 1,
      Dragon: 1,
      Dark: 1,
      Steel: 2,
      Fairy: 1,
      Stellar: 1
    }
  },
  rock: {
    effectiveness: {
      "???": 1,
      Normal: 1,
      Grass: 1,
      Fire: 2,
      Water: 1,
      Electric: 1,
      Ice: 2,
      Flying: 2,
      Bug: 2,
      Poison: 1,
      Ground: 0.5,
      Rock: 1,
      Fighting: 0.5,
      Psychic: 1,
      Ghost: 1,
      Dragon: 1,
      Dark: 1,
      Steel: 0.5,
      Fairy: 1,
      Stellar: 1
    }
  },
  fighting: {
    effectiveness: {
      "???": 1,
      Normal: 2,
      Grass: 1,
      Fire: 1,
      Water: 1,
      Electric: 1,
      Ice: 2,
      Flying: 0.5,
      Bug: 0.5,
      Poison: 0.5,
      Ground: 1,
      Rock: 2,
      Fighting: 1,
      Psychic: 0.5,
      Ghost: 0,
      Dragon: 1,
      Dark: 2,
      Steel: 2,
      Fairy: 0.5,
      Stellar: 1
    }
  },
  psychic: {
    effectiveness: {
      "???": 1,
      Normal: 1,
      Grass: 1,
      Fire: 1,
      Water: 1,
      Electric: 1,
      Ice: 1,
      Flying: 1,
      Bug: 1,
      Poison: 2,
      Ground: 1,
      Rock: 1,
      Fighting: 2,
      Psychic: 0.5,
      Ghost: 1,
      Dragon: 1,
      Dark: 0,
      Steel: 0.5,
      Fairy: 1,
      Stellar: 1
    }
  },
  ghost: {
    effectiveness: {
      "???": 1,
      Normal: 0,
      Grass: 1,
      Fire: 1,
      Water: 1,
      Electric: 1,
      Ice: 1,
      Flying: 1,
      Bug: 1,
      Poison: 1,
      Ground: 1,
      Rock: 1,
      Fighting: 1,
      Psychic: 2,
      Ghost: 2,
      Dragon: 1,
      Dark: 0.5,
      Steel: 1,
      Fairy: 1,
      Stellar: 1
    }
  },
  dragon: {
    effectiveness: {
      "???": 1,
      Normal: 1,
      Grass: 1,
      Fire: 1,
      Water: 1,
      Electric: 1,
      Ice: 1,
      Flying: 1,
      Bug: 1,
      Poison: 1,
      Ground: 1,
      Rock: 1,
      Fighting: 1,
      Psychic: 1,
      Ghost: 1,
      Dragon: 2,
      Dark: 1,
      Steel: 0.5,
      Fairy: 0,
      Stellar: 1
    }
  },
  dark: {
    effectiveness: {
      "???": 1,
      Normal: 1,
      Grass: 1,
      Fire: 1,
      Water: 1,
      Electric: 1,
      Ice: 1,
      Flying: 1,
      Bug: 1,
      Poison: 1,
      Ground: 1,
      Rock: 1,
      Fighting: 0.5,
      Psychic: 2,
      Ghost: 2,
      Dragon: 1,
      Dark: 0.5,
      Steel: 1,
      Fairy: 0.5,
      Stellar: 1
    }
  },
  steel: {
    effectiveness: {
      "???": 1,
      Normal: 1,
      Grass: 1,
      Fire: 0.5,
      Water: 0.5,
      Electric: 0.5,
      Ice: 2,
      Flying: 1,
      Bug: 1,
      Poison: 1,
      Ground: 1,
      Rock: 2,
      Fighting: 1,
      Psychic: 1,
      Ghost: 1,
      Dragon: 1,
      Dark: 1,
      Steel: 0.5,
      Fairy: 2,
      Stellar: 1
    }
  },
  fairy: {
    effectiveness: {
      "???": 1,
      Normal: 1,
      Grass: 1,
      Fire: 0.5,
      Water: 1,
      Electric: 1,
      Ice: 1,
      Flying: 1,
      Bug: 1,
      Poison: 0.5,
      Ground: 1,
      Rock: 1,
      Fighting: 2,
      Psychic: 1,
      Ghost: 1,
      Dragon: 2,
      Dark: 2,
      Steel: 0.5,
      Fairy: 1,
      Stellar: 1
    }
  },
  stellar: {
    effectiveness: {
      "???": 1
    }
  }
}
