export const eggMoves = {
  incineroar: ["fakeout", "partingshot", "powertrip"],
  rillaboom: ["strength", "leechseed", "growth", "fakeout", "hammerarm", "worryseed"],
  amoonguss: ["poisonpowder", "defensecurl", "rollout", "worryseed"],
  whimsicott: ["beatup", "memento", "tickle", "worryseed", "switcheroo"],
  grimmsnarl: ["partingshot"],
  volcarona: ["thrash", "absorb", "harden", "morningsun"],
  farigiraf: ["doublekick", "takedown", "meanlook", "mirrorcoat", "futuresight", "beatup", "uproar", "wish", "allyswitch"],
  ursaluna: ["double-edge", "counter", "seismictoss", "bellydrum", "furycutter", "metalclaw", "crosschop", "crunch", "yawn", "faketears", "closecombat", "nightslash"],
  clefairy: ["present", "wish", "tickle", "healpulse"],
  weezinggalar: ["curse", "spite", "painsplit", "stockpile", "spitup", "swallow"],
  indeedeef: ["psychup", "fakeout", "extrasensory"],
  annihilape: ["counter", "curse", "spite", "encore", "beatup", "nightslash"],
  basculegion: ["endeavor", "lastrespects"],
  jumpluff: ["encore", "worryseed", "seedbomb", "switcheroo", "ragepowder", "cottonguard", "grassyterrain", "strengthsap"],
  sneasler: ["counter", "fakeout", "feint", "nightslash", "switcheroo", "doublehit", "quickguard"],
  dondozo: ["thrash", "fissure", "curse", "yawn"],
  tatsugiri: ["counter", "batonpass", "rapidspin"],
  torkoal: ["fissure", "flail", "ancientpower", "yawn"],
  pelipper: ["gust", "twister", "knockoff", "aircutter", "aerialace", "aquaring", "wideguard", "soak"],
  dragonite: ["supersonic", "mist", "dragonbreath", "extremespeed", "waterpulse", "aquajet"],
  alcremie: ["lastresort", "baby-dolleyes"],
  ursalunabloodmoon: ["double-edge", "counter", "seismictoss", "bellydrum", "furycutter", "metalclaw", "crosschop", "crunch", "yawn", "faketears", "closecombat", "nightslash"],
  chesnaught: ["superfang", "curse", "bellydrum", "spikes", "synthesis", "wideguard", "quickguard"],
  gothitelle: ["meanlook", "mirrorcoat", "fakeout", "torment", "healpulse"],
  hariyama: ["counter", "dynamicpunch", "crosschop", "helpinghand", "feint", "bulletpunch", "wideguard"],
  glimmora: ["toxic", "explosion", "memento"],
  pachirisu: ["tailwhip", "bite", "defensecurl", "flail", "rollout", "flatter", "followme", "charge", "faketears", "covet", "baby-dolleyes"],
  rhydon: ["counter", "curse", "metalburst", "rockpolish", "dragonrush", "guardsplit"],
  pikachu: ["flail", "present", "fakeout", "charge", "wish", "tickle", "disarmingvoice", "volttackle"],
  maushold: ["bite", "batonpass", "tickle", "feint", "switcheroo", "afteryou"],
  tsareena: ["synthesis", "endeavor", "acupressure"],
  raichu: ["flail", "present", "fakeout", "charge", "wish", "tickle", "disarmingvoice", "volttackle"],
  lilliganthisui: ["sweetscent", "ingrain", "healingwish", "worryseed"],
  talonflame: ["defog", "flamecharge", "quickguard"],
  archaludon: ["slash", "mirrorcoat", "nightslash"],
  comfey: ["worryseed", "afteryou"],
  kingambit: ["headbutt", "meanlook", "suckerpunch", "quickguard"],
  araquanid: ["stockpile", "spitup", "powersplit", "stickyweb"],
  garganacl: ["fissure", "curse", "ancientpower", "powergem"],
  scraggy: ["counter", "detect", "fakeout", "quickguard"],
  scovillain: ["leechseed", "rollout", "ingrain", "worryseed", "ragepowder"],
  venusaur: ["petaldance", "toxic", "curse", "ingrain"],
  dachsbun: ["sweetscent", "wish", "yawn", "howl", "copycat"],
  mimikyu: ["curse", "destinybond"],
  spiritomb: ["disable", "smokescreen", "destinybond", "painsplit", "allyswitch"],
  electabuzz: ["dynamicpunch", "crosschop", "focuspunch", "followme", "hammerarm", "feint"],
  dragapult: ["disable", "doubleteam", "confuseray", "curse", "suckerpunch", "dragontail"],
  flamigo: ["doubleteam", "skyattack", "quickguard"],
  mienshao: ["focuspunch", "knockoff", "feint"],
  tyranitar: ["stomp", "focusenergy", "curse", "outrage", "ancientpower", "irondefense", "dragondance", "assurance", "ironhead"],
  hippowdon: ["whirlwind", "curse", "stockpile", "spitup", "swallow"],
  dugtrio: ["headbutt", "ancientpower", "memento", "honeclaws", "finalgambit"],
  oranguru: ["dreameater", "yawn", "extrasensory", "lastresort"],
  gastrodon: ["mist", "counter", "sludge", "acidarmor", "curse", "mirrorcoat", "stockpile", "spitup", "swallow", "yawn", "clearsmog"],
  overqwil: ["supersonic", "bubblebeam", "haze", "self-destruct", "flail", "astonish", "waterpulse", "aquatail", "aquajet", "acidspray"],
  sableye: ["recover", "torment", "flatter", "feint", "metalburst", "suckerpunch"],
  shiftry: ["takedown", "leechseed", "quickattack", "worryseed", "nightslash", "defog"],
  murkrow: ["whirlwind", "drillpeck", "screech", "confuseray", "skyattack", "perishsong", "flatter", "featherdance", "bravebird"],
  tinkaton: ["feint", "quash", "icehammer"],
  hitmontop: ["counter", "highjumpkick", "machpunch", "rapidspin", "feint", "vacuumwave", "bulletpunch"],
  rhyperior: ["counter", "curse", "metalburst", "rockpolish", "dragonrush", "guardsplit"],
  ceruledge: ["disable", "spite", "destinybond"],
  toxapex: ["haze", "stockpile", "spitup", "swallow", "infestation"],
  armarouge: ["disable", "spite", "destinybond"],
  mandibuzz: ["toxic", "meanlook", "roost"],
  chandelure: ["haze", "acidarmor", "powersplit", "clearsmog"],
  weezing: ["curse", "spite", "painsplit", "stockpile", "spitup", "swallow"],
  ninetalesalola: ["roar", "hypnosis", "flail", "howl", "baby-dolleyes", "moonblast"],
  snorlax: ["double-edge", "counter", "fissure", "curse", "belch"],
  swampert: ["stomp", "double-edge", "bite", "counter", "sludge", "curse", "mud-slap", "mirrorcoat", "ancientpower", "yawn", "wideguard"],
  bulbasaur: ["petaldance", "toxic", "curse", "ingrain"],
  ivysaur: ["petaldance", "toxic", "curse", "ingrain"],
  charmander: ["bite", "counter", "bellydrum", "irontail", "metalclaw", "ancientpower", "dragonrush", "dragontail"],
  charmeleon: ["bite", "counter", "bellydrum", "irontail", "metalclaw", "ancientpower", "dragonrush", "dragontail"],
  charizard: ["bite", "counter", "bellydrum", "irontail", "metalclaw", "ancientpower", "dragonrush", "dragontail"],
  squirtle: ["mist", "flail", "mirrorcoat", "fakeout", "yawn", "waterspout", "aquaring", "aquajet", "lifedew"],
  wartortle: ["mist", "flail", "mirrorcoat", "fakeout", "yawn", "waterspout", "aquaring", "aquajet", "lifedew"],
  blastoise: ["mist", "flail", "mirrorcoat", "fakeout", "yawn", "waterspout", "aquaring", "aquajet", "lifedew"],
  ekans: ["spite", "scaryface", "poisonfang", "poisontail", "suckerpunch", "switcheroo"],
  arbok: ["spite", "scaryface", "poisonfang", "poisontail", "suckerpunch", "switcheroo"],
  raichualola: ["flail", "present", "fakeout", "charge", "wish", "tickle", "disarmingvoice", "volttackle"],
  sandshrew: ["counter", "flail", "mud-slap", "metalclaw", "nightslash", "honeclaws"],
  sandshrewalola: ["counter", "flail", "nightslash", "honeclaws", "curse", "mirrorcoat", "crushclaw", "iceshard"],
  sandslash: ["counter", "flail", "mud-slap", "metalclaw", "nightslash", "honeclaws"],
  sandslashalola: ["counter", "flail", "nightslash", "honeclaws", "curse", "mirrorcoat", "crushclaw", "iceshard"],
  clefable: ["present", "wish", "tickle", "healpulse"],
  vulpix: ["roar", "hypnosis", "flail", "memento", "howl", "healingwish", "flamecharge", "baby-dolleyes"],
  vulpixalola: ["roar", "hypnosis", "flail", "howl", "baby-dolleyes", "moonblast"],
  ninetales: ["roar", "hypnosis", "flail", "memento", "howl", "healingwish", "flamecharge", "baby-dolleyes"],
  jigglypuff: ["perishsong", "rollout", "present", "wish", "covet", "gravity", "lastresort", "healpulse"],
  wigglytuff: ["perishsong", "rollout", "present", "wish", "covet", "gravity", "lastresort", "healpulse"],
  oddish: ["leechseed", "razorleaf", "flail", "synthesis", "ingrain", "teeterdance", "tickle", "afteryou", "strengthsap"],
  gloom: ["leechseed", "razorleaf", "flail", "synthesis", "ingrain", "teeterdance", "tickle", "afteryou", "strengthsap"],
  vileplume: ["leechseed", "razorleaf", "flail", "synthesis", "ingrain", "teeterdance", "tickle", "afteryou", "strengthsap"],
  venonat: ["agility", "screech", "batonpass", "morningsun", "toxicspikes", "bugbite", "venoshock", "ragepowder"],
  venomoth: ["agility", "screech", "batonpass", "morningsun", "toxicspikes", "bugbite", "venoshock", "ragepowder"],
  diglett: ["headbutt", "ancientpower", "memento", "honeclaws", "finalgambit"],
  diglettalola: ["headbutt", "ancientpower", "memento", "honeclaws", "finalgambit", "thrash", "metalsound"],
  dugtrioalola: ["headbutt", "ancientpower", "memento", "honeclaws", "finalgambit", "thrash", "metalsound"],
  meowth: ["tailwhip", "hypnosis", "flail", "spite", "covet", "lastresort"],
  meowthalola: ["hypnosis", "flail", "spite", "covet", "flatter", "partingshot"],
  persian: ["tailwhip", "hypnosis", "flail", "spite", "covet", "lastresort"],
  persianalola: ["hypnosis", "flail", "spite", "covet", "flatter", "partingshot"],
  psyduck: ["psybeam", "hypnosis", "confuseray", "crosschop", "yawn", "simplebeam", "clearsmog"],
  golduck: ["psybeam", "hypnosis", "confuseray", "crosschop", "yawn", "simplebeam", "clearsmog"],
  mankey: ["counter", "curse", "spite", "encore", "beatup", "nightslash"],
  primeape: ["counter", "curse", "spite", "encore", "beatup", "nightslash"],
  growlithe: ["doublekick", "thrash", "double-edge", "morningsun", "covet", "ragingfury"],
  arcanine: ["doublekick", "thrash", "double-edge", "morningsun", "covet", "ragingfury"],
  poliwag: ["mist", "splash", "endeavor", "muddywater", "waterpulse"],
  poliwhirl: ["mist", "splash", "endeavor", "muddywater", "waterpulse"],
  poliwrath: ["mist", "splash", "endeavor", "muddywater", "waterpulse"],
  bellsprout: ["synthesis", "ingrain", "tickle", "worryseed", "suckerpunch", "clearsmog", "strengthsap"],
  weepinbell: ["synthesis", "ingrain", "tickle", "worryseed", "suckerpunch", "clearsmog", "strengthsap"],
  victreebel: ["synthesis", "ingrain", "tickle", "worryseed", "suckerpunch", "clearsmog", "strengthsap"],
  tentacool: ["aurorabeam", "confuseray", "haze", "rapidspin", "mirrorcoat", "knockoff", "tickle", "acupressure", "aquaring"],
  tentacruel: ["aurorabeam", "confuseray", "haze", "rapidspin", "mirrorcoat", "knockoff", "tickle", "acupressure", "aquaring"],
  geodude: ["megapunch", "curse", "flail", "dynamicpunch", "block", "hammerarm", "wideguard"],
  geodudealola: ["curse", "flail", "block", "wideguard", "counter", "screech", "zapcannon", "endure"],
  graveler: ["megapunch", "curse", "flail", "dynamicpunch", "block", "hammerarm", "wideguard"],
  graveleralola: ["curse", "flail", "block", "wideguard", "counter", "screech", "zapcannon", "endure"],
  golem: ["megapunch", "curse", "flail", "dynamicpunch", "block", "hammerarm", "wideguard"],
  golemalola: ["curse", "flail", "block", "wideguard", "counter", "screech", "zapcannon", "endure"],
  slowpoke: ["stomp", "bellydrum", "block", "belch"],
  slowpokegalar: ["stomp", "bellydrum", "block", "belch"],
  slowbro: ["stomp", "bellydrum", "block", "belch"],
  slowbrogalar: ["stomp", "bellydrum", "block", "belch"],
  magnemite: ["explosion", "electroweb"],
  magneton: ["explosion", "electroweb"],
  doduo: ["whirlwind", "skyattack", "flail", "assurance"],
  dodrio: ["whirlwind", "skyattack", "flail", "assurance"],
  seel: ["horndrill", "disable", "lick", "perishsong", "fakeout", "stockpile", "spitup", "swallow", "entrainment", "belch"],
  dewgong: ["horndrill", "disable", "lick", "perishsong", "fakeout", "stockpile", "spitup", "swallow", "entrainment", "belch"],
  grimer: ["haze", "curse", "meanlook", "stockpile", "spitup", "swallow", "shadowpunch", "shadowsneak", "acidspray"],
  grimeralola: ["curse", "meanlook", "stockpile", "spitup", "swallow", "shadowsneak", "spite", "recycle", "assurance", "clearsmog"],
  muk: ["haze", "curse", "meanlook", "stockpile", "spitup", "swallow", "shadowpunch", "shadowsneak", "acidspray"],
  mukalola: ["curse", "meanlook", "stockpile", "spitup", "swallow", "shadowsneak", "spite", "recycle", "assurance", "clearsmog"],
  shellder: ["bubblebeam", "waterpulse", "aquaring", "lifedew"],
  cloyster: ["bubblebeam", "waterpulse", "aquaring", "lifedew"],
  gastly: ["disable", "toxic", "haze", "smog", "perishsong", "astonish", "clearsmog", "reflecttype"],
  haunter: ["disable", "toxic", "haze", "smog", "perishsong", "astonish", "clearsmog", "reflecttype"],
  gengar: ["disable", "toxic", "haze", "smog", "perishsong", "astonish", "clearsmog", "reflecttype"],
  drowzee: ["firepunch", "icepunch", "thunderpunch", "flatter", "roleplay", "guardswap", "psychocut", "powersplit"],
  hypno: ["firepunch", "icepunch", "thunderpunch", "flatter", "roleplay", "guardswap", "psychocut", "powersplit"],
  voltorb: ["recycle", "metalsound"],
  electrode: ["recycle", "metalsound"],
  exeggcute: ["poisonpowder", "stunspore", "sleeppowder", "curse", "moonlight", "ancientpower", "ingrain", "block"],
  exeggutor: ["poisonpowder", "stunspore", "sleeppowder", "curse", "moonlight", "ancientpower", "ingrain", "block"],
  exeggutoralola: ["poisonpowder", "stunspore", "sleeppowder", "curse", "moonlight", "ancientpower", "ingrain", "block"],
  hitmonlee: ["counter", "highjumpkick", "machpunch", "rapidspin", "feint", "vacuumwave", "bulletpunch"],
  hitmonchan: ["counter", "highjumpkick", "machpunch", "rapidspin", "feint", "vacuumwave", "bulletpunch"],
  koffing: ["curse", "spite", "painsplit", "stockpile", "spitup", "swallow"],
  rhyhorn: ["counter", "curse", "metalburst", "rockpolish", "dragonrush", "guardsplit"],
  chansey: ["seismictoss", "healbell", "present", "gravity"],
  horsea: ["disable", "aurorabeam", "splash", "flail", "clearsmog"],
  seadra: ["disable", "aurorabeam", "splash", "flail", "clearsmog"],
  scyther: ["counter", "feint", "nightslash", "defog", "quickguard"],
  magmar: ["machpunch", "bellydrum", "dynamicpunch", "crosschop", "focuspunch", "followme", "belch"],
  tauros: ["curse", "endeavor"],
  taurospaldeacombat: ["curse", "endeavor"],
  taurospaldeablaze: ["curse", "endeavor"],
  taurospaldeaaqua: ["curse", "endeavor"],
  lapras: ["horndrill", "fissure", "curse", "ancientpower", "tickle", "freeze-dry", "sparklingaria"],
  eevee: ["doublekick", "curse", "flail", "mud-slap", "detect", "wish", "yawn", "tickle"],
  vaporeon: ["doublekick", "curse", "flail", "mud-slap", "detect", "wish", "yawn", "tickle"],
  jolteon: ["doublekick", "curse", "flail", "mud-slap", "detect", "wish", "yawn", "tickle"],
  flareon: ["doublekick", "curse", "flail", "mud-slap", "detect", "wish", "yawn", "tickle"],
  dratini: ["supersonic", "mist", "dragonbreath", "extremespeed", "waterpulse", "aquajet"],
  dragonair: ["supersonic", "mist", "dragonbreath", "extremespeed", "waterpulse", "aquajet"],
  chikorita: ["vinewhip", "counter", "flail", "ancientpower", "ingrain", "healpulse"],
  bayleef: ["vinewhip", "counter", "flail", "ancientpower", "ingrain", "healpulse"],
  meganium: ["vinewhip", "counter", "flail", "ancientpower", "ingrain", "healpulse"],
  cyndaquil: ["doublekick", "curse", "reversal", "extrasensory", "howl", "covet"],
  quilava: ["doublekick", "curse", "reversal", "extrasensory", "howl", "covet"],
  typhlosion: ["doublekick", "curse", "reversal", "extrasensory", "howl", "covet"],
  typhlosionhisui: ["doublekick", "curse", "reversal", "extrasensory", "howl", "covet"],
  totodile: ["counter", "ancientpower", "flatter", "block", "aquajet"],
  croconaw: ["counter", "ancientpower", "flatter", "block", "aquajet"],
  feraligatr: ["counter", "ancientpower", "flatter", "block", "aquajet"],
  sentret: ["focusenergy", "slash", "reversal", "lastresort", "baby-dolleyes", "tidyup"],
  furret: ["focusenergy", "slash", "reversal", "lastresort", "baby-dolleyes", "tidyup"],
  hoothoot: ["wingattack", "whirlwind", "supersonic", "nightshade", "featherdance"],
  noctowl: ["wingattack", "whirlwind", "supersonic", "nightshade", "featherdance"],
  spinarak: ["disable", "megahorn", "nightslash", "ragepowder", "lunge"],
  ariados: ["disable", "megahorn", "nightslash", "ragepowder", "lunge"],
  chinchou: ["mist", "psybeam", "waterpulse", "suckerpunch", "soak"],
  lanturn: ["mist", "psybeam", "waterpulse", "suckerpunch", "soak"],
  pichu: ["flail", "present", "fakeout", "charge", "wish", "tickle", "disarmingvoice", "volttackle"],
  cleffa: ["present", "wish", "tickle", "healpulse"],
  igglybuff: ["perishsong", "rollout", "present", "wish", "covet", "gravity", "lastresort", "healpulse"],
  mareep: ["agility", "flatter", "afteryou", "electroweb", "eerieimpulse", "electricterrain"],
  flaaffy: ["agility", "flatter", "afteryou", "electroweb", "eerieimpulse", "electricterrain"],
  ampharos: ["agility", "flatter", "afteryou", "electroweb", "eerieimpulse", "electricterrain"],
  bellossom: ["leechseed", "razorleaf", "flail", "synthesis", "ingrain", "teeterdance", "tickle", "afteryou", "strengthsap"],
  marill: ["sing", "supersonic", "bellydrum", "perishsong", "present", "tickle", "copycat", "aquajet", "soak"],
  azumarill: ["sing", "supersonic", "bellydrum", "perishsong", "present", "tickle", "copycat", "aquajet", "soak"],
  sudowoodo: ["headbutt", "harden", "defensecurl", "curse", "rollout", "rockpolish"],
  politoed: ["mist", "splash", "endeavor", "muddywater", "waterpulse"],
  hoppip: ["encore", "worryseed", "seedbomb", "switcheroo", "ragepowder", "cottonguard", "grassyterrain", "strengthsap"],
  skiploom: ["encore", "worryseed", "seedbomb", "switcheroo", "ragepowder", "cottonguard", "grassyterrain", "strengthsap"],
  aipom: ["slam", "counter", "irontail", "beatup", "fakeout", "bounce", "covet", "switcheroo", "quickguard"],
  sunkern: ["leechseed", "curse", "encore", "morningsun", "ingrain", "grassyterrain"],
  sunflora: ["leechseed", "curse", "encore", "morningsun", "ingrain", "grassyterrain"],
  yanma: ["whirlwind", "double-edge", "feint"],
  wooper: ["doublekick", "counter", "recover", "curse", "ancientpower", "stockpile", "spitup", "swallow", "acidspray", "afteryou"],
  quagsire: ["doublekick", "counter", "recover", "curse", "ancientpower", "stockpile", "spitup", "swallow", "acidspray", "afteryou"],
  espeon: ["doublekick", "curse", "flail", "mud-slap", "detect", "wish", "yawn", "tickle"],
  umbreon: ["doublekick", "curse", "flail", "mud-slap", "detect", "wish", "yawn", "tickle"],
  slowking: ["stomp", "bellydrum", "block", "belch"],
  slowkinggalar: ["stomp", "bellydrum", "block", "belch"],
  misdreavus: ["screech", "curse", "spite", "destinybond", "memento", "imprison", "suckerpunch", "shadowsneak", "wonderroom"],
  girafarig: ["doublekick", "takedown", "meanlook", "mirrorcoat", "futuresight", "beatup", "uproar", "wish", "allyswitch"],
  pineco: ["pinmissile", "counter", "swift", "flail", "sandtomb", "powertrick", "toxicspikes"],
  forretress: ["pinmissile", "counter", "swift", "flail", "sandtomb", "powertrick", "toxicspikes"],
  dunsparce: ["headbutt", "bite", "curse", "astonish", "lastresort", "aquatail"],
  gligar: ["wingattack", "double-edge", "counter", "feint", "nightslash", "crosspoison"],
  snubbull: ["counter", "mimic", "snore", "present", "retaliate"],
  granbull: ["counter", "mimic", "snore", "present", "retaliate"],
  qwilfish: ["supersonic", "bubblebeam", "haze", "self-destruct", "flail", "astonish", "waterpulse", "aquajet", "acidspray", "barbbarrage"],
  scizor: ["counter", "feint", "nightslash", "defog", "quickguard"],
  heracross: ["double-edge", "seismictoss", "harden", "flail", "feint", "nightslash"],
  sneasel: ["bite", "counter", "spite", "fakeout", "feint", "iceshard", "doublehit", "iciclecrash"],
  teddiursa: ["double-edge", "counter", "seismictoss", "bellydrum", "furycutter", "metalclaw", "crosschop", "crunch", "yawn", "faketears", "closecombat", "nightslash"],
  ursaring: ["double-edge", "counter", "seismictoss", "bellydrum", "furycutter", "metalclaw", "crosschop", "crunch", "yawn", "faketears", "closecombat", "nightslash"],
  slugma: ["smokescreen", "acidarmor", "curse", "rollout", "stockpile", "memento", "guardswap", "inferno"],
  magcargo: ["smokescreen", "acidarmor", "curse", "rollout", "stockpile", "memento", "guardswap", "inferno"],
  swinub: ["double-edge", "bite", "fissure", "curse", "ancientpower", "iciclecrash", "freeze-dry"],
  piloswine: ["double-edge", "bite", "fissure", "curse", "ancientpower", "iciclecrash", "freeze-dry"],
  delibird: ["aurorabeam", "counter", "quickattack", "splash", "destinybond", "rapidspin", "fakeout", "memento", "iceshard", "freeze-dry", "auroraveil"],
  skarmory: ["whirlwind", "skyattack", "curse", "aircutter", "roost", "feint", "nightslash"],
  houndour: ["counter", "firespin", "reversal", "spite", "destinybond", "feint", "suckerpunch", "thunderfang"],
  houndoom: ["counter", "firespin", "reversal", "spite", "destinybond", "feint", "suckerpunch", "thunderfang"],
  kingdra: ["disable", "aurorabeam", "splash", "flail", "clearsmog"],
  phanpy: ["bodyslam", "counter", "fissure", "focusenergy", "snore", "ancientpower", "endeavor", "iceshard", "headsmash", "heavyslam", "playrough", "highhorsepower"],
  donphan: ["bodyslam", "counter", "fissure", "focusenergy", "snore", "ancientpower", "endeavor", "iceshard", "headsmash", "heavyslam", "playrough", "highhorsepower"],
  stantler: ["doublekick", "thrash", "bite", "disable", "spite", "megahorn", "extrasensory", "psyshieldbash"],
  tyrogue: ["counter", "highjumpkick", "machpunch", "rapidspin", "feint", "vacuumwave", "bulletpunch"],
  elekid: ["dynamicpunch", "crosschop", "focuspunch", "followme", "hammerarm", "feint"],
  magby: ["machpunch", "bellydrum", "dynamicpunch", "crosschop", "focuspunch", "followme", "belch"],
  blissey: ["seismictoss", "healbell", "present", "gravity"],
  larvitar: ["stomp", "focusenergy", "curse", "outrage", "ancientpower", "irondefense", "dragondance", "assurance", "ironhead"],
  pupitar: ["stomp", "focusenergy", "curse", "outrage", "ancientpower", "irondefense", "dragondance", "assurance", "ironhead"],
  treecko: ["doublekick", "absorb", "leechseed", "slash", "dragonbreath", "synthesis", "worryseed", "nightslash"],
  grovyle: ["doublekick", "absorb", "leechseed", "slash", "dragonbreath", "synthesis", "worryseed", "nightslash"],
  sceptile: ["doublekick", "absorb", "leechseed", "slash", "dragonbreath", "synthesis", "worryseed", "nightslash"],
  torchic: ["peck", "counter", "crushclaw", "feint", "lastresort", "nightslash"],
  combusken: ["peck", "counter", "crushclaw", "feint", "lastresort", "nightslash"],
  blaziken: ["peck", "counter", "crushclaw", "feint", "lastresort", "nightslash"],
  mudkip: ["stomp", "double-edge", "bite", "counter", "sludge", "curse", "mud-slap", "mirrorcoat", "ancientpower", "yawn", "wideguard"],
  marshtomp: ["stomp", "double-edge", "bite", "counter", "sludge", "curse", "mud-slap", "mirrorcoat", "ancientpower", "yawn", "wideguard"],
  poochyena: ["poisonfang", "astonish", "covet"],
  mightyena: ["poisonfang", "astonish", "covet"],
  lotad: ["counter", "razorleaf", "sweetscent", "synthesis", "teeterdance", "tickle"],
  lombre: ["counter", "razorleaf", "sweetscent", "synthesis", "teeterdance", "tickle"],
  ludicolo: ["counter", "razorleaf", "sweetscent", "synthesis", "teeterdance", "tickle"],
  seedot: ["takedown", "leechseed", "quickattack", "worryseed", "nightslash", "defog"],
  nuzleaf: ["takedown", "leechseed", "quickattack", "worryseed", "nightslash", "defog"],
  wingull: ["gust", "twister", "knockoff", "aircutter", "aerialace", "aquaring", "wideguard", "soak"],
  ralts: ["disable", "confuseray", "destinybond", "meanlook", "memento", "knockoff", "shadowsneak", "mysticalfire"],
  kirlia: ["disable", "confuseray", "destinybond", "meanlook", "memento", "knockoff", "shadowsneak", "mysticalfire"],
  gardevoir: ["disable", "confuseray", "destinybond", "meanlook", "memento", "knockoff", "shadowsneak", "mysticalfire"],
  surskit: ["hydropump", "psybeam", "mudshot", "bugbite", "aquajet", "powersplit", "fellstinger", "lunge"],
  masquerain: ["hydropump", "psybeam", "mudshot", "bugbite", "aquajet", "powersplit", "fellstinger", "lunge"],
  shroomish: ["charm", "helpinghand", "faketears", "worryseed"],
  breloom: ["charm", "helpinghand", "faketears", "worryseed"],
  slakoth: ["bodyslam", "slash", "snore", "curse", "crushclaw", "tickle", "hammerarm", "nightslash", "afteryou"],
  vigoroth: ["bodyslam", "slash", "snore", "curse", "crushclaw", "tickle", "hammerarm", "nightslash", "afteryou"],
  slaking: ["bodyslam", "slash", "snore", "curse", "crushclaw", "tickle", "hammerarm", "nightslash", "afteryou"],
  makuhita: ["counter", "dynamicpunch", "crosschop", "helpinghand", "feint", "bulletpunch", "wideguard"],
  azurill: ["sing", "supersonic", "bellydrum", "perishsong", "present", "tickle", "copycat", "aquajet", "soak"],
  nosepass: ["double-edge", "rollout", "headsmash", "wideguard"],
  meditite: ["firepunch", "icepunch", "thunderpunch", "dynamicpunch", "batonpass", "fakeout", "powerswap", "guardswap", "bulletpunch", "psychocut", "quickguard"],
  medicham: ["firepunch", "icepunch", "thunderpunch", "dynamicpunch", "batonpass", "fakeout", "powerswap", "guardswap", "bulletpunch", "psychocut", "quickguard"],
  plusle: ["sing", "sweetkiss", "charm", "wish"],
  minun: ["sing", "sweetkiss", "charm", "wish", "faketears"],
  volbeat: ["counter", "seismictoss", "swagger", "roost"],
  illumise: ["growth", "attract", "roost"],
  gulpin: ["smog", "acidarmor", "curse", "mud-slap", "destinybond", "clearsmog", "stuffcheeks"],
  swalot: ["smog", "acidarmor", "curse", "mud-slap", "destinybond", "clearsmog", "stuffcheeks"],
  numel: ["stomp", "bodyslam", "growth", "defensecurl", "scaryface", "rollout", "ancientpower", "stockpile", "spitup", "swallow", "heatwave", "yawn", "howl", "ironhead", "heavyslam"],
  camerupt: ["stomp", "bodyslam", "growth", "defensecurl", "scaryface", "rollout", "ancientpower", "stockpile", "spitup", "swallow", "heatwave", "yawn", "howl", "ironhead", "heavyslam"],
  spoink: ["whirlwind", "amnesia", "mirrorcoat", "futuresight", "trick", "extrasensory", "zenheadbutt", "simplebeam"],
  grumpig: ["whirlwind", "amnesia", "mirrorcoat", "futuresight", "trick", "extrasensory", "zenheadbutt", "simplebeam"],
  trapinch: ["gust", "quickattack", "flail", "furycutter", "feint", "bugbite", "firstimpression"],
  vibrava: ["gust", "quickattack", "flail", "furycutter", "feint", "bugbite", "firstimpression"],
  flygon: ["gust", "quickattack", "flail", "furycutter", "feint", "bugbite", "firstimpression"],
  cacnea: ["disable", "acid", "counter", "teeterdance", "block", "switcheroo", "belch", "fellstinger"],
  cacturne: ["disable", "acid", "counter", "teeterdance", "block", "switcheroo", "belch", "fellstinger"],
  swablu: ["haze", "featherdance", "astonish", "roost", "tailwind", "dragonrush", "defog"],
  altaria: ["haze", "featherdance", "astonish", "roost", "tailwind", "dragonrush", "defog"],
  seviper: ["bodyslam", "scaryface", "stockpile", "spitup", "swallow", "assurance", "nightslash", "switcheroo", "finalgambit"],
  barboach: ["takedown", "thrash", "flail", "spark"],
  whiscash: ["takedown", "thrash", "flail", "spark"],
  corphish: ["double-edge", "slash", "metalclaw", "ancientpower", "switcheroo", "aquajet"],
  crawdaunt: ["double-edge", "slash", "metalclaw", "ancientpower", "switcheroo", "aquajet"],
  feebas: ["mist", "hypnosis", "confuseray", "haze", "dragonbreath", "mirrorcoat", "tickle"],
  milotic: ["mist", "hypnosis", "confuseray", "haze", "dragonbreath", "mirrorcoat", "tickle"],
  shuppet: ["disable", "confuseray", "destinybond", "imprison", "gunkshot"],
  banette: ["disable", "confuseray", "destinybond", "imprison", "gunkshot"],
  duskull: ["haze", "painsplit", "memento"],
  dusclops: ["haze", "painsplit", "memento"],
  tropius: ["slam", "headbutt", "leechseed", "curse", "leafblade", "dragondance"],
  chimecho: ["disable", "hypnosis", "recover", "curse", "wish", "recycle", "cosmicpower", "allyswitch"],
  snorunt: ["disable", "rollout", "block", "switcheroo", "iciclecrash"],
  glalie: ["disable", "rollout", "block", "switcheroo", "iciclecrash"],
  luvdisc: ["supersonic", "splash", "aquajet", "entrainment"],
  bagon: ["thrash", "defensecurl", "twister", "dragonrush"],
  shelgon: ["thrash", "defensecurl", "twister", "dragonrush"],
  salamence: ["thrash", "defensecurl", "twister", "dragonrush"],
  turtwig: ["thrash", "double-edge", "growth", "stockpile", "spitup", "swallow", "superpower", "tickle", "worryseed", "wideguard", "shellsmash"],
  grotle: ["thrash", "double-edge", "growth", "stockpile", "spitup", "swallow", "superpower", "tickle", "worryseed", "wideguard", "shellsmash"],
  torterra: ["thrash", "double-edge", "growth", "stockpile", "spitup", "swallow", "superpower", "tickle", "worryseed", "wideguard", "shellsmash"],
  chimchar: ["firepunch", "thunderpunch", "doublekick", "counter", "focusenergy", "encore", "fakeout", "heatwave", "helpinghand", "switcheroo"],
  monferno: ["firepunch", "thunderpunch", "doublekick", "counter", "focusenergy", "encore", "fakeout", "heatwave", "helpinghand", "switcheroo"],
  infernape: ["firepunch", "thunderpunch", "doublekick", "counter", "focusenergy", "encore", "fakeout", "heatwave", "helpinghand", "switcheroo"],
  piplup: ["supersonic", "snore", "yawn", "featherdance", "roost", "aquaring", "powertrip"],
  prinplup: ["supersonic", "snore", "yawn", "featherdance", "roost", "aquaring", "powertrip"],
  empoleon: ["supersonic", "snore", "yawn", "featherdance", "roost", "aquaring", "powertrip"],
  starly: ["sandattack", "furyattack", "double-edge", "uproar", "featherdance", "astonish"],
  staravia: ["sandattack", "furyattack", "double-edge", "uproar", "featherdance", "astonish"],
  staraptor: ["sandattack", "furyattack", "double-edge", "uproar", "featherdance", "astonish"],
  shinx: ["doublekick", "takedown", "quickattack", "howl", "shockwave", "nightslash", "baby-dolleyes"],
  luxio: ["doublekick", "takedown", "quickattack", "howl", "shockwave", "nightslash", "baby-dolleyes"],
  luxray: ["doublekick", "takedown", "quickattack", "howl", "shockwave", "nightslash", "baby-dolleyes"],
  cranidos: ["whirlwind", "stomp", "thrash", "hammerarm"],
  rampardos: ["whirlwind", "stomp", "thrash", "hammerarm"],
  shieldon: ["headbutt", "counter", "fissure", "screech", "focusenergy", "guardsplit"],
  bastiodon: ["headbutt", "counter", "fissure", "screech", "focusenergy", "guardsplit"],
  buizel: ["headbutt", "furyswipes", "slash", "mud-slap", "furycutter", "batonpass", "helpinghand", "aquaring"],
  floatzel: ["headbutt", "furyswipes", "slash", "mud-slap", "furycutter", "batonpass", "helpinghand", "aquaring"],
  shellos: ["mist", "counter", "sludge", "acidarmor", "curse", "mirrorcoat", "stockpile", "spitup", "swallow", "yawn", "clearsmog"],
  ambipom: ["slam", "counter", "irontail", "beatup", "fakeout", "bounce", "covet", "switcheroo", "quickguard"],
  drifloon: ["disable", "hypnosis", "haze", "memento", "defog", "clearsmog"],
  drifblim: ["disable", "hypnosis", "haze", "memento", "defog", "clearsmog"],
  mismagius: ["screech", "curse", "spite", "destinybond", "memento", "imprison", "suckerpunch", "shadowsneak", "wonderroom"],
  honchkrow: ["whirlwind", "drillpeck", "screech", "confuseray", "skyattack", "perishsong", "flatter", "featherdance", "bravebird"],
  chingling: ["disable", "hypnosis", "recover", "curse", "wish", "recycle", "cosmicpower", "allyswitch"],
  stunky: ["double-edge", "leer", "haze", "smog", "slash", "astonish"],
  skuntank: ["double-edge", "leer", "haze", "smog", "slash", "astonish"],
  bronzor: ["recycle", "gravity"],
  bronzong: ["recycle", "gravity"],
  bonsly: ["headbutt", "harden", "defensecurl", "curse", "rollout", "rockpolish"],
  happiny: ["seismictoss", "healbell", "present", "gravity"],
  gible: ["thrash", "double-edge", "metalclaw", "twister"],
  gabite: ["thrash", "double-edge", "metalclaw", "twister"],
  garchomp: ["thrash", "double-edge", "metalclaw", "twister"],
  munchlax: ["double-edge", "counter", "fissure", "curse", "belch"],
  riolu: ["bite", "highjumpkick", "detect", "crosschop", "howl", "bulletpunch", "circlethrow"],
  lucario: ["bite", "highjumpkick", "detect", "crosschop", "howl", "bulletpunch", "circlethrow"],
  hippopotas: ["whirlwind", "curse", "stockpile", "spitup", "swallow"],
  croagunk: ["headbutt", "counter", "dynamicpunch", "crosschop", "fakeout", "feint", "vacuumwave", "bulletpunch", "quickguard"],
  toxicroak: ["headbutt", "counter", "dynamicpunch", "crosschop", "fakeout", "feint", "vacuumwave", "bulletpunch", "quickguard"],
  finneon: ["psybeam", "aurorabeam", "agility", "confuseray", "flail", "sweetkiss", "charm", "tickle", "aquatail"],
  lumineon: ["psybeam", "aurorabeam", "agility", "confuseray", "flail", "sweetkiss", "charm", "tickle", "aquatail"],
  snover: ["stomp", "double-edge", "leechseed", "growth", "weatherball"],
  abomasnow: ["stomp", "double-edge", "leechseed", "growth", "weatherball"],
  weavile: ["bite", "counter", "spite", "fakeout", "feint", "iceshard", "doublehit", "iciclecrash"],
  magnezone: ["explosion", "electroweb"],
  electivire: ["dynamicpunch", "crosschop", "focuspunch", "followme", "hammerarm", "feint"],
  magmortar: ["machpunch", "bellydrum", "dynamicpunch", "crosschop", "focuspunch", "followme", "belch"],
  yanmega: ["whirlwind", "double-edge", "feint"],
  leafeon: ["doublekick", "curse", "flail", "mud-slap", "detect", "wish", "yawn", "tickle"],
  glaceon: ["doublekick", "curse", "flail", "mud-slap", "detect", "wish", "yawn", "tickle"],
  gliscor: ["wingattack", "double-edge", "counter", "feint", "nightslash", "crosspoison"],
  mamoswine: ["double-edge", "bite", "fissure", "curse", "ancientpower", "iciclecrash", "freeze-dry"],
  gallade: ["disable", "confuseray", "destinybond", "meanlook", "memento", "knockoff", "shadowsneak", "mysticalfire"],
  probopass: ["double-edge", "rollout", "headsmash", "wideguard"],
  dusknoir: ["haze", "painsplit", "memento"],
  froslass: ["disable", "rollout", "block", "switcheroo", "iciclecrash"],
  snivy: ["glare", "meanlook", "sweetscent", "irontail", "synthesis", "twister", "mirrorcoat"],
  servine: ["glare", "meanlook", "sweetscent", "irontail", "synthesis", "twister", "mirrorcoat"],
  serperior: ["glare", "meanlook", "sweetscent", "irontail", "synthesis", "twister", "mirrorcoat"],
  tepig: ["thrash", "superpower", "yawn", "suckerpunch"],
  pignite: ["thrash", "superpower", "yawn", "suckerpunch"],
  emboar: ["thrash", "superpower", "yawn", "suckerpunch"],
  oshawott: ["screech", "detect", "knockoff", "copycat", "nightslash", "airslash", "sacredsword", "aquacutter"],
  dewott: ["screech", "detect", "knockoff", "copycat", "nightslash", "airslash", "sacredsword", "aquacutter"],
  samurott: ["screech", "detect", "knockoff", "copycat", "nightslash", "airslash", "sacredsword", "aquacutter"],
  samurotthisui: ["screech", "detect", "knockoff", "copycat", "nightslash", "airslash", "sacredsword", "aquacutter"],
  blitzle: ["doublekick", "sandattack", "screech", "feint"],
  zebstrika: ["doublekick", "sandattack", "screech", "feint"],
  drilbur: ["slash", "metalsound"],
  excadrill: ["slash", "metalsound"],
  timburr: ["counter", "machpunch", "detect", "defog", "wideguard"],
  gurdurr: ["counter", "machpunch", "detect", "defog", "wideguard"],
  conkeldurr: ["counter", "machpunch", "detect", "defog", "wideguard"],
  sewaddle: ["screech", "snore", "synthesis", "worryseed", "switcheroo"],
  swadloon: ["screech", "snore", "synthesis", "worryseed", "switcheroo"],
  leavanny: ["screech", "snore", "synthesis", "worryseed", "switcheroo"],
  cottonee: ["beatup", "memento", "tickle", "worryseed", "switcheroo"],
  petilil: ["sweetscent", "ingrain", "healingwish", "worryseed"],
  lilligant: ["sweetscent", "ingrain", "healingwish", "worryseed"],
  basculin: ["bubblebeam", "endeavor"],
  sandile: ["double-edge", "counter", "spite", "aquatail"],
  krokorok: ["double-edge", "counter", "spite", "aquatail"],
  krookodile: ["double-edge", "counter", "spite", "aquatail"],
  scrafty: ["counter", "detect", "fakeout", "quickguard"],
  zorua: ["counter", "detect", "memento", "extrasensory", "copycat", "suckerpunch"],
  zoroark: ["counter", "detect", "memento", "extrasensory", "copycat", "suckerpunch"],
  minccino: ["tailwhip", "flail", "knockoff", "aquatail", "tidyup"],
  cinccino: ["tailwhip", "flail", "knockoff", "aquatail", "tidyup"],
  gothita: ["meanlook", "mirrorcoat", "fakeout", "torment", "healpulse"],
  gothorita: ["meanlook", "mirrorcoat", "fakeout", "torment", "healpulse"],
  solosis: ["confuseray", "acidarmor", "astonish"],
  duosion: ["confuseray", "acidarmor", "astonish"],
  reuniclus: ["confuseray", "acidarmor", "astonish"],
  ducklett: ["gust", "steelwing", "endeavor", "dive", "brine", "aquajet"],
  swanna: ["gust", "steelwing", "endeavor", "dive", "brine", "aquajet"],
  deerling: ["headbutt", "agility", "sleeptalk", "batonpass", "synthesis", "faketears", "worryseed"],
  sawsbuck: ["headbutt", "agility", "sleeptalk", "batonpass", "synthesis", "faketears", "worryseed"],
  foongus: ["poisonpowder", "defensecurl", "rollout", "worryseed"],
  alomomola: ["mist", "endure", "painsplit", "mirrorcoat", "tickle", "bounce"],
  joltik: ["poisonsting", "doubleteam", "strugglebug", "infestation", "lunge"],
  galvantula: ["poisonsting", "doubleteam", "strugglebug", "infestation", "lunge"],
  litwick: ["haze", "acidarmor", "powersplit", "clearsmog"],
  lampent: ["haze", "acidarmor", "powersplit", "clearsmog"],
  axew: ["counter", "irontail", "endeavor", "nightslash", "aquatail", "firstimpression"],
  fraxure: ["counter", "irontail", "endeavor", "nightslash", "aquatail", "firstimpression"],
  haxorus: ["counter", "irontail", "endeavor", "nightslash", "aquatail", "firstimpression"],
  cubchoo: ["focuspunch", "yawn", "nightslash"],
  beartic: ["focuspunch", "yawn", "nightslash"],
  cryogonal: ["explosion", "frostbreath", "auroraveil"],
  mienfoo: ["focuspunch", "knockoff", "feint"],
  pawniard: ["headbutt", "meanlook", "suckerpunch", "quickguard"],
  bisharp: ["headbutt", "meanlook", "suckerpunch", "quickguard"],
  rufflet: ["rocksmash", "roost"],
  braviary: ["rocksmash", "roost"],
  braviaryhisui: ["rocksmash", "roost"],
  vullaby: ["toxic", "meanlook", "roost"],
  deino: ["astonish", "headsmash", "doublehit", "belch"],
  zweilous: ["astonish", "headsmash", "doublehit", "belch"],
  hydreigon: ["astonish", "headsmash", "doublehit", "belch"],
  larvesta: ["thrash", "absorb", "harden", "morningsun"],
  chespin: ["superfang", "curse", "bellydrum", "spikes", "synthesis", "wideguard", "quickguard"],
  quilladin: ["superfang", "curse", "bellydrum", "spikes", "synthesis", "wideguard", "quickguard"],
  fennekin: ["hypnosis", "heatwave", "wish", "copycat", "magicroom"],
  braixen: ["hypnosis", "heatwave", "wish", "copycat", "magicroom"],
  delphox: ["hypnosis", "heatwave", "wish", "copycat", "magicroom"],
  froakie: ["counter", "spikes", "toxicspikes", "switcheroo", "retaliate"],
  frogadier: ["counter", "spikes", "toxicspikes", "switcheroo", "retaliate"],
  greninja: ["counter", "spikes", "toxicspikes", "switcheroo", "retaliate"],
  fletchling: ["defog", "flamecharge", "quickguard"],
  fletchinder: ["defog", "flamecharge", "quickguard"],
  scatterbug: ["poisonpowder", "ragepowder"],
  spewpa: ["poisonpowder", "ragepowder"],
  vivillon: ["poisonpowder", "ragepowder"],
  litleo: ["firespin", "yawn", "flareblitz", "entrainment"],
  pyroar: ["firespin", "yawn", "flareblitz", "entrainment"],
  floette: ["endeavor", "copycat", "tearfullook"],
  florges: ["endeavor", "copycat", "tearfullook"],
  skiddo: ["defensecurl", "rollout", "milkdrink", "grassyterrain"],
  gogoat: ["defensecurl", "rollout", "milkdrink", "grassyterrain"],
  espurr: ["yawn", "tickle"],
  meowstic: ["yawn", "tickle"],
  inkay: ["disable", "destinybond", "acupressure"],
  malamar: ["disable", "destinybond", "acupressure"],
  skrelp: ["haze", "acidarmor", "twister", "dragontail"],
  dragalge: ["haze", "acidarmor", "twister", "dragontail"],
  clauncher: ["bubblebeam", "aquatail", "entrainment"],
  clawitzer: ["bubblebeam", "aquatail", "entrainment"],
  sylveon: ["doublekick", "curse", "flail", "mud-slap", "detect", "wish", "yawn", "tickle"],
  hawlucha: ["meanlook", "crosschop", "feint", "defog", "entrainment", "quickguard"],
  dedenne: ["covet", "magnetrise", "tearfullook"],
  goomy: ["counter", "lifedew"],
  sliggoo: ["counter", "lifedew"],
  sliggoohisui: ["counter", "lifedew"],
  goodra: ["counter", "lifedew"],
  goodrahisui: ["counter", "lifedew"],
  klefki: ["magnetrise", "switcheroo"],
  phantump: ["disable", "suckerpunch", "allyswitch"],
  trevenant: ["disable", "suckerpunch", "allyswitch"],
  bergmite: ["mist", "mirrorcoat", "auroraveil"],
  avalugg: ["mist", "mirrorcoat", "auroraveil"],
  avalugghisui: ["mist", "mirrorcoat", "auroraveil"],
  noibat: ["dragonrush", "switcheroo", "defog"],
  noivern: ["dragonrush", "switcheroo", "defog"],
  rowlet: ["doubleteam", "confuseray", "knockoff", "roost", "defog"],
  dartrix: ["doubleteam", "confuseray", "knockoff", "roost", "defog"],
  decidueye: ["doubleteam", "confuseray", "knockoff", "roost", "defog"],
  decidueyehisui: ["doubleteam", "confuseray", "knockoff", "roost", "defog"],
  litten: ["fakeout", "partingshot", "powertrip"],
  torracat: ["fakeout", "partingshot", "powertrip"],
  popplio: ["perishsong", "aquaring", "lifedew"],
  brionne: ["perishsong", "aquaring", "lifedew"],
  primarina: ["perishsong", "aquaring", "lifedew"],
  pikipek: ["skyattack", "gunkshot", "boomburst"],
  trumbeak: ["skyattack", "gunkshot", "boomburst"],
  toucannon: ["skyattack", "gunkshot", "boomburst"],
  yungoos: ["endeavor", "lastresort", "thunderfang", "icefang", "firefang"],
  gumshoos: ["endeavor", "lastresort", "thunderfang", "icefang", "firefang"],
  grubbin: ["harden", "discharge"],
  charjabug: ["harden", "discharge"],
  vikavolt: ["harden", "discharge"],
  crabrawler: ["focuspunch", "superpower", "endeavor", "wideguard"],
  crabominable: ["focuspunch", "superpower", "endeavor", "wideguard"],
  oricorio: ["attract", "safeguard", "pluck", "defog", "quiverdance"],
  oricoriopompom: ["attract", "safeguard", "pluck", "defog", "quiverdance"],
  oricoriopau: ["attract", "safeguard", "pluck", "defog", "quiverdance"],
  oricoriosensu: ["attract", "safeguard", "pluck", "defog", "quiverdance"],
  cutiefly: ["stickyweb", "moonblast", "aromaticmist"],
  ribombee: ["stickyweb", "moonblast", "aromaticmist"],
  rockruff: ["thrash", "endeavor", "lastresort", "suckerpunch"],
  lycanroc: ["thrash", "endeavor", "lastresort", "suckerpunch"],
  lycanrocmidnight: ["thrash", "endeavor", "lastresort", "suckerpunch"],
  lycanrocdusk: ["thrash", "endeavor", "lastresort", "suckerpunch"],
  mareanie: ["haze", "stockpile", "spitup", "swallow", "infestation"],
  mudbray: ["double-edge", "roar", "fissure", "endeavor", "smackdown"],
  mudsdale: ["double-edge", "roar", "fissure", "endeavor", "smackdown"],
  dewpider: ["stockpile", "spitup", "powersplit", "stickyweb"],
  fomantis: ["superpower", "worryseed", "defog"],
  lurantis: ["superpower", "worryseed", "defog"],
  salandit: ["sandattack", "mud-slap", "fakeout", "belch"],
  salazzle: ["sandattack", "mud-slap", "fakeout", "belch"],
  bounsweet: ["synthesis", "endeavor", "acupressure"],
  steenee: ["synthesis", "endeavor", "acupressure"],
  passimian: ["counter", "seismictoss", "quickattack", "knockoff", "feint", "quickguard"],
  sandygast: ["curse", "destinybond", "ancientpower", "stockpile", "spitup", "swallow"],
  palossand: ["curse", "destinybond", "ancientpower", "stockpile", "spitup", "swallow"],
  komala: ["sing", "charm", "wish", "superpower", "playrough"],
  bruxish: ["superfang", "poisonfang", "waterpulse", "icefang"],
  grookey: ["strength", "leechseed", "growth", "fakeout", "hammerarm", "worryseed"],
  thwackey: ["strength", "leechseed", "growth", "fakeout", "hammerarm", "worryseed"],
  scorbunny: ["sandattack", "highjumpkick", "superfang", "suckerpunch"],
  raboot: ["sandattack", "highjumpkick", "superfang", "suckerpunch"],
  cinderace: ["sandattack", "highjumpkick", "superfang", "suckerpunch"],
  sobble: ["mist", "doubleteam", "haze", "aquaring", "iceshard", "aquajet", "fellstinger"],
  drizzile: ["mist", "doubleteam", "haze", "aquaring", "iceshard", "aquajet", "fellstinger"],
  inteleon: ["mist", "doubleteam", "haze", "aquaring", "iceshard", "aquajet", "fellstinger"],
  skwovet: ["defensecurl", "bellydrum", "rollout", "lastresort"],
  greedent: ["defensecurl", "bellydrum", "rollout", "lastresort"],
  rookidee: ["sandattack", "skyattack", "spite", "rocksmash", "roost", "tailwind", "defog"],
  corvisquire: ["sandattack", "skyattack", "spite", "rocksmash", "roost", "tailwind", "defog"],
  corviknight: ["sandattack", "skyattack", "spite", "rocksmash", "roost", "tailwind", "defog"],
  chewtle: ["gastroacid", "shellsmash", "dragontail"],
  drednaw: ["gastroacid", "shellsmash", "dragontail"],
  rolycoly: ["explosion", "mud-slap", "block"],
  carkol: ["explosion", "mud-slap", "block"],
  coalossal: ["explosion", "mud-slap", "block"],
  applin: ["defensecurl", "rollout", "recycle", "suckerpunch"],
  flapple: ["defensecurl", "rollout", "recycle", "suckerpunch"],
  appletun: ["defensecurl", "rollout", "recycle", "suckerpunch"],
  silicobra: ["mud-slap", "poisontail", "lastresort", "dragonrush", "belch"],
  sandaconda: ["mud-slap", "poisontail", "lastresort", "dragonrush", "belch"],
  cramorant: ["featherdance", "aerialace", "roost", "aquaring", "defog", "aquacutter"],
  arrokuda: ["thrash", "slash", "acupressure", "nightslash"],
  barraskewda: ["thrash", "slash", "acupressure", "nightslash"],
  toxel: ["endeavor", "metalsound"],
  toxtricity: ["endeavor", "metalsound"],
  toxtricitylowkey: ["endeavor", "metalsound"],
  sinistea: ["allyswitch"],
  polteageist: ["allyswitch"],
  hatenna: ["afteryou", "quash", "mysticalfire", "nuzzle"],
  hattrem: ["afteryou", "quash", "mysticalfire", "nuzzle"],
  hatterene: ["afteryou", "quash", "mysticalfire", "nuzzle"],
  impidimp: ["partingshot"],
  morgrem: ["partingshot"],
  perrserker: ["double-edge", "curse", "flail", "spite", "covet", "nightslash"],
  milcery: ["lastresort", "baby-dolleyes"],
  pincurchin: ["memento", "suckerpunch"],
  snom: ["mirrorcoat", "bugbite", "fairywind"],
  frosmoth: ["mirrorcoat", "bugbite", "fairywind"],
  stonjourner: ["curse", "ancientpower"],
  eiscue: ["double-edge", "bellydrum", "aquaring", "headsmash", "soak", "iciclecrash"],
  eiscuenoice: ["double-edge", "bellydrum", "aquaring", "headsmash", "soak", "iciclecrash"],
  indeedee: ["psychup", "fakeout", "extrasensory"],
  morpeko: ["superfang", "swagger", "rapidspin", "fakeout", "charge", "tickle", "quash", "partingshot"],
  cufant: ["whirlwind", "slam", "double-edge", "fissure", "defensecurl", "curse", "swagger", "belch"],
  copperajah: ["whirlwind", "slam", "double-edge", "fissure", "defensecurl", "curse", "swagger", "belch"],
  duraludon: ["slash", "mirrorcoat", "nightslash"],
  dreepy: ["disable", "doubleteam", "confuseray", "curse", "suckerpunch", "dragontail"],
  drakloak: ["disable", "doubleteam", "confuseray", "curse", "suckerpunch", "dragontail"],
  wyrdeer: ["doublekick", "thrash", "bite", "disable", "spite", "megahorn", "extrasensory", "psyshieldbash"],
  kleavor: ["counter", "feint", "nightslash", "defog", "quickguard"],
  basculegionf: ["endeavor", "lastrespects"],
  sprigatito: ["leechseed", "copycat", "suckerpunch", "allyswitch", "petalblizzard"],
  floragato: ["leechseed", "copycat", "suckerpunch", "allyswitch", "petalblizzard"],
  meowscarada: ["leechseed", "copycat", "suckerpunch", "allyswitch", "petalblizzard"],
  fuecoco: ["curse", "encore", "slackoff", "belch"],
  crocalor: ["curse", "encore", "slackoff", "belch"],
  skeledirge: ["curse", "encore", "slackoff", "belch"],
  quaxly: ["detect", "rapidspin", "roost", "lastresort"],
  quaxwell: ["detect", "rapidspin", "roost", "lastresort"],
  quaquaval: ["detect", "rapidspin", "roost", "lastresort"],
  lechonk: ["stockpile", "spitup", "swallow", "endeavor", "stuffcheeks"],
  oinkologne: ["stockpile", "spitup", "swallow", "endeavor", "stuffcheeks"],
  oinkolognef: ["stockpile", "spitup", "swallow", "endeavor", "stuffcheeks"],
  tarountula: ["memento", "suckerpunch", "firstimpression", "lunge"],
  spidops: ["memento", "suckerpunch", "firstimpression", "lunge"],
  nymble: ["counter", "skittersmack"],
  lokix: ["counter", "skittersmack"],
  pawmi: ["machpunch", "sweetkiss", "fakeout", "wish"],
  pawmo: ["machpunch", "sweetkiss", "fakeout", "wish"],
  pawmot: ["machpunch", "sweetkiss", "fakeout", "wish"],
  tandemaus: ["bite", "batonpass", "tickle", "feint", "switcheroo", "afteryou"],
  fidough: ["sweetscent", "wish", "yawn", "howl", "copycat"],
  smoliv: ["synthesis", "memento", "weatherball", "strengthsap"],
  dolliv: ["synthesis", "memento", "weatherball", "strengthsap"],
  arboliva: ["synthesis", "memento", "weatherball", "strengthsap"],
  squawkabilly: ["double-edge", "flatter", "finalgambit", "partingshot"],
  nacli: ["fissure", "curse", "ancientpower", "powergem"],
  naclstack: ["fissure", "curse", "ancientpower", "powergem"],
  charcadet: ["disable", "spite", "destinybond"],
  tadbulb: ["muddywater", "soak", "paraboliccharge"],
  bellibolt: ["muddywater", "soak", "paraboliccharge"],
  wattrel: ["stockpile", "spitup", "swallow", "endeavor", "featherdance", "weatherball"],
  kilowattrel: ["stockpile", "spitup", "swallow", "endeavor", "featherdance", "weatherball"],
  maschiff: ["destinybond", "endeavor", "retaliate", "playrough"],
  mabosstiff: ["destinybond", "endeavor", "retaliate", "playrough"],
  shroodle: ["toxic", "superfang", "swagger", "copycat", "crosspoison", "partingshot"],
  grafaiai: ["toxic", "superfang", "swagger", "copycat", "crosspoison", "partingshot"],
  bramblin: ["leechseed", "beatup", "block", "shadowsneak", "strengthsap"],
  brambleghast: ["leechseed", "beatup", "block", "shadowsneak", "strengthsap"],
  toedscool: ["leechseed", "toxic", "rapidspin", "mirrorcoat", "knockoff", "tickle", "acupressure", "ragepowder"],
  toedscruel: ["leechseed", "toxic", "rapidspin", "mirrorcoat", "knockoff", "tickle", "acupressure", "ragepowder"],
  klawf: ["crabhammer", "ancientpower", "knockoff", "endeavor"],
  capsakid: ["leechseed", "rollout", "ingrain", "worryseed", "ragepowder"],
  rellor: ["recover", "memento", "weatherball", "cosmicpower"],
  rabsca: ["recover", "memento", "weatherball", "cosmicpower"],
  flittle: ["hypnosis", "roost", "allyswitch"],
  espathra: ["hypnosis", "roost", "allyswitch"],
  tinkatink: ["feint", "quash", "icehammer"],
  tinkatuff: ["feint", "quash", "icehammer"],
  wiglett: ["memento", "finalgambit"],
  wugtrio: ["memento", "finalgambit"],
  bombirdier: ["skyattack", "featherdance", "roost", "suckerpunch", "powertrip"],
  finizen: ["counter", "haze", "tickle", "bounce", "boomburst"],
  palafin: ["counter", "haze", "tickle", "bounce", "boomburst"],
  palafinhero: ["counter", "haze", "tickle", "bounce", "boomburst"],
  varoom: ["toxic", "haze", "self-destruct", "torment", "partingshot"],
  revavroom: ["toxic", "haze", "self-destruct", "torment", "partingshot"],
  cyclizar: ["irontail", "knockoff", "aquatail", "powerwhip"],
  orthworm: ["curse", "metalburst", "coil"],
  glimmet: ["toxic", "explosion", "memento"],
  greavard: ["disable", "destinybond", "memento", "yawn", "howl", "shadowsneak", "allyswitch"],
  houndstone: ["disable", "destinybond", "memento", "yawn", "howl", "shadowsneak", "allyswitch"],
  cetoddle: ["bellydrum", "superpower", "yawn", "entrainment", "iciclecrash"],
  cetitan: ["bellydrum", "superpower", "yawn", "entrainment", "iciclecrash"],
  veluza: ["thrash", "recover"],
  clodsire: ["doublekick", "mist", "counter", "recover", "haze", "curse", "ancientpower", "stockpile", "spitup", "swallow", "acidspray", "afteryou"],
  dudunsparce: ["headbutt", "bite", "curse", "astonish", "lastresort", "aquatail"],
  frigibax: ["iciclespear", "aquatail", "dragonrush", "freeze-dry"],
  arctibax: ["iciclespear", "aquatail", "dragonrush", "freeze-dry"],
  baxcalibur: ["iciclespear", "aquatail", "dragonrush", "freeze-dry"],
  dipplin: ["defensecurl", "rollout", "recycle", "suckerpunch"],
  hydrapple: ["defensecurl", "rollout", "recycle", "suckerpunch"],
  meowthgalar: ["flail", "spite", "covet", "double-edge", "curse", "nightslash"],
  growlithehisui: ["doublekick", "thrash", "double-edge", "morningsun", "covet", "headsmash"],
  arcaninehisui: ["doublekick", "thrash", "double-edge", "morningsun", "covet", "headsmash"],
  voltorbhisui: ["recycle", "leechseed", "worryseed"],
  electrodehisui: ["recycle", "leechseed", "worryseed"],
  wooperpaldea: ["doublekick", "counter", "recover", "curse", "ancientpower", "stockpile", "spitup", "swallow", "acidspray", "afteryou", "mist", "haze"],
  qwilfishhisui: ["supersonic", "bubblebeam", "haze", "self-destruct", "flail", "astonish", "waterpulse", "aquajet", "acidspray", "aquatail"],
  sneaselhisui: ["counter", "fakeout", "feint", "doublehit", "nightslash", "switcheroo", "quickguard"],
  zoruahisui: ["detect", "memento", "extrasensory", "comeuppance"],
  zoroarkhisui: ["detect", "memento", "extrasensory", "comeuppance"],
  flabebe: ["endeavor", "copycat", "tearfullook"],
  jangmoo: ["counter", "dragonbreath", "focuspunch"],
  hakamoo: ["counter", "dragonbreath", "focuspunch"],
  kommoo: ["counter", "dragonbreath", "focuspunch"]
}
