// This class is generated by speed-statistics-class-generator.js script

type SpeedStatistic = {
  speed: number
  percentile: number
  percentage: number
  speedEv: number
  nature: string
}

export const SPEED_STATISTICS: Record<string, SpeedStatistic[]> = {
  "Urshifu-Rapid-Strike": [
    { speed: 149, percentile: 78, percentage: 63, speedEv: 252, nature: "Adamant" },
    { speed: 163, percentile: 100, percentage: 17, speedEv: 252, nature: "Jolly" }
  ],
  Incineroar: [
    { speed: 80, percentile: 38, percentage: 30, speedEv: 0, nature: "Adamant" },
    { speed: 81, percentile: 49, percentage: 11, speedEv: 4, nature: "Careful" }
  ],
  Rillaboom: [
    { speed: 105, percentile: 13, percentage: 12, speedEv: 0, nature: "Adamant" },
    { speed: 106, percentile: 28, percentage: 15, speedEv: 4, nature: "Adamant" },
    { speed: 115, percentile: 68, percentage: 12, speedEv: 76, nature: "Adamant" }
  ],
  "Flutter Mane": [
    { speed: 188, percentile: 36, percentage: 12, speedEv: 124, nature: "Timid" },
    { speed: 190, percentile: 55, percentage: 12, speedEv: 140, nature: "Timid" },
    { speed: 205, percentile: 100, percentage: 28, speedEv: 252, nature: "Timid" }
  ],
  "Raging Bolt": [
    { speed: 95, percentile: 16, percentage: 15, speedEv: 0, nature: "Modest" },
    { speed: 96, percentile: 34, percentage: 17, speedEv: 4, nature: "Calm" },
    { speed: 127, percentile: 99, percentage: 14, speedEv: 252, nature: "Modest" }
  ],
  Amoonguss: [
    { speed: 45, percentile: 41, percentage: 41, speedEv: 0, nature: "Relaxed" },
    { speed: 50, percentile: 96, percentage: 55, speedEv: 0, nature: "Calm" }
  ],
  Farigiraf: [
    { speed: 72, percentile: 17, percentage: 17, speedEv: 0, nature: "Sassy" },
    { speed: 80, percentile: 54, percentage: 37, speedEv: 0, nature: "Calm" },
    { speed: 84, percentile: 96, percentage: 23, speedEv: 28, nature: "Bold" }
  ],
  "Ogerpon-Hearthflame": [
    { speed: 154, percentile: 61, percentage: 31, speedEv: 188, nature: "Adamant" },
    { speed: 178, percentile: 100, percentage: 16, speedEv: 252, nature: "Jolly" }
  ],
  "Calyrex-Shadow": [{ speed: 222, percentile: 100, percentage: 73, speedEv: 252, nature: "Timid" }],
  "Chien-Pao": [
    { speed: 187, percentile: 25, percentage: 24, speedEv: 252, nature: "Adamant" },
    { speed: 205, percentile: 100, percentage: 75, speedEv: 252, nature: "Jolly" }
  ],
  Whimsicott: [
    { speed: 165, percentile: 52, percentage: 30, speedEv: 108, nature: "Timid" },
    { speed: 184, percentile: 100, percentage: 29, speedEv: 252, nature: "Timid" }
  ],
  "Calyrex-Ice": [{ speed: 63, percentile: 41, percentage: 41, speedEv: 0, nature: "Brave" }],
  "Iron Hands": [
    { speed: 63, percentile: 51, percentage: 51, speedEv: 0, nature: "Brave" },
    { speed: 70, percentile: 69, percentage: 18, speedEv: 0, nature: "Adamant" }
  ],
  "Chi-Yu": [
    { speed: 150, percentile: 19, percentage: 11, speedEv: 236, nature: "Modest" },
    { speed: 152, percentile: 70, percentage: 46, speedEv: 252, nature: "Modest" },
    { speed: 167, percentile: 100, percentage: 23, speedEv: 252, nature: "Timid" }
  ],
  Tornadus: [
    { speed: 131, percentile: 14, percentage: 14, speedEv: 0, nature: "Calm" },
    { speed: 179, percentile: 100, percentage: 31, speedEv: 252, nature: "Timid" }
  ],
  Miraidon: [
    { speed: 181, percentile: 40, percentage: 29, speedEv: 204, nature: "Modest" },
    { speed: 187, percentile: 65, percentage: 17, speedEv: 252, nature: "Modest" },
    { speed: 205, percentile: 100, percentage: 30, speedEv: 252, nature: "Timid" }
  ],
  Landorus: [
    { speed: 153, percentile: 63, percentage: 44, speedEv: 252, nature: "Modest" },
    { speed: 168, percentile: 100, percentage: 34, speedEv: 252, nature: "Timid" }
  ],
  "Zamazenta-Crowned": [
    { speed: 169, percentile: 51, percentage: 24, speedEv: 164, nature: "Impish" },
    { speed: 180, percentile: 95, percentage: 21, speedEv: 252, nature: "Impish" }
  ],
  Urshifu: [
    { speed: 149, percentile: 76, percentage: 62, speedEv: 252, nature: "Adamant" },
    { speed: 163, percentile: 100, percentage: 23, speedEv: 252, nature: "Jolly" }
  ],
  "Ogerpon-Cornerstone": [
    { speed: 162, percentile: 20, percentage: 11, speedEv: 252, nature: "Adamant" },
    { speed: 178, percentile: 100, percentage: 77, speedEv: 252, nature: "Jolly" }
  ],
  "Indeedee-F": [
    { speed: 94, percentile: 39, percentage: 39, speedEv: 0, nature: "Sassy" },
    { speed: 105, percentile: 94, percentage: 55, speedEv: 0, nature: "Calm" }
  ],
  Terapagos: [
    { speed: 80, percentile: 12, percentage: 11, speedEv: 0, nature: "Modest" },
    { speed: 95, percentile: 66, percentage: 17, speedEv: 116, nature: "Modest" }
  ],
  Kyogre: [{ speed: 156, percentile: 100, percentage: 19, speedEv: 252, nature: "Timid" }],
  Pelipper: [
    { speed: 85, percentile: 26, percentage: 24, speedEv: 0, nature: "Bold" },
    { speed: 117, percentile: 87, percentage: 31, speedEv: 252, nature: "Modest" },
    { speed: 128, percentile: 100, percentage: 12, speedEv: 252, nature: "Timid" }
  ],
  Koraidon: [
    { speed: 187, percentile: 53, percentage: 12, speedEv: 252, nature: "Adamant" },
    { speed: 205, percentile: 100, percentage: 37, speedEv: 252, nature: "Jolly" }
  ],
  "Roaring Moon": [
    { speed: 174, percentile: 20, percentage: 13, speedEv: 156, nature: "Jolly" },
    { speed: 188, percentile: 100, percentage: 55, speedEv: 252, nature: "Jolly" }
  ],
  Groudon: [
    { speed: 110, percentile: 13, percentage: 11, speedEv: 0, nature: "Adamant" },
    { speed: 112, percentile: 32, percentage: 17, speedEv: 12, nature: "Adamant" },
    { speed: 119, percentile: 60, percentage: 11, speedEv: 68, nature: "Adamant" }
  ],
  "Ursaluna-Bloodmoon": [
    { speed: 64, percentile: 34, percentage: 34, speedEv: 0, nature: "Quiet" },
    { speed: 72, percentile: 55, percentage: 20, speedEv: 0, nature: "Hardy" }
  ],
  "Ogerpon-Wellspring": [
    { speed: 169, percentile: 73, percentage: 17, speedEv: 188, nature: "Jolly" },
    { speed: 178, percentile: 100, percentage: 20, speedEv: 252, nature: "Jolly" }
  ],
  Dondozo: [
    { speed: 55, percentile: 17, percentage: 11, speedEv: 0, nature: "Careful" },
    { speed: 75, percentile: 69, percentage: 32, speedEv: 156, nature: "Impish" },
    { speed: 85, percentile: 93, percentage: 13, speedEv: 236, nature: "Impish" }
  ],
  Clefairy: [
    { speed: 49, percentile: 63, percentage: 63, speedEv: 0, nature: "Sassy" },
    { speed: 55, percentile: 99, percentage: 36, speedEv: 0, nature: "Bold" }
  ],
  Grimmsnarl: [
    { speed: 80, percentile: 70, percentage: 65, speedEv: 0, nature: "Impish" },
    { speed: 81, percentile: 82, percentage: 11, speedEv: 4, nature: "Careful" }
  ],
  Ursaluna: [
    { speed: 63, percentile: 64, percentage: 64, speedEv: 0, nature: "Brave" },
    { speed: 70, percentile: 79, percentage: 15, speedEv: 0, nature: "Adamant" }
  ],
  Tatsugiri: [
    { speed: 134, percentile: 59, percentage: 48, speedEv: 252, nature: "Modest" },
    { speed: 147, percentile: 100, percentage: 32, speedEv: 252, nature: "Timid" }
  ],
  "Weezing-Galar": [
    { speed: 80, percentile: 18, percentage: 15, speedEv: 0, nature: "Bold" },
    { speed: 82, percentile: 74, percentage: 49, speedEv: 12, nature: "Bold" }
  ],
  Entei: [
    { speed: 150, percentile: 48, percentage: 13, speedEv: 236, nature: "Adamant" },
    { speed: 152, percentile: 87, percentage: 36, speedEv: 252, nature: "Adamant" },
    { speed: 167, percentile: 100, percentage: 12, speedEv: 252, nature: "Jolly" }
  ],
  Torkoal: [
    { speed: 36, percentile: 85, percentage: 85, speedEv: 0, nature: "Quiet" },
    { speed: 40, percentile: 99, percentage: 14, speedEv: 0, nature: "Modest" }
  ],
  "Zacian-Crowned": [
    { speed: 206, percentile: 47, percentage: 20, speedEv: 156, nature: "Jolly" },
    { speed: 209, percentile: 66, percentage: 11, speedEv: 172, nature: "Jolly" },
    { speed: 220, percentile: 100, percentage: 19, speedEv: 252, nature: "Jolly" }
  ],
  Ditto: [
    { speed: 68, percentile: 23, percentage: 16, speedEv: 0, nature: "Bashful" },
    { speed: 100, percentile: 41, percentage: 11, speedEv: 252, nature: "Serious" },
    { speed: 110, percentile: 100, percentage: 55, speedEv: 252, nature: "Timid" }
  ],
  Volcarona: [
    { speed: 120, percentile: 16, percentage: 16, speedEv: 0, nature: "Modest" },
    { speed: 121, percentile: 33, percentage: 16, speedEv: 4, nature: "Bold" }
  ],
  "Iron Valiant": [
    { speed: 173, percentile: 55, percentage: 34, speedEv: 172, nature: "Jolly" },
    { speed: 184, percentile: 100, percentage: 37, speedEv: 252, nature: "Jolly" }
  ],
  Archaludon: [
    { speed: 105, percentile: 35, percentage: 29, speedEv: 0, nature: "Modest" },
    { speed: 150, percentile: 100, percentage: 14, speedEv: 252, nature: "Timid" }
  ],
  Lunala: [
    { speed: 117, percentile: 17, percentage: 11, speedEv: 0, nature: "Modest" },
    { speed: 118, percentile: 37, percentage: 20, speedEv: 4, nature: "Modest" },
    { speed: 126, percentile: 73, percentage: 13, speedEv: 68, nature: "Modest" }
  ],
  Regieleki: [
    { speed: 252, percentile: 72, percentage: 61, speedEv: 252, nature: "Modest" },
    { speed: 277, percentile: 100, percentage: 23, speedEv: 252, nature: "Timid" }
  ],
  Smeargle: [
    { speed: 85, percentile: 30, percentage: 30, speedEv: 0, nature: "Relaxed" },
    { speed: 139, percentile: 100, percentage: 63, speedEv: 252, nature: "Jolly" }
  ],
  "Gouging Fire": [
    { speed: 154, percentile: 56, percentage: 21, speedEv: 228, nature: "Jolly" },
    { speed: 157, percentile: 100, percentage: 41, speedEv: 252, nature: "Jolly" }
  ],
  Gholdengo: [
    { speed: 127, percentile: 64, percentage: 12, speedEv: 180, nature: "Modest" },
    { speed: 149, percentile: 100, percentage: 21, speedEv: 252, nature: "Timid" }
  ],
  Dragonite: [
    { speed: 100, percentile: 24, percentage: 23, speedEv: 0, nature: "Adamant" },
    { speed: 101, percentile: 45, percentage: 21, speedEv: 4, nature: "Adamant" },
    { speed: 132, percentile: 93, percentage: 11, speedEv: 252, nature: "Adamant" }
  ],
  "Ting-Lu": [
    { speed: 58, percentile: 28, percentage: 28, speedEv: 0, nature: "Relaxed" },
    { speed: 65, percentile: 64, percentage: 35, speedEv: 0, nature: "Impish" },
    { speed: 66, percentile: 92, percentage: 29, speedEv: 4, nature: "Adamant" }
  ],
  "Walking Wake": [{ speed: 177, percentile: 100, percentage: 58, speedEv: 252, nature: "Timid" }],
  Jumpluff: [{ speed: 178, percentile: 100, percentage: 69, speedEv: 252, nature: "Timid" }],
  Regidrago: [
    { speed: 129, percentile: 39, percentage: 19, speedEv: 228, nature: "Modest" },
    { speed: 132, percentile: 74, percentage: 33, speedEv: 252, nature: "Modest" },
    { speed: 145, percentile: 100, percentage: 22, speedEv: 252, nature: "Timid" }
  ],
  Annihilape: [{ speed: 156, percentile: 100, percentage: 54, speedEv: 252, nature: "Jolly" }],
  Tsareena: [
    { speed: 124, percentile: 52, percentage: 15, speedEv: 252, nature: "Adamant" },
    { speed: 129, percentile: 81, percentage: 28, speedEv: 204, nature: "Jolly" }
  ],
  Sneasler: [
    { speed: 172, percentile: 66, percentage: 37, speedEv: 252, nature: "Adamant" },
    { speed: 189, percentile: 100, percentage: 29, speedEv: 252, nature: "Jolly" }
  ],
  "Ninetales-Alola": [{ speed: 177, percentile: 100, percentage: 58, speedEv: 252, nature: "Timid" }],
  Kingambit: [
    { speed: 63, percentile: 29, percentage: 29, speedEv: 0, nature: "Brave" },
    { speed: 70, percentile: 76, percentage: 48, speedEv: 0, nature: "Adamant" },
    { speed: 71, percentile: 89, percentage: 12, speedEv: 4, nature: "Adamant" }
  ],
  "Scream Tail": [
    { speed: 170, percentile: 61, percentage: 11, speedEv: 188, nature: "Jolly" },
    { speed: 179, percentile: 100, percentage: 29, speedEv: 252, nature: "Jolly" }
  ],
  Mienshao: [
    { speed: 157, percentile: 25, percentage: 22, speedEv: 252, nature: "Adamant" },
    { speed: 172, percentile: 100, percentage: 73, speedEv: 252, nature: "Jolly" }
  ],
  "Iron Bundle": [{ speed: 206, percentile: 100, percentage: 82, speedEv: 252, nature: "Timid" }],
  Ogerpon: [
    { speed: 162, percentile: 58, percentage: 16, speedEv: 252, nature: "Adamant" },
    { speed: 178, percentile: 100, percentage: 30, speedEv: 252, nature: "Jolly" }
  ],
  Sinistcha: [
    { speed: 81, percentile: 29, percentage: 29, speedEv: 0, nature: "Sassy" },
    { speed: 90, percentile: 81, percentage: 51, speedEv: 0, nature: "Calm" },
    { speed: 91, percentile: 92, percentage: 11, speedEv: 4, nature: "Calm" }
  ],
  "Iron Crown": [
    { speed: 150, percentile: 37, percentage: 15, speedEv: 252, nature: "Calm" },
    { speed: 165, percentile: 100, percentage: 51, speedEv: 252, nature: "Timid" }
  ],
  "Iron Jugulis": [
    { speed: 157, percentile: 46, percentage: 28, speedEv: 116, nature: "Timid" },
    { speed: 176, percentile: 100, percentage: 27, speedEv: 252, nature: "Timid" }
  ],
  Eternatus: [
    { speed: 150, percentile: 11, percentage: 11, speedEv: 0, nature: "Modest" },
    { speed: 181, percentile: 66, percentage: 20, speedEv: 244, nature: "Modest" },
    { speed: 200, percentile: 100, percentage: 11, speedEv: 252, nature: "Timid" }
  ],
  Gallade: [
    { speed: 90, percentile: 59, percentage: 59, speedEv: 0, nature: "Brave" },
    { speed: 100, percentile: 74, percentage: 15, speedEv: 0, nature: "Adamant" }
  ],
  Gothitelle: [
    { speed: 76, percentile: 31, percentage: 31, speedEv: 0, nature: "Sassy" },
    { speed: 85, percentile: 77, percentage: 45, speedEv: 0, nature: "Calm" }
  ],
  Basculegion: [
    { speed: 118, percentile: 44, percentage: 32, speedEv: 156, nature: "Adamant" },
    { speed: 130, percentile: 89, percentage: 34, speedEv: 252, nature: "Adamant" }
  ],
  "Landorus-Therian": [
    { speed: 143, percentile: 47, percentage: 17, speedEv: 252, nature: "Adamant" },
    { speed: 157, percentile: 100, percentage: 36, speedEv: 252, nature: "Jolly" }
  ],
  Tyranitar: [
    { speed: 81, percentile: 41, percentage: 31, speedEv: 0, nature: "Adamant" },
    { speed: 113, percentile: 96, percentage: 34, speedEv: 252, nature: "Adamant" }
  ],
  Gastrodon: [
    { speed: 53, percentile: 32, percentage: 32, speedEv: 0, nature: "Relaxed" },
    { speed: 59, percentile: 87, percentage: 54, speedEv: 0, nature: "Modest" }
  ],
  Sableye: [
    { speed: 63, percentile: 14, percentage: 14, speedEv: 0, nature: "Sassy" },
    { speed: 70, percentile: 80, percentage: 66, speedEv: 0, nature: "Bold" },
    { speed: 112, percentile: 100, percentage: 15, speedEv: 252, nature: "Jolly" }
  ],
  Umbreon: [
    { speed: 85, percentile: 72, percentage: 64, speedEv: 0, nature: "Calm" },
    { speed: 92, percentile: 97, percentage: 12, speedEv: 52, nature: "Bold" }
  ],
  "Iron Treads": [
    { speed: 165, percentile: 37, percentage: 11, speedEv: 188, nature: "Jolly" },
    { speed: 173, percentile: 100, percentage: 45, speedEv: 252, nature: "Jolly" }
  ],
  Venusaur: [
    { speed: 132, percentile: 71, percentage: 30, speedEv: 252, nature: "Modest" },
    { speed: 145, percentile: 100, percentage: 26, speedEv: 252, nature: "Timid" }
  ],
  "Moltres-Galar": [{ speed: 112, percentile: 31, percentage: 20, speedEv: 12, nature: "Modest" }],
  Araquanid: [
    { speed: 55, percentile: 66, percentage: 66, speedEv: 0, nature: "Brave" },
    { speed: 62, percentile: 93, percentage: 27, speedEv: 0, nature: "Impish" }
  ],
  Comfey: [
    { speed: 120, percentile: 46, percentage: 40, speedEv: 0, nature: "Bold" },
    { speed: 121, percentile: 61, percentage: 15, speedEv: 4, nature: "Bold" },
    { speed: 124, percentile: 81, percentage: 20, speedEv: 28, nature: "Bold" }
  ],
  "Wo-Chien": [
    { speed: 90, percentile: 33, percentage: 29, speedEv: 0, nature: "Modest" },
    { speed: 114, percentile: 97, percentage: 43, speedEv: 188, nature: "Bold" }
  ],
  "Kyurem-White": [
    { speed: 117, percentile: 31, percentage: 13, speedEv: 12, nature: "Modest" },
    { speed: 147, percentile: 76, percentage: 13, speedEv: 252, nature: "Modest" },
    { speed: 161, percentile: 100, percentage: 14, speedEv: 252, nature: "Timid" }
  ],
  "Lilligant-Hisui": [
    { speed: 157, percentile: 39, percentage: 33, speedEv: 252, nature: "Adamant" },
    { speed: 172, percentile: 100, percentage: 60, speedEv: 252, nature: "Jolly" }
  ],
  Thundurus: [
    { speed: 131, percentile: 34, percentage: 33, speedEv: 0, nature: "Modest" },
    { speed: 132, percentile: 54, percentage: 20, speedEv: 4, nature: "Calm" },
    { speed: 179, percentile: 100, percentage: 15, speedEv: 252, nature: "Timid" }
  ],
  "Brute Bonnet": [
    { speed: 67, percentile: 22, percentage: 22, speedEv: 0, nature: "Brave" },
    { speed: 75, percentile: 48, percentage: 26, speedEv: 0, nature: "Adamant" },
    { speed: 76, percentile: 61, percentage: 13, speedEv: 4, nature: "Impish" }
  ],
  Raichu: [
    { speed: 168, percentile: 40, percentage: 13, speedEv: 180, nature: "Timid" },
    { speed: 178, percentile: 100, percentage: 54, speedEv: 252, nature: "Jolly" }
  ],
  Porygon2: [
    { speed: 72, percentile: 70, percentage: 70, speedEv: 0, nature: "Sassy" },
    { speed: 80, percentile: 89, percentage: 19, speedEv: 0, nature: "Hardy" }
  ],
  Maushold: [
    { speed: 131, percentile: 27, percentage: 26, speedEv: 0, nature: "Bold" },
    { speed: 179, percentile: 100, percentage: 42, speedEv: 252, nature: "Jolly" }
  ],
  Talonflame: [
    { speed: 178, percentile: 21, percentage: 14, speedEv: 252, nature: "Serious" },
    { speed: 188, percentile: 40, percentage: 11, speedEv: 196, nature: "Timid" },
    { speed: 195, percentile: 100, percentage: 44, speedEv: 252, nature: "Jolly" }
  ],
  Cresselia: [
    { speed: 94, percentile: 43, percentage: 43, speedEv: 0, nature: "Sassy" },
    { speed: 105, percentile: 83, percentage: 40, speedEv: 0, nature: "Calm" }
  ],
  Latios: [{ speed: 178, percentile: 100, percentage: 83, speedEv: 252, nature: "Timid" }],
  Okidogi: [
    { speed: 100, percentile: 18, percentage: 15, speedEv: 0, nature: "Adamant" },
    { speed: 112, percentile: 57, percentage: 12, speedEv: 92, nature: "Adamant" },
    { speed: 113, percentile: 72, percentage: 15, speedEv: 100, nature: "Adamant" }
  ],
  Electabuzz: [{ speed: 125, percentile: 71, percentage: 71, speedEv: 0, nature: "Bold" }],
  Tinkaton: [
    { speed: 114, percentile: 19, percentage: 16, speedEv: 0, nature: "Careful" },
    { speed: 116, percentile: 39, percentage: 15, speedEv: 12, nature: "Adamant" },
    { speed: 124, percentile: 56, percentage: 11, speedEv: 76, nature: "Adamant" }
  ],
  Armarouge: [
    { speed: 85, percentile: 29, percentage: 29, speedEv: 0, nature: "Quiet" },
    { speed: 95, percentile: 62, percentage: 33, speedEv: 0, nature: "Modest" },
    { speed: 103, percentile: 83, percentage: 13, speedEv: 60, nature: "Modest" }
  ],
  "Ho-Oh": [
    { speed: 110, percentile: 24, percentage: 23, speedEv: 0, nature: "Impish" },
    { speed: 112, percentile: 43, percentage: 13, speedEv: 12, nature: "Adamant" },
    { speed: 113, percentile: 58, percentage: 15, speedEv: 20, nature: "Careful" }
  ],
  Bronzong: [
    { speed: 47, percentile: 84, percentage: 84, speedEv: 0, nature: "Relaxed" },
    { speed: 53, percentile: 99, percentage: 15, speedEv: 0, nature: "Modest" }
  ],
  Hatterene: [{ speed: 44, percentile: 88, percentage: 88, speedEv: 0, nature: "Sassy" }],
  "Iron Leaves": [{ speed: 171, percentile: 100, percentage: 81, speedEv: 252, nature: "Jolly" }],
  Chandelure: [
    { speed: 103, percentile: 49, percentage: 25, speedEv: 20, nature: "Modest" },
    { speed: 132, percentile: 90, percentage: 25, speedEv: 252, nature: "Modest" }
  ],
  Heatran: [
    { speed: 87, percentile: 16, percentage: 16, speedEv: 0, nature: "Quiet" },
    { speed: 97, percentile: 47, percentage: 30, speedEv: 0, nature: "Modest" },
    { speed: 98, percentile: 63, percentage: 16, speedEv: 4, nature: "Modest" }
  ],
  "Zapdos-Galar": [
    { speed: 108, percentile: 16, percentage: 16, speedEv: 0, nature: "Brave" },
    { speed: 152, percentile: 55, percentage: 14, speedEv: 252, nature: "Adamant" },
    { speed: 167, percentile: 100, percentage: 39, speedEv: 252, nature: "Jolly" }
  ],
  Dragapult: [
    { speed: 194, percentile: 20, percentage: 15, speedEv: 252, nature: "Modest" },
    { speed: 213, percentile: 100, percentage: 71, speedEv: 252, nature: "Jolly" }
  ],
  "Iron Moth": [{ speed: 178, percentile: 100, percentage: 57, speedEv: 252, nature: "Timid" }],
  Alcremie: [
    { speed: 75, percentile: 67, percentage: 67, speedEv: 0, nature: "Relaxed" },
    { speed: 84, percentile: 88, percentage: 20, speedEv: 0, nature: "Calm" }
  ],
  Rayquaza: [
    { speed: 147, percentile: 73, percentage: 13, speedEv: 252, nature: "Adamant" },
    { speed: 161, percentile: 100, percentage: 22, speedEv: 252, nature: "Hasty" }
  ],
  "Arcanine-Hisui": [
    { speed: 138, percentile: 45, percentage: 20, speedEv: 220, nature: "Adamant" },
    { speed: 142, percentile: 69, percentage: 18, speedEv: 252, nature: "Adamant" },
    { speed: 156, percentile: 100, percentage: 27, speedEv: 252, nature: "Jolly" }
  ],
  Garganacl: [
    { speed: 49, percentile: 40, percentage: 40, speedEv: 0, nature: "Relaxed" },
    { speed: 55, percentile: 95, percentage: 55, speedEv: 0, nature: "Impish" }
  ],
  Weezing: [{ speed: 80, percentile: 50, percentage: 48, speedEv: 0, nature: "Calm" }],
  Indeedee: [
    { speed: 115, percentile: 31, percentage: 17, speedEv: 0, nature: "Bold" },
    { speed: 147, percentile: 52, percentage: 14, speedEv: 252, nature: "Modest" },
    { speed: 161, percentile: 100, percentage: 43, speedEv: 252, nature: "Timid" }
  ],
  "Typhlosion-Hisui": [
    { speed: 147, percentile: 33, percentage: 22, speedEv: 252, nature: "Modest" },
    { speed: 161, percentile: 100, percentage: 58, speedEv: 252, nature: "Timid" }
  ],
  "Necrozma-Dawn-Wings": [
    { speed: 87, percentile: 54, percentage: 54, speedEv: 0, nature: "Quiet" },
    { speed: 97, percentile: 91, percentage: 37, speedEv: 0, nature: "Modest" }
  ],
  Garchomp: [
    { speed: 122, percentile: 13, percentage: 13, speedEv: 0, nature: "Adamant" },
    { speed: 154, percentile: 43, percentage: 17, speedEv: 252, nature: "Adamant" },
    { speed: 169, percentile: 100, percentage: 55, speedEv: 252, nature: "Naive" }
  ],
  Oranguru: [
    { speed: 72, percentile: 65, percentage: 65, speedEv: 0, nature: "Sassy" },
    { speed: 80, percentile: 89, percentage: 22, speedEv: 0, nature: "Calm" }
  ],
  Suicune: [
    { speed: 105, percentile: 26, percentage: 25, speedEv: 0, nature: "Bold" },
    { speed: 112, percentile: 52, percentage: 16, speedEv: 52, nature: "Bold" },
    { speed: 114, percentile: 73, percentage: 11, speedEv: 68, nature: "Calm" }
  ],
  Murkrow: [
    { speed: 111, percentile: 69, percentage: 68, speedEv: 0, nature: "Careful" },
    { speed: 112, percentile: 80, percentage: 11, speedEv: 4, nature: "Careful" }
  ],
  Glimmora: [{ speed: 151, percentile: 100, percentage: 60, speedEv: 252, nature: "Timid" }],
  Politoed: [
    { speed: 81, percentile: 15, percentage: 15, speedEv: 0, nature: "Sassy" },
    { speed: 90, percentile: 63, percentage: 48, speedEv: 0, nature: "Calm" }
  ],
  Lugia: [
    { speed: 130, percentile: 41, percentage: 40, speedEv: 0, nature: "Modest" },
    { speed: 131, percentile: 67, percentage: 25, speedEv: 4, nature: "Bold" }
  ],
  "Zoroark-Hisui": [
    { speed: 162, percentile: 42, percentage: 27, speedEv: 252, nature: "Modest" },
    { speed: 178, percentile: 100, percentage: 57, speedEv: 252, nature: "Timid" }
  ],
  Ceruledge: [
    { speed: 105, percentile: 33, percentage: 32, speedEv: 0, nature: "Impish" },
    { speed: 150, percentile: 100, percentage: 22, speedEv: 252, nature: "Jolly" }
  ],
  "Sandy Shocks": [{ speed: 168, percentile: 100, percentage: 76, speedEv: 252, nature: "Timid" }],
  Hitmontop: [
    { speed: 90, percentile: 50, percentage: 45, speedEv: 0, nature: "Adamant" },
    { speed: 91, percentile: 70, percentage: 21, speedEv: 4, nature: "Adamant" }
  ],
  Milotic: [
    { speed: 101, percentile: 47, percentage: 41, speedEv: 0, nature: "Bold" },
    { speed: 106, percentile: 85, percentage: 24, speedEv: 36, nature: "Calm" }
  ],
  Charizard: [
    { speed: 152, percentile: 35, percentage: 21, speedEv: 252, nature: "Modest" },
    { speed: 167, percentile: 100, percentage: 59, speedEv: 252, nature: "Timid" }
  ],
  Bastiodon: [
    { speed: 45, percentile: 71, percentage: 71, speedEv: 0, nature: "Sassy" },
    { speed: 50, percentile: 100, percentage: 29, speedEv: 0, nature: "Bold" }
  ],
  Primarina: [
    { speed: 72, percentile: 20, percentage: 20, speedEv: 0, nature: "Quiet" },
    { speed: 80, percentile: 65, percentage: 45, speedEv: 0, nature: "Modest" }
  ],
  Magmar: [{ speed: 113, percentile: 64, percentage: 59, speedEv: 0, nature: "Careful" }],
  Mimikyu: [
    { speed: 104, percentile: 37, percentage: 37, speedEv: 0, nature: "Brave" },
    { speed: 116, percentile: 67, percentage: 30, speedEv: 0, nature: "Impish" },
    { speed: 162, percentile: 100, percentage: 15, speedEv: 252, nature: "Timid" }
  ],
  Scizor: [
    { speed: 76, percentile: 12, percentage: 12, speedEv: 0, nature: "Brave" },
    { speed: 85, percentile: 71, percentage: 59, speedEv: 0, nature: "Adamant" }
  ],
  Regigigas: [
    { speed: 120, percentile: 32, percentage: 27, speedEv: 0, nature: "Hardy" },
    { speed: 152, percentile: 73, percentage: 15, speedEv: 252, nature: "Adamant" },
    { speed: 167, percentile: 100, percentage: 21, speedEv: 252, nature: "Jolly" }
  ],
  "Goodra-Hisui": [
    { speed: 72, percentile: 26, percentage: 26, speedEv: 0, nature: "Relaxed" },
    { speed: 80, percentile: 75, percentage: 49, speedEv: 0, nature: "Impish" }
  ],
  Corviknight: [{ speed: 87, percentile: 59, percentage: 51, speedEv: 0, nature: "Impish" }],
  Flamigo: [
    { speed: 110, percentile: 15, percentage: 13, speedEv: 0, nature: "Adamant" },
    { speed: 142, percentile: 48, percentage: 22, speedEv: 252, nature: "Adamant" },
    { speed: 156, percentile: 100, percentage: 47, speedEv: 252, nature: "Jolly" }
  ],
  Overqwil: [
    { speed: 119, percentile: 36, percentage: 11, speedEv: 108, nature: "Adamant" },
    { speed: 137, percentile: 84, percentage: 41, speedEv: 252, nature: "Adamant" },
    { speed: 150, percentile: 100, percentage: 16, speedEv: 252, nature: "Jolly" }
  ],
  "Kyurem-Black": [
    { speed: 147, percentile: 54, percentage: 17, speedEv: 252, nature: "Adamant" },
    { speed: 161, percentile: 100, percentage: 24, speedEv: 252, nature: "Jolly" }
  ],
  "Muk-Alola": [
    { speed: 63, percentile: 21, percentage: 21, speedEv: 0, nature: "Brave" },
    { speed: 70, percentile: 81, percentage: 61, speedEv: 0, nature: "Careful" }
  ],
  Dusclops: [
    { speed: 40, percentile: 69, percentage: 69, speedEv: 0, nature: "Sassy" },
    { speed: 45, percentile: 98, percentage: 29, speedEv: 0, nature: "Bold" }
  ],
  "Dialga-Origin": [
    { speed: 99, percentile: 31, percentage: 31, speedEv: 0, nature: "Quiet" },
    { speed: 110, percentile: 48, percentage: 17, speedEv: 0, nature: "Modest" },
    { speed: 111, percentile: 60, percentage: 12, speedEv: 4, nature: "Modest" }
  ],
  Sylveon: [
    { speed: 72, percentile: 20, percentage: 20, speedEv: 0, nature: "Quiet" },
    { speed: 80, percentile: 62, percentage: 42, speedEv: 0, nature: "Modest" },
    { speed: 112, percentile: 96, percentage: 11, speedEv: 252, nature: "Modest" }
  ],
  "Iron Boulder": [
    { speed: 176, percentile: 33, percentage: 16, speedEv: 252, nature: "Adamant" },
    { speed: 193, percentile: 100, percentage: 44, speedEv: 252, nature: "Jolly" }
  ],
  "Giratina-Origin": [
    { speed: 110, percentile: 21, percentage: 18, speedEv: 0, nature: "Adamant" },
    { speed: 112, percentile: 57, percentage: 27, speedEv: 12, nature: "Adamant" },
    { speed: 126, percentile: 85, percentage: 12, speedEv: 124, nature: "Modest" }
  ],
  Frosmoth: [
    { speed: 85, percentile: 24, percentage: 21, speedEv: 0, nature: "Calm" },
    { speed: 90, percentile: 66, percentage: 25, speedEv: 36, nature: "Modest" },
    { speed: 113, percentile: 95, percentage: 13, speedEv: 220, nature: "Modest" }
  ],
  Clefable: [{ speed: 80, percentile: 81, percentage: 73, speedEv: 0, nature: "Calm" }],
  "Great Tusk": [
    { speed: 107, percentile: 25, percentage: 24, speedEv: 0, nature: "Adamant" },
    { speed: 139, percentile: 65, percentage: 20, speedEv: 252, nature: "Adamant" },
    { speed: 152, percentile: 100, percentage: 30, speedEv: 252, nature: "Jolly" }
  ],
  "Thundurus-Therian": [
    { speed: 153, percentile: 44, percentage: 21, speedEv: 252, nature: "Bashful" },
    { speed: 168, percentile: 100, percentage: 50, speedEv: 252, nature: "Timid" }
  ],
  Metagross: [{ speed: 90, percentile: 67, percentage: 60, speedEv: 0, nature: "Adamant" }],
  "Enamorus-Therian": [
    { speed: 59, percentile: 68, percentage: 68, speedEv: 0, nature: "Quiet" },
    { speed: 66, percentile: 89, percentage: 21, speedEv: 0, nature: "Modest" }
  ],
  Gyarados: [
    { speed: 101, percentile: 13, percentage: 12, speedEv: 0, nature: "Careful" },
    { speed: 133, percentile: 90, percentage: 31, speedEv: 252, nature: "Adamant" }
  ],
  Kingdra: [
    { speed: 133, percentile: 40, percentage: 14, speedEv: 220, nature: "Modest" },
    { speed: 137, percentile: 89, percentage: 48, speedEv: 252, nature: "Modest" },
    { speed: 150, percentile: 100, percentage: 11, speedEv: 252, nature: "Timid" }
  ],
  Klefki: [
    { speed: 85, percentile: 15, percentage: 15, speedEv: 0, nature: "Quiet" },
    { speed: 95, percentile: 84, percentage: 69, speedEv: 0, nature: "Modest" }
  ],
  Snorlax: [
    { speed: 45, percentile: 53, percentage: 53, speedEv: 0, nature: "Relaxed" },
    { speed: 50, percentile: 95, percentage: 42, speedEv: 0, nature: "Adamant" }
  ],
  Palafin: [
    { speed: 120, percentile: 15, percentage: 13, speedEv: 0, nature: "Adamant" },
    { speed: 152, percentile: 55, percentage: 20, speedEv: 252, nature: "Adamant" },
    { speed: 167, percentile: 100, percentage: 42, speedEv: 252, nature: "Jolly" }
  ],
  Skeledirge: [
    { speed: 77, percentile: 20, percentage: 20, speedEv: 0, nature: "Quiet" },
    { speed: 86, percentile: 61, percentage: 41, speedEv: 0, nature: "Modest" },
    { speed: 87, percentile: 72, percentage: 11, speedEv: 4, nature: "Modest" }
  ],
  Meowscarada: [
    { speed: 175, percentile: 38, percentage: 18, speedEv: 252, nature: "Adamant" },
    { speed: 192, percentile: 100, percentage: 60, speedEv: 252, nature: "Jolly" }
  ],
  Pawmot: [
    { speed: 157, percentile: 23, percentage: 12, speedEv: 252, nature: "Adamant" },
    { speed: 172, percentile: 100, percentage: 69, speedEv: 252, nature: "Jolly" }
  ],
  Empoleon: [
    { speed: 80, percentile: 37, percentage: 23, speedEv: 0, nature: "Hardy" },
    { speed: 85, percentile: 74, percentage: 30, speedEv: 36, nature: "Modest" },
    { speed: 112, percentile: 97, percentage: 15, speedEv: 252, nature: "Hardy" }
  ],
  "Necrozma-Dusk-Mane": [
    { speed: 87, percentile: 46, percentage: 46, speedEv: 0, nature: "Brave" },
    { speed: 97, percentile: 62, percentage: 16, speedEv: 0, nature: "Adamant" },
    { speed: 98, percentile: 73, percentage: 11, speedEv: 4, nature: "Adamant" }
  ],
  Baxcalibur: [
    { speed: 107, percentile: 19, percentage: 16, speedEv: 0, nature: "Adamant" },
    { speed: 139, percentile: 64, percentage: 13, speedEv: 252, nature: "Adamant" },
    { speed: 152, percentile: 100, percentage: 34, speedEv: 252, nature: "Jolly" }
  ],
  Articuno: [
    { speed: 105, percentile: 30, percentage: 28, speedEv: 0, nature: "Modest" },
    { speed: 107, percentile: 67, percentage: 24, speedEv: 12, nature: "Modest" },
    { speed: 150, percentile: 100, percentage: 13, speedEv: 252, nature: "Timid" }
  ],
  "Kommo-o": [
    { speed: 128, percentile: 74, percentage: 15, speedEv: 180, nature: "Hardy" },
    { speed: 150, percentile: 100, percentage: 15, speedEv: 252, nature: "Timid" }
  ],
  Rhyperior: [
    { speed: 54, percentile: 60, percentage: 60, speedEv: 0, nature: "Brave" },
    { speed: 60, percentile: 84, percentage: 24, speedEv: 0, nature: "Impish" },
    { speed: 66, percentile: 97, percentage: 11, speedEv: 0, nature: "Jolly" }
  ],
  Rhydon: [
    { speed: 54, percentile: 40, percentage: 40, speedEv: 0, nature: "Sassy" },
    { speed: 60, percentile: 92, percentage: 52, speedEv: 0, nature: "Impish" }
  ],
  Hariyama: [
    { speed: 63, percentile: 58, percentage: 58, speedEv: 0, nature: "Brave" },
    { speed: 70, percentile: 79, percentage: 21, speedEv: 0, nature: "Impish" },
    { speed: 71, percentile: 98, percentage: 19, speedEv: 4, nature: "Adamant" }
  ],
  Arcanine: [
    { speed: 115, percentile: 35, percentage: 30, speedEv: 0, nature: "Adamant" },
    { speed: 161, percentile: 100, percentage: 11, speedEv: 252, nature: "Jolly" }
  ],
  Excadrill: [
    { speed: 140, percentile: 74, percentage: 51, speedEv: 252, nature: "Adamant" },
    { speed: 154, percentile: 100, percentage: 26, speedEv: 252, nature: "Jolly" }
  ],
  Toxapex: [
    { speed: 49, percentile: 26, percentage: 26, speedEv: 0, nature: "Relaxed" },
    { speed: 55, percentile: 91, percentage: 63, speedEv: 0, nature: "Bold" }
  ],
  "Palkia-Origin": [
    { speed: 172, percentile: 63, percentage: 15, speedEv: 252, nature: "Modest" },
    { speed: 189, percentile: 100, percentage: 27, speedEv: 252, nature: "Timid" }
  ],
  Reshiram: [
    { speed: 112, percentile: 30, percentage: 16, speedEv: 12, nature: "Modest" },
    { speed: 156, percentile: 100, percentage: 11, speedEv: 252, nature: "Timid" }
  ],
  Clodsire: [
    { speed: 36, percentile: 45, percentage: 45, speedEv: 0, nature: "Relaxed" },
    { speed: 40, percentile: 89, percentage: 45, speedEv: 0, nature: "Impish" }
  ],
  Registeel: [
    { speed: 70, percentile: 56, percentage: 46, speedEv: 0, nature: "Careful" },
    { speed: 71, percentile: 96, percentage: 40, speedEv: 4, nature: "Careful" }
  ],
  Mewtwo: [
    { speed: 182, percentile: 52, percentage: 27, speedEv: 252, nature: "Modest" },
    { speed: 200, percentile: 100, percentage: 36, speedEv: 252, nature: "Timid" }
  ],
  "Slither Wing": [
    { speed: 101, percentile: 12, percentage: 11, speedEv: 0, nature: "Hardy" },
    { speed: 146, percentile: 100, percentage: 43, speedEv: 252, nature: "Jolly" }
  ],
  Scovillain: [
    { speed: 127, percentile: 37, percentage: 21, speedEv: 164, nature: "Naive" },
    { speed: 139, percentile: 100, percentage: 62, speedEv: 252, nature: "Timid" }
  ],
  Lapras: [
    { speed: 72, percentile: 24, percentage: 24, speedEv: 0, nature: "Sassy" },
    { speed: 80, percentile: 93, percentage: 69, speedEv: 0, nature: "Modest" }
  ],
  Slowking: [
    { speed: 45, percentile: 77, percentage: 77, speedEv: 0, nature: "Quiet" },
    { speed: 50, percentile: 99, percentage: 22, speedEv: 0, nature: "Modest" }
  ],
  Solgaleo: [
    { speed: 117, percentile: 18, percentage: 15, speedEv: 0, nature: "Adamant" },
    { speed: 149, percentile: 74, percentage: 24, speedEv: 252, nature: "Adamant" },
    { speed: 163, percentile: 100, percentage: 20, speedEv: 252, nature: "Jolly" }
  ],
  Azumarill: [
    { speed: 63, percentile: 54, percentage: 54, speedEv: 0, nature: "Relaxed" },
    { speed: 70, percentile: 90, percentage: 36, speedEv: 0, nature: "Adamant" }
  ],
  Hydrapple: [
    { speed: 57, percentile: 46, percentage: 46, speedEv: 0, nature: "Quiet" },
    { speed: 64, percentile: 93, percentage: 46, speedEv: 0, nature: "Bold" }
  ],
  Pachirisu: [
    { speed: 115, percentile: 58, percentage: 53, speedEv: 0, nature: "Bold" },
    { speed: 161, percentile: 100, percentage: 21, speedEv: 252, nature: "Timid" }
  ],
  Altaria: [
    { speed: 100, percentile: 25, percentage: 20, speedEv: 0, nature: "Calm" },
    { speed: 116, percentile: 93, percentage: 49, speedEv: 124, nature: "Calm" }
  ],
  Riolu: [
    { speed: 80, percentile: 44, percentage: 44, speedEv: 0, nature: "Careful" },
    { speed: 81, percentile: 61, percentage: 16, speedEv: 4, nature: "Impish" },
    { speed: 123, percentile: 100, percentage: 26, speedEv: 252, nature: "Jolly" }
  ],
  Breloom: [
    { speed: 90, percentile: 17, percentage: 15, speedEv: 0, nature: "Adamant" },
    { speed: 122, percentile: 47, percentage: 15, speedEv: 252, nature: "Adamant" },
    { speed: 134, percentile: 100, percentage: 52, speedEv: 252, nature: "Jolly" }
  ],
  Hydreigon: [
    { speed: 150, percentile: 55, percentage: 21, speedEv: 252, nature: "Modest" },
    { speed: 165, percentile: 100, percentage: 31, speedEv: 252, nature: "Timid" }
  ],
  Toedscruel: [
    { speed: 120, percentile: 23, percentage: 20, speedEv: 0, nature: "Bold" },
    { speed: 167, percentile: 100, percentage: 51, speedEv: 252, nature: "Timid" }
  ],
  Glastrier: [
    { speed: 45, percentile: 58, percentage: 58, speedEv: 0, nature: "Relaxed" },
    { speed: 50, percentile: 78, percentage: 20, speedEv: 0, nature: "Adamant" },
    { speed: 51, percentile: 95, percentage: 17, speedEv: 4, nature: "Adamant" }
  ],
  Gliscor: [
    { speed: 115, percentile: 30, percentage: 28, speedEv: 0, nature: "Adamant" },
    { speed: 124, percentile: 48, percentage: 13, speedEv: 72, nature: "Impish" },
    { speed: 161, percentile: 100, percentage: 25, speedEv: 252, nature: "Jolly" }
  ],
  Ludicolo: [
    { speed: 120, percentile: 49, percentage: 11, speedEv: 236, nature: "Modest" },
    { speed: 122, percentile: 79, percentage: 29, speedEv: 252, nature: "Adamant" },
    { speed: 134, percentile: 100, percentage: 21, speedEv: 252, nature: "Timid" }
  ],
  Swampert: [{ speed: 80, percentile: 82, percentage: 73, speedEv: 0, nature: "Impish" }],
  Zapdos: [
    { speed: 120, percentile: 21, percentage: 18, speedEv: 0, nature: "Modest" },
    { speed: 152, percentile: 70, percentage: 16, speedEv: 152, nature: "Timid" },
    { speed: 167, percentile: 100, percentage: 29, speedEv: 252, nature: "Timid" }
  ],
  "Raichu-Alola": [
    { speed: 162, percentile: 31, percentage: 15, speedEv: 252, nature: "Modest" },
    { speed: 178, percentile: 100, percentage: 68, speedEv: 252, nature: "Timid" }
  ],
  Salamence: [
    { speed: 120, percentile: 14, percentage: 12, speedEv: 0, nature: "Adamant" },
    { speed: 152, percentile: 50, percentage: 14, speedEv: 252, nature: "Adamant" },
    { speed: 167, percentile: 100, percentage: 47, speedEv: 252, nature: "Hasty" }
  ],
  "Rotom-Wash": [
    { speed: 106, percentile: 27, percentage: 25, speedEv: 0, nature: "Modest" },
    { speed: 107, percentile: 53, percentage: 26, speedEv: 4, nature: "Modest" },
    { speed: 151, percentile: 100, percentage: 11, speedEv: 252, nature: "Timid" }
  ],
  Ninetales: [
    { speed: 152, percentile: 55, percentage: 30, speedEv: 252, nature: "Modest" },
    { speed: 165, percentile: 72, percentage: 15, speedEv: 236, nature: "Timid" },
    { speed: 167, percentile: 100, percentage: 28, speedEv: 252, nature: "Timid" }
  ],
  Cobalion: [
    { speed: 129, percentile: 28, percentage: 20, speedEv: 4, nature: "Impish" },
    { speed: 157, percentile: 84, percentage: 31, speedEv: 228, nature: "Impish" }
  ],
  Meowstic: [{ speed: 124, percentile: 57, percentage: 57, speedEv: 0, nature: "Bold" }],
  "Articuno-Galar": [
    { speed: 115, percentile: 27, percentage: 18, speedEv: 0, nature: "Modest" },
    { speed: 147, percentile: 67, percentage: 20, speedEv: 252, nature: "Bold" },
    { speed: 161, percentile: 100, percentage: 31, speedEv: 252, nature: "Timid" }
  ],
  Stonjourner: [
    { speed: 90, percentile: 31, percentage: 22, speedEv: 0, nature: "Bold" },
    { speed: 122, percentile: 95, percentage: 52, speedEv: 252, nature: "Impish" }
  ],
  Enamorus: [
    { speed: 158, percentile: 41, percentage: 14, speedEv: 252, nature: "Adamant" },
    { speed: 173, percentile: 100, percentage: 45, speedEv: 252, nature: "Hasty" }
  ],
  Orthworm: [
    { speed: 76, percentile: 11, percentage: 11, speedEv: 0, nature: "Relaxed" },
    { speed: 85, percentile: 90, percentage: 79, speedEv: 0, nature: "Bold" }
  ],
  Espathra: [
    { speed: 157, percentile: 46, percentage: 31, speedEv: 252, nature: "Modest" },
    { speed: 172, percentile: 100, percentage: 51, speedEv: 252, nature: "Timid" }
  ],
  Yanmega: [
    { speed: 139, percentile: 26, percentage: 16, speedEv: 188, nature: "Modest" },
    { speed: 147, percentile: 54, percentage: 22, speedEv: 252, nature: "Modest" },
    { speed: 161, percentile: 100, percentage: 42, speedEv: 252, nature: "Timid" }
  ],
  Arboliva: [
    { speed: 53, percentile: 12, percentage: 12, speedEv: 0, nature: "Sassy" },
    { speed: 59, percentile: 88, percentage: 75, speedEv: 0, nature: "Hardy" },
    { speed: 60, percentile: 99, percentage: 12, speedEv: 4, nature: "Hardy" }
  ],
  Conkeldurr: [
    { speed: 58, percentile: 53, percentage: 53, speedEv: 0, nature: "Brave" },
    { speed: 65, percentile: 96, percentage: 43, speedEv: 0, nature: "Careful" }
  ],
  Exeggutor: [
    { speed: 75, percentile: 29, percentage: 20, speedEv: 0, nature: "Calm" },
    { speed: 107, percentile: 62, percentage: 20, speedEv: 252, nature: "Modest" },
    { speed: 117, percentile: 100, percentage: 33, speedEv: 252, nature: "Timid" }
  ],
  Pikachu: [{ speed: 156, percentile: 100, percentage: 79, speedEv: 252, nature: "Jolly" }],
  Abomasnow: [
    { speed: 72, percentile: 35, percentage: 35, speedEv: 0, nature: "Quiet" },
    { speed: 80, percentile: 84, percentage: 48, speedEv: 0, nature: "Calm" }
  ],
  Serperior: [{ speed: 181, percentile: 100, percentage: 55, speedEv: 252, nature: "Timid" }],
  Fezandipiti: [
    { speed: 119, percentile: 26, percentage: 23, speedEv: 0, nature: "Modest" },
    { speed: 151, percentile: 75, percentage: 15, speedEv: 252, nature: "Modest" },
    { speed: 166, percentile: 100, percentage: 19, speedEv: 252, nature: "Jolly" }
  ],
  Malamar: [
    { speed: 83, percentile: 28, percentage: 28, speedEv: 0, nature: "Relaxed" },
    { speed: 93, percentile: 71, percentage: 40, speedEv: 0, nature: "Impish" }
  ],
  Gengar: [
    { speed: 162, percentile: 37, percentage: 12, speedEv: 252, nature: "Modest" },
    { speed: 178, percentile: 100, percentage: 62, speedEv: 252, nature: "Timid" }
  ],
  Munkidori: [
    { speed: 129, percentile: 35, percentage: 26, speedEv: 20, nature: "Modest" },
    { speed: 173, percentile: 100, percentage: 42, speedEv: 252, nature: "Timid" }
  ],
  Gardevoir: [
    { speed: 100, percentile: 21, percentage: 16, speedEv: 0, nature: "Modest" },
    { speed: 132, percentile: 70, percentage: 19, speedEv: 252, nature: "Modest" },
    { speed: 145, percentile: 100, percentage: 26, speedEv: 252, nature: "Hasty" }
  ],
  Greninja: [
    { speed: 174, percentile: 30, percentage: 17, speedEv: 252, nature: "Calm" },
    { speed: 191, percentile: 100, percentage: 70, speedEv: 252, nature: "Jolly" }
  ],
  Kleavor: [
    { speed: 124, percentile: 31, percentage: 23, speedEv: 148, nature: "Adamant" },
    { speed: 137, percentile: 57, percentage: 18, speedEv: 252, nature: "Serious" },
    { speed: 150, percentile: 100, percentage: 43, speedEv: 252, nature: "Jolly" }
  ],
  Blaziken: [
    { speed: 132, percentile: 70, percentage: 46, speedEv: 252, nature: "Adamant" },
    { speed: 145, percentile: 100, percentage: 29, speedEv: 252, nature: "Jolly" }
  ],
  Dialga: [
    { speed: 99, percentile: 23, percentage: 23, speedEv: 0, nature: "Quiet" },
    { speed: 110, percentile: 74, percentage: 51, speedEv: 0, nature: "Bold" }
  ],
  Salazzle: [{ speed: 185, percentile: 100, percentage: 84, speedEv: 252, nature: "Hasty" }],
  Giratina: [
    { speed: 99, percentile: 15, percentage: 15, speedEv: 0, nature: "Brave" },
    { speed: 110, percentile: 42, percentage: 27, speedEv: 0, nature: "Modest" },
    { speed: 111, percentile: 55, percentage: 13, speedEv: 4, nature: "Modest" }
  ],
  "Slowking-Galar": [
    { speed: 45, percentile: 62, percentage: 62, speedEv: 0, nature: "Sassy" },
    { speed: 50, percentile: 99, percentage: 37, speedEv: 0, nature: "Hardy" }
  ],
  Barraskewda: [
    { speed: 188, percentile: 67, percentage: 61, speedEv: 252, nature: "Adamant" },
    { speed: 206, percentile: 100, percentage: 31, speedEv: 252, nature: "Jolly" }
  ],
  Latias: [
    { speed: 130, percentile: 11, percentage: 11, speedEv: 0, nature: "Bold" },
    { speed: 162, percentile: 52, percentage: 15, speedEv: 252, nature: "Calm" },
    { speed: 178, percentile: 100, percentage: 34, speedEv: 252, nature: "Timid" }
  ],
  Mamoswine: [
    { speed: 100, percentile: 35, percentage: 30, speedEv: 0, nature: "Hardy" },
    { speed: 132, percentile: 75, percentage: 12, speedEv: 252, nature: "Adamant" },
    { speed: 145, percentile: 100, percentage: 23, speedEv: 252, nature: "Jolly" }
  ],
  Zekrom: [
    { speed: 142, percentile: 76, percentage: 28, speedEv: 252, nature: "Adamant" },
    { speed: 156, percentile: 100, percentage: 12, speedEv: 252, nature: "Jolly" }
  ],
  Scrafty: [
    { speed: 70, percentile: 30, percentage: 30, speedEv: 0, nature: "Relaxed" },
    { speed: 78, percentile: 77, percentage: 46, speedEv: 0, nature: "Impish" }
  ],
  Noivern: [
    { speed: 175, percentile: 34, percentage: 29, speedEv: 252, nature: "Modest" },
    { speed: 192, percentile: 100, percentage: 57, speedEv: 252, nature: "Timid" }
  ],
  Terrakion: [
    { speed: 160, percentile: 32, percentage: 11, speedEv: 252, nature: "Adamant" },
    { speed: 176, percentile: 100, percentage: 53, speedEv: 252, nature: "Jolly" }
  ],
  Vikavolt: [
    { speed: 56, percentile: 65, percentage: 65, speedEv: 0, nature: "Quiet" },
    { speed: 63, percentile: 85, percentage: 20, speedEv: 0, nature: "Modest" }
  ],
  Kilowattrel: [
    { speed: 177, percentile: 17, percentage: 12, speedEv: 252, nature: "Modest" },
    { speed: 194, percentile: 100, percentage: 78, speedEv: 252, nature: "Timid" }
  ],
  Pincurchin: [
    { speed: 31, percentile: 62, percentage: 62, speedEv: 0, nature: "Relaxed" },
    { speed: 35, percentile: 99, percentage: 37, speedEv: 0, nature: "Careful" }
  ],
  Slaking: [
    { speed: 120, percentile: 45, percentage: 44, speedEv: 0, nature: "Adamant" },
    { speed: 152, percentile: 77, percentage: 12, speedEv: 252, nature: "Adamant" },
    { speed: 167, percentile: 100, percentage: 22, speedEv: 252, nature: "Jolly" }
  ],
  Jolteon: [{ speed: 200, percentile: 100, percentage: 81, speedEv: 252, nature: "Hasty" }],
  Volbeat: [
    { speed: 105, percentile: 58, percentage: 57, speedEv: 0, nature: "Careful" },
    { speed: 106, percentile: 82, percentage: 24, speedEv: 4, nature: "Impish" },
    { speed: 150, percentile: 100, percentage: 11, speedEv: 252, nature: "Timid" }
  ],
  Greedent: [{ speed: 36, percentile: 97, percentage: 97, speedEv: 0, nature: "Brave" }],
  Moltres: [
    { speed: 111, percentile: 30, percentage: 17, speedEv: 4, nature: "Bold" },
    { speed: 114, percentile: 59, percentage: 16, speedEv: 28, nature: "Modest" }
  ],
  "Decidueye-Hisui": [
    { speed: 72, percentile: 18, percentage: 18, speedEv: 0, nature: "Brave" },
    { speed: 80, percentile: 58, percentage: 40, speedEv: 0, nature: "Adamant" }
  ],
  Mandibuzz: [{ speed: 100, percentile: 67, percentage: 65, speedEv: 0, nature: "Impish" }],
  Spectrier: [
    { speed: 174, percentile: 29, percentage: 21, speedEv: 68, nature: "Timid" },
    { speed: 182, percentile: 44, percentage: 11, speedEv: 252, nature: "Hardy" },
    { speed: 200, percentile: 100, percentage: 49, speedEv: 252, nature: "Timid" }
  ],
  Zamazenta: [
    { speed: 158, percentile: 11, percentage: 11, speedEv: 0, nature: "Impish" },
    { speed: 171, percentile: 38, percentage: 18, speedEv: 100, nature: "Impish" },
    { speed: 182, percentile: 63, percentage: 21, speedEv: 188, nature: "Impish" }
  ],
  Toxicroak: [
    { speed: 113, percentile: 23, percentage: 14, speedEv: 60, nature: "Adamant" },
    { speed: 137, percentile: 69, percentage: 27, speedEv: 156, nature: "Hasty" },
    { speed: 150, percentile: 100, percentage: 29, speedEv: 252, nature: "Jolly" }
  ],
  Blastoise: [
    { speed: 88, percentile: 27, percentage: 27, speedEv: 0, nature: "Sassy" },
    { speed: 98, percentile: 68, percentage: 39, speedEv: 0, nature: "Modest" },
    { speed: 130, percentile: 96, percentage: 14, speedEv: 252, nature: "Hardy" }
  ],
  Palkia: [
    { speed: 108, percentile: 22, percentage: 22, speedEv: 0, nature: "Quiet" },
    { speed: 120, percentile: 41, percentage: 19, speedEv: 0, nature: "Modest" }
  ],
  Drifblim: [
    { speed: 100, percentile: 31, percentage: 23, speedEv: 0, nature: "Adamant" },
    { speed: 132, percentile: 66, percentage: 16, speedEv: 252, nature: "Modest" },
    { speed: 145, percentile: 100, percentage: 34, speedEv: 252, nature: "Jolly" }
  ],
  Bellibolt: [
    { speed: 58, percentile: 43, percentage: 43, speedEv: 0, nature: "Quiet" },
    { speed: 65, percentile: 92, percentage: 46, speedEv: 0, nature: "Calm" }
  ],
  Quaquaval: [
    { speed: 137, percentile: 85, percentage: 69, speedEv: 252, nature: "Adamant" },
    { speed: 150, percentile: 100, percentage: 15, speedEv: 252, nature: "Jolly" }
  ],
  Medicham: [
    { speed: 112, percentile: 41, percentage: 18, speedEv: 92, nature: "Adamant" },
    { speed: 132, percentile: 73, percentage: 23, speedEv: 252, nature: "Hardy" },
    { speed: 145, percentile: 100, percentage: 26, speedEv: 252, nature: "Jolly" }
  ],
  Shiftry: [
    { speed: 132, percentile: 46, percentage: 39, speedEv: 252, nature: "Adamant" },
    { speed: 139, percentile: 57, percentage: 11, speedEv: 212, nature: "Jolly" },
    { speed: 145, percentile: 100, percentage: 38, speedEv: 252, nature: "Jolly" }
  ],
  Cinderace: [
    { speed: 139, percentile: 14, percentage: 13, speedEv: 0, nature: "Hardy" },
    { speed: 188, percentile: 100, percentage: 61, speedEv: 252, nature: "Jolly" }
  ],
  Electivire: [
    { speed: 115, percentile: 34, percentage: 34, speedEv: 0, nature: "Impish" },
    { speed: 147, percentile: 77, percentage: 17, speedEv: 252, nature: "Adamant" },
    { speed: 161, percentile: 100, percentage: 20, speedEv: 252, nature: "Timid" }
  ],
  "Samurott-Hisui": [
    { speed: 137, percentile: 72, percentage: 30, speedEv: 252, nature: "Adamant" },
    { speed: 150, percentile: 100, percentage: 26, speedEv: 252, nature: "Jolly" }
  ],
  Hippowdon: [
    { speed: 60, percentile: 17, percentage: 17, speedEv: 0, nature: "Sassy" },
    { speed: 67, percentile: 81, percentage: 64, speedEv: 0, nature: "Impish" },
    { speed: 68, percentile: 100, percentage: 19, speedEv: 4, nature: "Impish" }
  ],
  Cetitan: [
    { speed: 93, percentile: 31, percentage: 18, speedEv: 0, nature: "Adamant" },
    { speed: 94, percentile: 51, percentage: 20, speedEv: 4, nature: "Adamant" },
    { speed: 137, percentile: 100, percentage: 15, speedEv: 252, nature: "Jolly" }
  ],
  Torterra: [
    { speed: 76, percentile: 47, percentage: 34, speedEv: 0, nature: "Adamant" },
    { speed: 77, percentile: 59, percentage: 12, speedEv: 4, nature: "Adamant" },
    { speed: 82, percentile: 74, percentage: 15, speedEv: 44, nature: "Adamant" }
  ],
  Wigglytuff: [
    { speed: 58, percentile: 82, percentage: 82, speedEv: 0, nature: "Quiet" },
    { speed: 65, percentile: 99, percentage: 17, speedEv: 0, nature: "Calm" }
  ],
  Lurantis: [
    { speed: 58, percentile: 62, percentage: 62, speedEv: 0, nature: "Brave" },
    { speed: 65, percentile: 94, percentage: 32, speedEv: 0, nature: "Careful" }
  ],
  Golurk: [
    { speed: 67, percentile: 29, percentage: 29, speedEv: 0, nature: "Sassy" },
    { speed: 75, percentile: 77, percentage: 47, speedEv: 0, nature: "Adamant" },
    { speed: 76, percentile: 87, percentage: 11, speedEv: 4, nature: "Adamant" }
  ],
  Slowbro: [
    { speed: 45, percentile: 62, percentage: 62, speedEv: 0, nature: "Relaxed" },
    { speed: 50, percentile: 97, percentage: 34, speedEv: 0, nature: "Calm" }
  ],
  Chesnaught: [
    { speed: 75, percentile: 12, percentage: 12, speedEv: 0, nature: "Sassy" },
    { speed: 84, percentile: 48, percentage: 35, speedEv: 0, nature: "Careful" },
    { speed: 94, percentile: 94, percentage: 25, speedEv: 80, nature: "Hardy" }
  ],
  Glaceon: [
    { speed: 85, percentile: 37, percentage: 28, speedEv: 0, nature: "Modest" },
    { speed: 109, percentile: 79, percentage: 21, speedEv: 188, nature: "Modest" },
    { speed: 117, percentile: 98, percentage: 14, speedEv: 252, nature: "Hardy" }
  ],
  Illumise: [
    { speed: 105, percentile: 59, percentage: 54, speedEv: 0, nature: "Calm" },
    { speed: 106, percentile: 76, percentage: 17, speedEv: 4, nature: "Calm" },
    { speed: 150, percentile: 100, percentage: 18, speedEv: 252, nature: "Timid" }
  ],
  "Rotom-Heat": [
    { speed: 106, percentile: 24, percentage: 24, speedEv: 0, nature: "Calm" },
    { speed: 125, percentile: 61, percentage: 12, speedEv: 148, nature: "Modest" },
    { speed: 151, percentile: 100, percentage: 26, speedEv: 252, nature: "Timid" }
  ],
  Vivillon: [
    { speed: 141, percentile: 23, percentage: 16, speedEv: 252, nature: "Modest" },
    { speed: 155, percentile: 100, percentage: 74, speedEv: 252, nature: "Timid" }
  ],
  Houndstone: [
    { speed: 88, percentile: 18, percentage: 15, speedEv: 0, nature: "Careful" },
    { speed: 120, percentile: 55, percentage: 24, speedEv: 252, nature: "Adamant" },
    { speed: 132, percentile: 100, percentage: 44, speedEv: 252, nature: "Jolly" }
  ],
  Gothorita: [
    { speed: 67, percentile: 18, percentage: 18, speedEv: 0, nature: "Sassy" },
    { speed: 75, percentile: 95, percentage: 76, speedEv: 0, nature: "Bold" }
  ],
  Regirock: [
    { speed: 70, percentile: 76, percentage: 67, speedEv: 0, nature: "Hardy" },
    { speed: 71, percentile: 93, percentage: 17, speedEv: 4, nature: "Serious" }
  ],
  Charjabug: [
    { speed: 50, percentile: 22, percentage: 22, speedEv: 0, nature: "Sassy" },
    { speed: 56, percentile: 88, percentage: 66, speedEv: 0, nature: "Impish" },
    { speed: 58, percentile: 99, percentage: 11, speedEv: 12, nature: "Bold" }
  ],
  Toxtricity: [
    { speed: 95, percentile: 27, percentage: 22, speedEv: 0, nature: "Modest" },
    { speed: 127, percentile: 68, percentage: 13, speedEv: 252, nature: "Modest" },
    { speed: 139, percentile: 100, percentage: 23, speedEv: 252, nature: "Timid" }
  ],
  Ambipom: [
    { speed: 167, percentile: 35, percentage: 20, speedEv: 252, nature: "Adamant" },
    { speed: 183, percentile: 100, percentage: 65, speedEv: 252, nature: "Jolly" }
  ],
  Staraptor: [
    { speed: 152, percentile: 40, percentage: 13, speedEv: 252, nature: "Hardy" },
    { speed: 167, percentile: 100, percentage: 60, speedEv: 252, nature: "Jolly" }
  ],
  Lycanroc: [{ speed: 164, percentile: 92, percentage: 89, speedEv: 252, nature: "Adamant" }],
  Dugtrio: [{ speed: 189, percentile: 100, percentage: 78, speedEv: 252, nature: "Jolly" }],
  Lilligant: [
    { speed: 110, percentile: 11, percentage: 11, speedEv: 0, nature: "Bold" },
    { speed: 142, percentile: 74, percentage: 40, speedEv: 252, nature: "Modest" },
    { speed: 156, percentile: 100, percentage: 26, speedEv: 252, nature: "Timid" }
  ],
  Sawsbuck: [
    { speed: 147, percentile: 63, percentage: 59, speedEv: 252, nature: "Adamant" },
    { speed: 161, percentile: 100, percentage: 36, speedEv: 252, nature: "Jolly" }
  ],
  Brambleghast: [
    { speed: 142, percentile: 75, percentage: 59, speedEv: 252, nature: "Adamant" },
    { speed: 156, percentile: 100, percentage: 25, speedEv: 252, nature: "Jolly" }
  ],
  "Basculegion-F": [
    { speed: 98, percentile: 18, percentage: 17, speedEv: 0, nature: "Modest" },
    { speed: 130, percentile: 96, percentage: 57, speedEv: 252, nature: "Modest" }
  ],
  Blissey: [{ speed: 75, percentile: 85, percentage: 75, speedEv: 0, nature: "Modest" }],
  Krookodile: [
    { speed: 144, percentile: 45, percentage: 18, speedEv: 252, nature: "Hardy" },
    { speed: 158, percentile: 100, percentage: 51, speedEv: 252, nature: "Jolly" }
  ],
  Coalossal: [
    { speed: 45, percentile: 13, percentage: 13, speedEv: 0, nature: "Sassy" },
    { speed: 50, percentile: 47, percentage: 34, speedEv: 0, nature: "Modest" },
    { speed: 56, percentile: 72, percentage: 25, speedEv: 44, nature: "Modest" }
  ],
  Ribombee: [
    { speed: 176, percentile: 28, percentage: 19, speedEv: 252, nature: "Modest" },
    { speed: 193, percentile: 100, percentage: 69, speedEv: 252, nature: "Timid" }
  ],
  Weavile: [
    { speed: 177, percentile: 35, percentage: 25, speedEv: 252, nature: "Adamant" },
    { speed: 194, percentile: 100, percentage: 62, speedEv: 252, nature: "Jolly" }
  ],
  Regice: [
    { speed: 63, percentile: 21, percentage: 21, speedEv: 0, nature: "Relaxed" },
    { speed: 70, percentile: 87, percentage: 66, speedEv: 0, nature: "Modest" }
  ],
  Lucario: [
    { speed: 142, percentile: 44, percentage: 22, speedEv: 252, nature: "Adamant" },
    { speed: 156, percentile: 100, percentage: 53, speedEv: 252, nature: "Jolly" }
  ],
  Infernape: [
    { speed: 160, percentile: 24, percentage: 11, speedEv: 252, nature: "Adamant" },
    { speed: 176, percentile: 100, percentage: 70, speedEv: 252, nature: "Jolly" }
  ],
  Goodra: [
    { speed: 90, percentile: 17, percentage: 17, speedEv: 0, nature: "Quiet" },
    { speed: 100, percentile: 91, percentage: 74, speedEv: 0, nature: "Modest" }
  ],
  "Iron Thorns": [
    { speed: 92, percentile: 40, percentage: 33, speedEv: 0, nature: "Adamant" },
    { speed: 93, percentile: 58, percentage: 18, speedEv: 4, nature: "Adamant" },
    { speed: 124, percentile: 95, percentage: 13, speedEv: 252, nature: "Adamant" }
  ],
  Sceptile: [
    { speed: 167, percentile: 27, percentage: 13, speedEv: 216, nature: "Modest" },
    { speed: 172, percentile: 42, percentage: 14, speedEv: 252, nature: "Modest" },
    { speed: 189, percentile: 100, percentage: 55, speedEv: 252, nature: "Timid" }
  ],
  "Porygon-Z": [
    { speed: 99, percentile: 14, percentage: 14, speedEv: 0, nature: "Sassy" },
    { speed: 142, percentile: 51, percentage: 20, speedEv: 252, nature: "Modest" },
    { speed: 156, percentile: 100, percentage: 42, speedEv: 252, nature: "Timid" }
  ],
  Cloyster: [
    { speed: 81, percentile: 15, percentage: 15, speedEv: 0, nature: "Brave" },
    { speed: 122, percentile: 84, percentage: 35, speedEv: 252, nature: "Hardy" },
    { speed: 134, percentile: 100, percentage: 15, speedEv: 252, nature: "Jolly" }
  ],
  Reuniclus: [
    { speed: 45, percentile: 46, percentage: 46, speedEv: 0, nature: "Quiet" },
    { speed: 50, percentile: 94, percentage: 48, speedEv: 0, nature: "Bold" }
  ],
  Tropius: [
    { speed: 71, percentile: 23, percentage: 19, speedEv: 0, nature: "Calm" },
    { speed: 90, percentile: 45, percentage: 22, speedEv: 148, nature: "Bold" },
    { speed: 113, percentile: 100, percentage: 46, speedEv: 252, nature: "Timid" }
  ],
  Dusknoir: [
    { speed: 58, percentile: 80, percentage: 80, speedEv: 0, nature: "Sassy" },
    { speed: 65, percentile: 94, percentage: 14, speedEv: 0, nature: "Impish" }
  ],
  Haxorus: [
    { speed: 117, percentile: 22, percentage: 20, speedEv: 0, nature: "Hardy" },
    { speed: 149, percentile: 69, percentage: 34, speedEv: 252, nature: "Adamant" },
    { speed: 163, percentile: 100, percentage: 30, speedEv: 252, nature: "Jolly" }
  ],
  "Exeggutor-Alola": [
    { speed: 58, percentile: 52, percentage: 52, speedEv: 0, nature: "Quiet" },
    { speed: 65, percentile: 96, percentage: 43, speedEv: 0, nature: "Bold" }
  ],
  Cramorant: [
    { speed: 137, percentile: 88, percentage: 65, speedEv: 252, nature: "Mild" },
    { speed: 150, percentile: 100, percentage: 12, speedEv: 252, nature: "Timid" }
  ],
  "Electrode-Hisui": [{ speed: 222, percentile: 100, percentage: 82, speedEv: 252, nature: "Hasty" }],
  Carbink: [
    { speed: 63, percentile: 49, percentage: 49, speedEv: 0, nature: "Relaxed" },
    { speed: 70, percentile: 95, percentage: 46, speedEv: 0, nature: "Calm" }
  ],
  Florges: [
    { speed: 85, percentile: 15, percentage: 15, speedEv: 0, nature: "Relaxed" },
    { speed: 95, percentile: 68, percentage: 53, speedEv: 0, nature: "Calm" },
    { speed: 96, percentile: 80, percentage: 12, speedEv: 4, nature: "Bold" }
  ],
  Inteleon: [
    { speed: 172, percentile: 33, percentage: 15, speedEv: 252, nature: "Mild" },
    { speed: 189, percentile: 100, percentage: 66, speedEv: 252, nature: "Hasty" }
  ],
  Grafaiai: [
    { speed: 130, percentile: 41, percentage: 38, speedEv: 0, nature: "Bold" },
    { speed: 178, percentile: 100, percentage: 38, speedEv: 252, nature: "Jolly" }
  ],
  Raikou: [
    { speed: 135, percentile: 18, percentage: 18, speedEv: 0, nature: "Bold" },
    { speed: 179, percentile: 53, percentage: 13, speedEv: 220, nature: "Timid" },
    { speed: 183, percentile: 100, percentage: 34, speedEv: 252, nature: "Timid" }
  ],
  Cyclizar: [
    { speed: 168, percentile: 23, percentage: 16, speedEv: 92, nature: "Jolly" },
    { speed: 173, percentile: 35, percentage: 12, speedEv: 252, nature: "Hardy" },
    { speed: 190, percentile: 100, percentage: 61, speedEv: 252, nature: "Timid" }
  ],
  Hawlucha: [
    { speed: 170, percentile: 85, percentage: 65, speedEv: 252, nature: "Adamant" },
    { speed: 187, percentile: 100, percentage: 15, speedEv: 252, nature: "Jolly" }
  ],
  Leafeon: [
    { speed: 115, percentile: 14, percentage: 13, speedEv: 0, nature: "Adamant" },
    { speed: 147, percentile: 87, percentage: 61, speedEv: 252, nature: "Adamant" }
  ],
  Uxie: [{ speed: 115, percentile: 91, percentage: 86, speedEv: 0, nature: "Calm" }],
  Galvantula: [
    { speed: 129, percentile: 16, percentage: 13, speedEv: 4, nature: "Modest" },
    { speed: 160, percentile: 40, percentage: 20, speedEv: 252, nature: "Bold" },
    { speed: 176, percentile: 100, percentage: 59, speedEv: 252, nature: "Timid" }
  ],
  Alomomola: [
    { speed: 76, percentile: 24, percentage: 24, speedEv: 0, nature: "Sassy" },
    { speed: 85, percentile: 84, percentage: 60, speedEv: 0, nature: "Modest" }
  ],
  Beartic: [
    { speed: 102, percentile: 48, percentage: 25, speedEv: 252, nature: "Adamant" },
    { speed: 112, percentile: 100, percentage: 51, speedEv: 252, nature: "Jolly" }
  ],
  "Avalugg-Hisui": [
    { speed: 52, percentile: 39, percentage: 39, speedEv: 0, nature: "Brave" },
    { speed: 58, percentile: 98, percentage: 59, speedEv: 0, nature: "Naughty" }
  ],
  Bisharp: [
    { speed: 81, percentile: 20, percentage: 20, speedEv: 0, nature: "Sassy" },
    { speed: 90, percentile: 78, percentage: 58, speedEv: 0, nature: "Hardy" }
  ],
  Spiritomb: [
    { speed: 49, percentile: 60, percentage: 60, speedEv: 0, nature: "Relaxed" },
    { speed: 55, percentile: 94, percentage: 34, speedEv: 0, nature: "Hardy" }
  ],
  Dudunsparce: [
    { speed: 67, percentile: 21, percentage: 21, speedEv: 0, nature: "Brave" },
    { speed: 75, percentile: 65, percentage: 44, speedEv: 0, nature: "Impish" },
    { speed: 117, percentile: 100, percentage: 19, speedEv: 252, nature: "Timid" }
  ],
  "Slowbro-Galar": [
    { speed: 45, percentile: 53, percentage: 53, speedEv: 0, nature: "Relaxed" },
    { speed: 50, percentile: 91, percentage: 39, speedEv: 0, nature: "Modest" }
  ],
  Wyrdeer: [
    { speed: 76, percentile: 59, percentage: 59, speedEv: 0, nature: "Quiet" },
    { speed: 85, percentile: 88, percentage: 29, speedEv: 0, nature: "Careful" }
  ],
  Dodrio: [{ speed: 178, percentile: 100, percentage: 94, speedEv: 252, nature: "Jolly" }],
  Clawitzer: [
    { speed: 71, percentile: 20, percentage: 20, speedEv: 0, nature: "Quiet" },
    { speed: 79, percentile: 65, percentage: 45, speedEv: 0, nature: "Hardy" },
    { speed: 80, percentile: 78, percentage: 13, speedEv: 4, nature: "Modest" }
  ],
  Crabominable: [
    { speed: 56, percentile: 64, percentage: 64, speedEv: 0, nature: "Brave" },
    { speed: 63, percentile: 97, percentage: 34, speedEv: 0, nature: "Adamant" }
  ],
  Espeon: [
    { speed: 130, percentile: 34, percentage: 30, speedEv: 0, nature: "Hardy" },
    { speed: 162, percentile: 57, percentage: 17, speedEv: 252, nature: "Modest" },
    { speed: 178, percentile: 100, percentage: 43, speedEv: 252, nature: "Timid" }
  ],
  Duraludon: [
    { speed: 94, percentile: 14, percentage: 14, speedEv: 0, nature: "Relaxed" },
    { speed: 105, percentile: 81, percentage: 67, speedEv: 0, nature: "Modest" }
  ],
  "Oricorio-Pom-Pom": [{ speed: 145, percentile: 93, percentage: 67, speedEv: 252, nature: "Modest" }],
  Gloom: [
    { speed: 54, percentile: 21, percentage: 21, speedEv: 0, nature: "Sassy" },
    { speed: 60, percentile: 98, percentage: 77, speedEv: 0, nature: "Calm" }
  ],
  "Golem-Alola": [
    { speed: 58, percentile: 26, percentage: 26, speedEv: 0, nature: "Brave" },
    { speed: 65, percentile: 79, percentage: 53, speedEv: 0, nature: "Adamant" },
    { speed: 75, percentile: 92, percentage: 13, speedEv: 80, nature: "Adamant" }
  ],
  Cinccino: [
    { speed: 167, percentile: 22, percentage: 17, speedEv: 252, nature: "Adamant" },
    { speed: 183, percentile: 100, percentage: 73, speedEv: 252, nature: "Jolly" }
  ],
  Rampardos: [
    { speed: 70, percentile: 39, percentage: 39, speedEv: 0, nature: "Brave" },
    { speed: 78, percentile: 60, percentage: 21, speedEv: 0, nature: "Bold" },
    { speed: 110, percentile: 85, percentage: 25, speedEv: 252, nature: "Adamant" }
  ],
  Typhlosion: [
    { speed: 132, percentile: 39, percentage: 36, speedEv: 0, nature: "Timid" },
    { speed: 167, percentile: 100, percentage: 55, speedEv: 252, nature: "Timid" }
  ],
  Vileplume: [
    { speed: 70, percentile: 54, percentage: 50, speedEv: 0, nature: "Hardy" },
    { speed: 112, percentile: 100, percentage: 27, speedEv: 252, nature: "Timid" }
  ],
  Probopass: [
    { speed: 54, percentile: 42, percentage: 42, speedEv: 0, nature: "Relaxed" },
    { speed: 60, percentile: 99, percentage: 57, speedEv: 0, nature: "Modest" }
  ],
  "Braviary-Hisui": [
    { speed: 85, percentile: 49, percentage: 41, speedEv: 0, nature: "Modest" },
    { speed: 117, percentile: 96, percentage: 21, speedEv: 252, nature: "Modest" }
  ],
  Magmortar: [
    { speed: 103, percentile: 38, percentage: 36, speedEv: 0, nature: "Careful" },
    { speed: 104, percentile: 64, percentage: 26, speedEv: 4, nature: "Modest" },
    { speed: 148, percentile: 100, percentage: 26, speedEv: 252, nature: "Timid" }
  ],
  Hitmonlee: [
    { speed: 123, percentile: 71, percentage: 62, speedEv: 124, nature: "Careful" },
    { speed: 139, percentile: 98, percentage: 23, speedEv: 252, nature: "Adamant" }
  ],
  "Tornadus-Therian": [{ speed: 190, percentile: 100, percentage: 63, speedEv: 252, nature: "Timid" }],
  Perrserker: [
    { speed: 63, percentile: 14, percentage: 14, speedEv: 0, nature: "Brave" },
    { speed: 70, percentile: 50, percentage: 36, speedEv: 0, nature: "Careful" },
    { speed: 102, percentile: 89, percentage: 33, speedEv: 252, nature: "Adamant" }
  ],
  Delphox: [
    { speed: 111, percentile: 24, percentage: 24, speedEv: 0, nature: "Sassy" },
    { speed: 124, percentile: 37, percentage: 13, speedEv: 0, nature: "Hardy" },
    { speed: 171, percentile: 100, percentage: 42, speedEv: 252, nature: "Timid" }
  ],
  Appletun: [
    { speed: 45, percentile: 26, percentage: 26, speedEv: 0, nature: "Quiet" },
    { speed: 50, percentile: 91, percentage: 65, speedEv: 0, nature: "Hardy" }
  ],
  Zebstrika: [
    { speed: 168, percentile: 40, percentage: 21, speedEv: 252, nature: "Modest" },
    { speed: 184, percentile: 100, percentage: 60, speedEv: 252, nature: "Timid" }
  ],
  Dachsbun: [{ speed: 115, percentile: 80, percentage: 78, speedEv: 0, nature: "Adamant" }],
  Toucannon: [
    { speed: 72, percentile: 32, percentage: 32, speedEv: 0, nature: "Brave" },
    { speed: 80, percentile: 82, percentage: 50, speedEv: 0, nature: "Adamant" },
    { speed: 81, percentile: 98, percentage: 16, speedEv: 4, nature: "Adamant" }
  ],
  Trapinch: [
    { speed: 27, percentile: 23, percentage: 23, speedEv: 0, nature: "Brave" },
    { speed: 30, percentile: 79, percentage: 56, speedEv: 0, nature: "Hardy" },
    { speed: 31, percentile: 98, percentage: 19, speedEv: 36, nature: "Relaxed" }
  ],
  Chansey: [{ speed: 70, percentile: 89, percentage: 82, speedEv: 0, nature: "Bold" }],
  Lokix: [
    { speed: 112, percentile: 21, percentage: 21, speedEv: 0, nature: "Adamant" },
    { speed: 144, percentile: 65, percentage: 26, speedEv: 252, nature: "Hardy" },
    { speed: 158, percentile: 100, percentage: 33, speedEv: 252, nature: "Jolly" }
  ],
  Flygon: [
    { speed: 126, percentile: 33, percentage: 30, speedEv: 44, nature: "Adamant" },
    { speed: 127, percentile: 51, percentage: 18, speedEv: 52, nature: "Adamant" },
    { speed: 152, percentile: 83, percentage: 30, speedEv: 252, nature: "Modest" }
  ],
  Dipplin: [
    { speed: 54, percentile: 41, percentage: 41, speedEv: 0, nature: "Sassy" },
    { speed: 60, percentile: 87, percentage: 46, speedEv: 0, nature: "Bold" }
  ],
  Rabsca: [
    { speed: 58, percentile: 69, percentage: 69, speedEv: 0, nature: "Quiet" },
    { speed: 65, percentile: 95, percentage: 26, speedEv: 0, nature: "Bold" }
  ],
  Honchkrow: [
    { speed: 91, percentile: 44, percentage: 34, speedEv: 0, nature: "Adamant" },
    { speed: 135, percentile: 100, percentage: 23, speedEv: 252, nature: "Timid" }
  ],
  Magnezone: [
    { speed: 72, percentile: 24, percentage: 24, speedEv: 0, nature: "Quiet" },
    { speed: 80, percentile: 95, percentage: 71, speedEv: 0, nature: "Calm" }
  ],
  Mudsdale: [
    { speed: 49, percentile: 51, percentage: 51, speedEv: 0, nature: "Sassy" },
    { speed: 55, percentile: 94, percentage: 43, speedEv: 0, nature: "Impish" }
  ],
  Trevenant: [
    { speed: 68, percentile: 67, percentage: 67, speedEv: 0, nature: "Brave" },
    { speed: 76, percentile: 95, percentage: 28, speedEv: 0, nature: "Careful" }
  ],
  "Persian-Alola": [
    { speed: 151, percentile: 30, percentage: 13, speedEv: 124, nature: "Calm" },
    { speed: 167, percentile: 47, percentage: 14, speedEv: 252, nature: "Hardy" },
    { speed: 183, percentile: 100, percentage: 38, speedEv: 252, nature: "Jolly" }
  ],
  "Oricorio-Sensu": [
    { speed: 101, percentile: 15, percentage: 15, speedEv: 0, nature: "Sassy" },
    { speed: 114, percentile: 53, percentage: 25, speedEv: 4, nature: "Modest" },
    { speed: 145, percentile: 86, percentage: 19, speedEv: 252, nature: "Modest" }
  ],
  Froslass: [
    { speed: 146, percentile: 22, percentage: 15, speedEv: 124, nature: "Calm" },
    { speed: 150, percentile: 33, percentage: 11, speedEv: 160, nature: "Hardy" },
    { speed: 178, percentile: 100, percentage: 52, speedEv: 252, nature: "Timid" }
  ],
  Braviary: [
    { speed: 100, percentile: 25, percentage: 25, speedEv: 96, nature: "Brave" },
    { speed: 112, percentile: 54, percentage: 15, speedEv: 92, nature: "Adamant" },
    { speed: 138, percentile: 83, percentage: 16, speedEv: 204, nature: "Jolly" }
  ],
  "Tauros-Paldea-Blaze": [
    { speed: 120, percentile: 15, percentage: 15, speedEv: 0, nature: "Careful" },
    { speed: 152, percentile: 46, percentage: 13, speedEv: 252, nature: "Impish" },
    { speed: 167, percentile: 100, percentage: 54, speedEv: 252, nature: "Jolly" }
  ],
  Golem: [
    { speed: 58, percentile: 58, percentage: 58, speedEv: 0, nature: "Brave" },
    { speed: 65, percentile: 94, percentage: 36, speedEv: 0, nature: "Adamant" }
  ],
  Avalugg: [
    { speed: 43, percentile: 50, percentage: 50, speedEv: 0, nature: "Relaxed" },
    { speed: 48, percentile: 97, percentage: 48, speedEv: 0, nature: "Impish" }
  ],
  Glalie: [
    { speed: 100, percentile: 79, percentage: 76, speedEv: 0, nature: "Hardy" },
    { speed: 145, percentile: 100, percentage: 14, speedEv: 252, nature: "Naive" }
  ],
  Azelf: [
    { speed: 167, percentile: 66, percentage: 48, speedEv: 252, nature: "Adamant" },
    { speed: 183, percentile: 100, percentage: 34, speedEv: 252, nature: "Timid" }
  ],
  Feraligatr: [
    { speed: 98, percentile: 19, percentage: 17, speedEv: 0, nature: "Adamant" },
    { speed: 120, percentile: 50, percentage: 26, speedEv: 176, nature: "Adamant" },
    { speed: 125, percentile: 69, percentage: 19, speedEv: 212, nature: "Adamant" }
  ],
  Vaporeon: [{ speed: 85, percentile: 91, percentage: 87, speedEv: 0, nature: "Hardy" }],
  Camerupt: [
    { speed: 54, percentile: 51, percentage: 51, speedEv: 0, nature: "Quiet" },
    { speed: 60, percentile: 77, percentage: 26, speedEv: 0, nature: "Modest" }
  ],
  Lumineon: [
    { speed: 111, percentile: 22, percentage: 22, speedEv: 0, nature: "Impish" },
    { speed: 157, percentile: 100, percentage: 73, speedEv: 252, nature: "Jolly" }
  ],
  Poliwhirl: [{ speed: 156, percentile: 100, percentage: 89, speedEv: 252, nature: "Timid" }],
  Revavroom: [
    { speed: 142, percentile: 73, percentage: 50, speedEv: 252, nature: "Adamant" },
    { speed: 156, percentile: 100, percentage: 27, speedEv: 252, nature: "Jolly" }
  ],
  Luvdisc: [
    { speed: 149, percentile: 11, percentage: 11, speedEv: 252, nature: "Adamant" },
    { speed: 154, percentile: 41, percentage: 30, speedEv: 180, nature: "Timid" },
    { speed: 163, percentile: 100, percentage: 59, speedEv: 252, nature: "Timid" }
  ],
  Decidueye: [
    { speed: 81, percentile: 11, percentage: 11, speedEv: 0, nature: "Quiet" },
    { speed: 90, percentile: 39, percentage: 28, speedEv: 0, nature: "Adamant" },
    { speed: 122, percentile: 92, percentage: 42, speedEv: 252, nature: "Adamant" }
  ],
  Sentret: [
    { speed: 36, percentile: 35, percentage: 35, speedEv: 0, nature: "Relaxed" },
    { speed: 40, percentile: 100, percentage: 65, speedEv: 0, nature: "Bold" }
  ],
  Poliwag: [{ speed: 156, percentile: 100, percentage: 100, speedEv: 252, nature: "Timid" }],
  Eelektross: [
    { speed: 63, percentile: 32, percentage: 32, speedEv: 0, nature: "Quiet" },
    { speed: 70, percentile: 76, percentage: 42, speedEv: 0, nature: "Hardy" }
  ],
  Cacturne: [
    { speed: 67, percentile: 31, percentage: 31, speedEv: 0, nature: "Quiet" },
    { speed: 75, percentile: 68, percentage: 37, speedEv: 0, nature: "Modest" },
    { speed: 116, percentile: 87, percentage: 16, speedEv: 248, nature: "Jolly" }
  ],
  Ampharos: [
    { speed: 67, percentile: 20, percentage: 20, speedEv: 0, nature: "Quiet" },
    { speed: 75, percentile: 87, percentage: 61, speedEv: 0, nature: "Hardy" }
  ],
  Bellossom: [
    { speed: 70, percentile: 17, percentage: 16, speedEv: 0, nature: "Calm" },
    { speed: 102, percentile: 44, percentage: 13, speedEv: 252, nature: "Bold" },
    { speed: 112, percentile: 100, percentage: 51, speedEv: 252, nature: "Timid" }
  ],
  Arbok: [
    { speed: 100, percentile: 16, percentage: 15, speedEv: 0, nature: "Adamant" },
    { speed: 124, percentile: 45, percentage: 12, speedEv: 100, nature: "Jolly" },
    { speed: 145, percentile: 100, percentage: 53, speedEv: 252, nature: "Jolly" }
  ],
  Dewgong: [
    { speed: 90, percentile: 52, percentage: 44, speedEv: 0, nature: "Careful" },
    { speed: 107, percentile: 92, percentage: 16, speedEv: 132, nature: "Bold" }
  ],
  Heracross: [
    { speed: 105, percentile: 43, percentage: 41, speedEv: 0, nature: "Adamant" },
    { speed: 150, percentile: 100, percentage: 29, speedEv: 252, nature: "Jolly" }
  ],
  Klawf: [{ speed: 139, percentile: 100, percentage: 86, speedEv: 252, nature: "Jolly" }],
  "Tauros-Paldea-Aqua": [
    { speed: 120, percentile: 16, percentage: 16, speedEv: 0, nature: "Adamant" },
    { speed: 167, percentile: 100, percentage: 52, speedEv: 252, nature: "Jolly" }
  ],
  Quagsire: [
    { speed: 49, percentile: 26, percentage: 26, speedEv: 0, nature: "Brave" },
    { speed: 55, percentile: 100, percentage: 72, speedEv: 0, nature: "Impish" }
  ],
  Dedenne: [
    { speed: 121, percentile: 44, percentage: 44, speedEv: 0, nature: "Hardy" },
    { speed: 122, percentile: 59, percentage: 15, speedEv: 4, nature: "Hardy" },
    { speed: 168, percentile: 100, percentage: 27, speedEv: 252, nature: "Timid" }
  ],
  Tentacruel: [
    { speed: 122, percentile: 39, percentage: 16, speedEv: 16, nature: "Modest" },
    { speed: 151, percentile: 75, percentage: 24, speedEv: 144, nature: "Timid" },
    { speed: 167, percentile: 100, percentage: 22, speedEv: 252, nature: "Jolly" }
  ],
  Dragalge: [
    { speed: 57, percentile: 45, percentage: 45, speedEv: 0, nature: "Quiet" },
    { speed: 64, percentile: 90, percentage: 43, speedEv: 0, nature: "Modest" }
  ],
  Bombirdier: [
    { speed: 134, percentile: 71, percentage: 67, speedEv: 252, nature: "Hardy" },
    { speed: 147, percentile: 100, percentage: 29, speedEv: 252, nature: "Jolly" }
  ],
  Polteageist: [
    { speed: 91, percentile: 14, percentage: 11, speedEv: 4, nature: "Hardy" },
    { speed: 122, percentile: 45, percentage: 23, speedEv: 252, nature: "Modest" },
    { speed: 134, percentile: 100, percentage: 53, speedEv: 252, nature: "Timid" }
  ],
  Flapple: [
    { speed: 81, percentile: 14, percentage: 14, speedEv: 0, nature: "Brave" },
    { speed: 120, percentile: 43, percentage: 27, speedEv: 236, nature: "Adamant" },
    { speed: 134, percentile: 100, percentage: 45, speedEv: 252, nature: "Jolly" }
  ],
  Golduck: [
    { speed: 114, percentile: 26, percentage: 19, speedEv: 68, nature: "Bold" },
    { speed: 150, percentile: 100, percentage: 57, speedEv: 252, nature: "Hasty" }
  ],
  Bruxish: [
    { speed: 100, percentile: 12, percentage: 12, speedEv: 0, nature: "Relaxed" },
    { speed: 112, percentile: 58, percentage: 46, speedEv: 0, nature: "Calm" },
    { speed: 158, percentile: 100, percentage: 28, speedEv: 252, nature: "Jolly" }
  ],
  Forretress: [
    { speed: 54, percentile: 43, percentage: 43, speedEv: 0, nature: "Sassy" },
    { speed: 60, percentile: 58, percentage: 14, speedEv: 0, nature: "Adamant" },
    { speed: 61, percentile: 99, percentage: 41, speedEv: 4, nature: "Adamant" }
  ],
  Zacian: [
    { speed: 159, percentile: 18, percentage: 14, speedEv: 4, nature: "Adamant" },
    { speed: 190, percentile: 61, percentage: 16, speedEv: 252, nature: "Adamant" },
    { speed: 209, percentile: 100, percentage: 25, speedEv: 252, nature: "Jolly" }
  ],
  "Lycanroc-Dusk": [
    { speed: 162, percentile: 54, percentage: 48, speedEv: 252, nature: "Adamant" },
    { speed: 178, percentile: 100, percentage: 46, speedEv: 252, nature: "Jolly" }
  ]
}
