import { Pokemon } from "../pokemon"

export function speedMeta(regulation: string): Pokemon[] {
  if(regulation == "Reg G") {
    return regG()
  } else {
    return regH()
  }
}

export function regG(): Pokemon[] {
  return [
    new Pokemon("Urshifu-Rapid-Strike", { ability: "Unseen Fist", nature: "Adamant", item: "Choice Scarf", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Rillaboom", { ability: "Grassy Surge", nature: "Adamant", item: "Assault Vest", evs: { hp: 140, atk: 116, def: 4, spa: 0, spd: 84, spe: 164 }}),
    new Pokemon("Raging Bolt", { ability: "Protosynthesis", nature: "Modest", item: "Booster Energy", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Incineroar", { ability: "Intimidate", nature: "Impish", item: "Safety Goggles", evs: { hp: 252, atk: 4, def: 188, spa: 0, spd: 60, spe: 4 }}),
    new Pokemon("Iron Hands", { ability: "Quark Drive", nature: "Adamant", item: "Assault Vest", evs: { hp: 52, atk: 76, def: 12, spa: 0, spd: 252, spe: 116 }}),
    new Pokemon("Calyrex-Shadow", { ability: "As One (Spectrier)", nature: "Timid", item: "Life Orb", evs: { hp: 0, atk: 0, def: 4, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Chi-Yu", { ability: "Beads of Ruin", nature: "Modest", item: "Choice Scarf", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Farigiraf", { ability: "Armor Tail", nature: "Bold", item: "Electric Seed", evs: { hp: 252, atk: 0, def: 164, spa: 0, spd: 92, spe: 0 }}),
    new Pokemon("Calyrex-Ice", { ability: "As One (Glastrier)", nature: "Brave", item: "Clear Amulet", evs: { hp: 244, atk: 164, def: 0, spa: 0, spd: 100, spe: 0 }}),
    new Pokemon("Flutter Mane", { ability: "Protosynthesis", nature: "Timid", item: "Booster Energy", evs: { hp: 228, atk: 0, def: 108, spa: 20, spd: 12, spe: 140 }}),
    new Pokemon("Ogerpon-Hearthflame", { ability: "Mold Breaker", nature: "Adamant", item: "Hearthflame Mask", evs: { hp: 236, atk: 84, def: 4, spa: 0, spd: 4, spe: 180 }}),
    new Pokemon("Whimsicott", { ability: "Prankster", nature: "Timid", item: "Covert Cloak", evs: { hp: 156, atk: 0, def: 0, spa: 0, spd: 204, spe: 148 }}),
    new Pokemon("Miraidon", { ability: "Hadron Engine", nature: "Timid", item: "Choice Specs", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Amoonguss", { ability: "Regenerator", nature: "Calm", item: "Rocky Helmet", evs: { hp: 236, atk: 0, def: 196, spa: 0, spd: 76, spe: 0 }}),
    new Pokemon("Ogerpon-Cornerstone", { ability: "Sturdy", nature: "Jolly", item: "Cornerstone Mask", evs: { hp: 0, atk: 252, def: 4, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Clefairy", { ability: "Friend Guard", nature: "Sassy", item: "Eviolite", evs: { hp: 252, atk: 0, def: 188, spa: 0, spd: 68, spe: 0 }}),
    new Pokemon("Tornadus", { ability: "Prankster", nature: "Timid", item: "Covert Cloak", evs: { hp: 220, atk: 0, def: 20, spa: 4, spd: 12, spe: 252 }}),
    new Pokemon("Terapagos", { ability: "Tera Shift", nature: "Bold", item: "Leftovers", evs: { hp: 172, atk: 0, def: 76, spa: 60, spd: 4, spe: 196 }}),
    new Pokemon("Chien-Pao", { ability: "Sword of Ruin", nature: "Jolly", item: "Focus Sash", evs: { hp: 0, atk: 252, def: 4, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Urshifu", { ability: "Unseen Fist", nature: "Adamant", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Indeedee-F", { ability: "Psychic Surge", nature: "Bold", item: "Rocky Helmet", evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Pelipper", { ability: "Drizzle", nature: "Modest", item: "Safety Goggles", evs: { hp: 252, atk: 0, def: 20, spa: 36, spd: 148, spe: 52 }}),
    new Pokemon("Zamazenta-Crowned", { ability: "Dauntless Shield", nature: "Impish", item: "Rusted Shield", evs: { hp: 156, atk: 0, def: 156, spa: 0, spd: 0, spe: 196 }}),
    new Pokemon("Dondozo", { ability: "Unaware", nature: "Impish", item: "Leftovers", evs: { hp: 4, atk: 4, def: 116, spa: 0, spd: 212, spe: 172 }}),
    new Pokemon("Tatsugiri", { ability: "Commander", nature: "Modest", item: "Focus Sash", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Weezing-Galar", { ability: "Neutralizing Gas", nature: "Bold", item: "Covert Cloak", evs: { hp: 252, atk: 0, def: 0, spa: 0, spd: 236, spe: 20 }}),
    new Pokemon("Grimmsnarl", { ability: "Prankster", nature: "Careful", item: "Light Clay", evs: { hp: 228, atk: 4, def: 204, spa: 0, spd: 68, spe: 4 }}),
    new Pokemon("Koraidon", { ability: "Orichalcum Pulse", nature: "Adamant", item: "Clear Amulet", evs: { hp: 252, atk: 196, def: 4, spa: 0, spd: 28, spe: 28 }}),
    new Pokemon("Ditto", { ability: "Imposter", nature: "Jolly", item: "Choice Scarf", evs: { hp: 252, atk: 0, def: 0, spa: 0, spd: 4, spe: 252 }}),
    new Pokemon("Landorus", { ability: "Sheer Force", nature: "Modest", item: "Choice Scarf", evs: { hp: 4, atk: 0, def: 4, spa: 244, spd: 4, spe: 252 }}),
    new Pokemon("Ursaluna-Bloodmoon", { ability: "Mind's Eye", nature: "Modest", item: "Life Orb", evs: { hp: 252, atk: 0, def: 4, spa: 252, spd: 0, spe: 0 }}),
    new Pokemon("Ursaluna", { ability: "Guts", nature: "Brave", item: "Flame Orb", evs: { hp: 140, atk: 236, def: 0, spa: 0, spd: 132, spe: 0 }}),
    new Pokemon("Groudon", { ability: "Drought", nature: "Adamant", item: "Clear Amulet", evs: { hp: 164, atk: 156, def: 4, spa: 0, spd: 4, spe: 180 }}),
    new Pokemon("Volcarona", { ability: "Flame Body", nature: "Timid", item: "Leftovers", evs: { hp: 252, atk: 0, def: 132, spa: 0, spd: 0, spe: 124 }}),
    new Pokemon("Kyogre", { ability: "Drizzle", nature: "Modest", item: "Choice Scarf", evs: { hp: 132, atk: 0, def: 140, spa: 68, spd: 12, spe: 156 }}),
    new Pokemon("Smeargle", { ability: "Moody", nature: "Jolly", item: "Focus Sash", evs: { hp: 252, atk: 0, def: 4, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Ogerpon", { ability: "Defiant", nature: "Adamant", item: "Loaded Dice", evs: { hp: 132, atk: 156, def: 4, spa: 0, spd: 4, spe: 212 }}),
    new Pokemon("Entei", { ability: "Inner Focus", nature: "Adamant", item: "Choice Band", evs: { hp: 12, atk: 244, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Iron Crown", { ability: "Quark Drive", nature: "Timid", item: "Life Orb", evs: { hp: 52, atk: 0, def: 20, spa: 252, spd: 4, spe: 180 }}),
    new Pokemon("Ogerpon-Wellspring", { ability: "Water Absorb", nature: "Impish", item: "Wellspring Mask", evs: { hp: 252, atk: 4, def: 220, spa: 0, spd: 12, spe: 20 }}),
    new Pokemon("Mienshao", { ability: "Inner Focus", nature: "Jolly", item: "Focus Sash", evs: { hp: 0, atk: 252, def: 4, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Iron Jugulis", { ability: "Quark Drive", nature: "Timid", item: "Booster Energy", evs: { hp: 92, atk: 0, def: 132, spa: 52, spd: 4, spe: 228 }}),
    new Pokemon("Latios", { ability: "Levitate", nature: "Timid", item: "Life Orb", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Tyranitar", { ability: "Sand Stream", nature: "Adamant", item: "Focus Sash", evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 }}),
    new Pokemon("Maushold", { ability: "Friend Guard", nature: "Impish", item: "Rocky Helmet", evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Iron Treads", { ability: "Quark Drive", nature: "Jolly", item: "Choice Band", evs: { hp: 12, atk: 252, def: 4, spa: 0, spd: 20, spe: 220 }}),
    new Pokemon("Porygon2", { ability: "Download", nature: "Sassy", item: "Eviolite", evs: { hp: 252, atk: 0, def: 140, spa: 0, spd: 116, spe: 0 }}),
    new Pokemon("Annihilape", { ability: "Defiant", nature: "Jolly", item: "Choice Scarf", evs: { hp: 252, atk: 4, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Venusaur", { ability: "Chlorophyll", nature: "Modest", item: "Covert Cloak", evs: { hp: 188, atk: 0, def: 4, spa: 76, spd: 4, spe: 236 }}),
    new Pokemon("Gholdengo", { ability: "Good as Gold", nature: "Modest", item: "Grassy Seed", evs: { hp: 244, atk: 0, def: 12, spa: 12, spd: 20, spe: 220 }}),
    new Pokemon("Scream Tail", { ability: "Protosynthesis", nature: "Timid", item: "Booster Energy", evs: { hp: 252, atk: 0, def: 4, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Kingambit", { ability: "Defiant", nature: "Adamant", item: "Lum Berry", evs: { hp: 252, atk: 100, def: 4, spa: 0, spd: 148, spe: 4 }}),
    new Pokemon("Lunala", { ability: "Shadow Shield", nature: "Modest", item: "Power Herb", evs: { hp: 220, atk: 0, def: 12, spa: 180, spd: 4, spe: 92 }}),
    new Pokemon("Roaring Moon", { ability: "Protosynthesis", nature: "Jolly", item: "Booster Energy", evs: { hp: 28, atk: 220, def: 4, spa: 0, spd: 4, spe: 252 }}),
    new Pokemon("Regidrago", { ability: "Dragon's Maw", nature: "Modest", item: "Life Orb", evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 68, spe: 188 }}),
    new Pokemon("Hitmontop", { ability: "Intimidate", nature: "Impish", item: "Rocky Helmet", evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Zacian-Crowned", { ability: "Intrepid Sword", nature: "Jolly", item: "Rusted Sword", evs: { hp: 76, atk: 252, def: 0, spa: 0, spd: 0, spe: 180 }}),
    new Pokemon("Okidogi", { ability: "Guard Dog", nature: "Adamant", item: "Assault Vest", evs: { hp: 124, atk: 252, def: 4, spa: 0, spd: 12, spe: 116 }}),
    new Pokemon("Tsareena", { ability: "Queenly Majesty", nature: "Adamant", item: "Wide Lens", evs: { hp: 36, atk: 236, def: 4, spa: 0, spd: 4, spe: 228 }}),
    new Pokemon("Talonflame", { ability: "Gale Wings", nature: "Adamant", item: "Life Orb", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Jumpluff", { ability: "Chlorophyll", nature: "Timid", item: "Covert Cloak", evs: { hp: 252, atk: 0, def: 4, spa: 36, spd: 84, spe: 108 }}),
    new Pokemon("Torkoal", { ability: "Drought", nature: "Quiet", item: "Choice Specs", evs: { hp: 252, atk: 0, def: 4, spa: 252, spd: 0, spe: 0 }}),
    new Pokemon("Dragonite", { ability: "Inner Focus", nature: "Adamant", item: "Choice Band", evs: { hp: 156, atk: 252, def: 4, spa: 0, spd: 4, spe: 92 }}),
    new Pokemon("Moltres-Galar", { ability: "Berserk", nature: "Calm", item: "Safety Goggles", evs: { hp: 244, atk: 0, def: 76, spa: 4, spd: 36, spe: 148 }}),
 ]  
}

export function regH(): Pokemon[] {
  return [
    new Pokemon("Gholdengo", { ability: "Good as Gold", nature: "Timid", item: "Choice Scarf", evs: { hp: 4, atk: 0, def: 4, spa: 244, spd: 4, spe: 252 }}),
    new Pokemon("Rillaboom", { ability: "Grassy Surge", nature: "Adamant", item: "Assault Vest", evs: { hp: 252, atk: 116, def: 4, spa: 0, spd: 60, spe: 76 }}),
    new Pokemon("Incineroar", { ability: "Intimidate", nature: "Adamant", item: "Safety Goggles", evs: { hp: 228, atk: 36, def: 4, spa: 0, spd: 36, spe: 204 }}),
    new Pokemon("Amoonguss", { ability: "Regenerator", nature: "Bold", item: "Sitrus Berry", evs: { hp: 236, atk: 0, def: 156, spa: 0, spd: 116, spe: 0 }}),
    new Pokemon("Archaludon", { ability: "Stamina", nature: "Timid", item: "Assault Vest", evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 }}),
    new Pokemon("Kingambit", { ability: "Defiant", nature: "Adamant", item: "Black Glasses", evs: { hp: 252, atk: 252, def: 0, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Pelipper", { ability: "Drizzle", nature: "Modest", item: "Focus Sash", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Volcarona", { ability: "Flame Body", nature: "Modest", item: "Leftovers", evs: { hp: 252, atk: 0, def: 60, spa: 36, spd: 4, spe: 156 }}),
    new Pokemon("Ursaluna-Bloodmoon", { ability: "Mind's Eye", nature: "Modest", item: "Life Orb", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Glimmora", { ability: "Toxic Debris", nature: "Timid", item: "Power Herb", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Dondozo", { ability: "Unaware", nature: "Jolly", item: "Leftovers", evs: { hp: 4, atk: 252, def: 4, spa: 0, spd: 36, spe: 212 }}),
    new Pokemon("Basculegion", { ability: "Swift Swim", nature: "Adamant", item: "Choice Scarf", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Tatsugiri", { ability: "Commander", nature: "Timid", item: "Choice Scarf", evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 }}),
    new Pokemon("Primarina", { ability: "Liquid Voice", nature: "Modest", item: "Throat Spray", evs: { hp: 236, atk: 0, def: 4, spa: 188, spd: 4, spe: 76 }}),
    new Pokemon("Whimsicott", { ability: "Prankster", nature: "Timid", item: "Covert Cloak", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Maushold", { ability: "Friend Guard", nature: "Jolly", item: "Safety Goggles", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Talonflame", { ability: "Gale Wings", nature: "Jolly", item: "Covert Cloak", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Dragonite", { ability: "Inner Focus", nature: "Adamant", item: "Choice Band", evs: { hp: 244, atk: 252, def: 4, spa: 0, spd: 4, spe: 4 }}),
    new Pokemon("Annihilape", { ability: "Defiant", nature: "Jolly", item: "Choice Scarf", evs: { hp: 252, atk: 4, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Indeedee-F", { ability: "Psychic Surge", nature: "Relaxed", item: "Psychic Seed", evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Dragapult", { ability: "Clear Body", nature: "Adamant", item: "Choice Band", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Clefable", { ability: "Unaware", nature: "Calm", item: "Sitrus Berry", evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Tyranitar", { ability: "Sand Stream", nature: "Adamant", item: "Assault Vest", evs: { hp: 164, atk: 252, def: 4, spa: 4, spd: 0, spe: 84 }}),
    new Pokemon("Hydreigon", { ability: "Levitate", nature: "Timid", item: "Life Orb", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Ursaluna", { ability: "Guts", nature: "Brave", item: "Flame Orb", evs: { hp: 252, atk: 252, def: 0, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Pawmot", { ability: "Natural Cure", nature: "Jolly", item: "Focus Sash", evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 }}),
    new Pokemon("Torkoal", { ability: "Drought", nature: "Quiet", item: "Charcoal", evs: { hp: 252, atk: 0, def: 0, spa: 252, spd: 4, spe: 0 }}),
    new Pokemon("Palafin", { ability: "Zero to Hero", nature: "Adamant", item: "Mystic Water", evs: { hp: 252, atk: 252, def: 0, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Farigiraf", { ability: "Armor Tail", nature: "Modest", item: "Throat Spray", evs: { hp: 236, atk: 0, def: 4, spa: 236, spd: 4, spe: 28 }}),
    new Pokemon("Gallade", { ability: "Sharpness", nature: "Brave", item: "Clear Amulet", evs: { hp: 252, atk: 252, def: 4, spa: 0, spd: 0, spe: 0 }}),
    new Pokemon("Murkrow", { ability: "Prankster", nature: "Calm", item: "Eviolite", evs: { hp: 252, atk: 0, def: 44, spa: 0, spd: 212, spe: 0 }}),
    new Pokemon("Armarouge", { ability: "Flash Fire", nature: "Quiet", item: "Life Orb", evs: { hp: 228, atk: 0, def: 0, spa: 252, spd: 28, spe: 0 }}),
    new Pokemon("Tauros-Paldea-Aqua", { ability: "Intimidate", nature: "Adamant", item: "Mirror Herb", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Typhlosion-Hisui", { ability: "Blaze", nature: "Timid", item: "Choice Scarf", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Porygon2", { ability: "Download", nature: "Quiet", item: "Eviolite", evs: { hp: 252, atk: 4, def: 124, spa: 92, spd: 36, spe: 0 }}),
    new Pokemon("Garchomp", { ability: "Rough Skin", nature: "Jolly", item: "Choice Scarf", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Meowscarada", { ability: "Overgrow", nature: "Jolly", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Gastrodon", { ability: "Storm Drain", nature: "Calm", item: "Sitrus Berry", evs: { hp: 252, atk: 0, def: 52, spa: 0, spd: 204, spe: 0 }}),
    new Pokemon("Lilligant-Hisui", { ability: "Chlorophyll", nature: "Jolly", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Hatterene", { ability: "Magic Bounce", nature: "Quiet", item: "Life Orb", evs: { hp: 212, atk: 0, def: 44, spa: 252, spd: 0, spe: 0 }}),
    new Pokemon("Kommo-o", { ability: "Overcoat", nature: "Impish", item: "Leftovers", evs: { hp: 76, atk: 4, def: 196, spa: 0, spd: 28, spe: 204 }}),
    new Pokemon("Grimmsnarl", { ability: "Prankster", nature: "Impish", item: "Light Clay", evs: { hp: 252, atk: 0, def: 68, spa: 0, spd: 188, spe: 0 }}),
    new Pokemon("Electabuzz", { ability: "Vital Spirit", nature: "Bold", item: "Eviolite", evs: { hp: 252, atk: 0, def: 212, spa: 4, spd: 4, spe: 36 }}),
    new Pokemon("Baxcalibur", { ability: "Thermal Exchange", nature: "Adamant", item: "Clear Amulet", evs: { hp: 140, atk: 196, def: 0, spa: 0, spd: 0, spe: 172 }}),
    new Pokemon("Arcanine-Hisui", { ability: "Intimidate", nature: "Jolly", item: "Choice Band", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Tauros-Paldea-Blaze", { ability: "Intimidate", nature: "Jolly", item: "Safety Goggles", evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 }}),
    new Pokemon("Sinistcha", { ability: "Hospitality", nature: "Calm", item: "Rocky Helmet", evs: { hp: 252, atk: 0, def: 92, spa: 4, spd: 156, spe: 4 }}),
    new Pokemon("Salamence", { ability: "Intimidate", nature: "Timid", item: "Choice Scarf", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Sneasler", { ability: "Poison Touch", nature: "Jolly", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Garganacl", { ability: "Purifying Salt", nature: "Careful", item: "Leftovers", evs: { hp: 252, atk: 0, def: 4, spa: 0, spd: 252, spe: 0 }}),
    new Pokemon("Ninetales-Alola", { ability: "Snow Warning", nature: "Timid", item: "Light Clay", evs: { hp: 252, atk: 0, def: 0, spa: 4, spd: 0, spe: 252 }}),
    new Pokemon("Sylveon", { ability: "Pixilate", nature: "Modest", item: "Throat Spray", evs: { hp: 60, atk: 0, def: 0, spa: 252, spd: 0, spe: 196 }}),
    new Pokemon("Decidueye-Hisui", { ability: "Scrappy", nature: "Adamant", item: "Razor Claw", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Gyarados", { ability: "Intimidate", nature: "Impish", item: "Sitrus Berry", evs: { hp: 236, atk: 4, def: 172, spa: 0, spd: 76, spe: 20 }}),
    new Pokemon("Gengar", { ability: "Cursed Body", nature: "Timid", item: "Focus Sash", evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 }}),
    new Pokemon("Clefairy", { ability: "Friend Guard", nature: "Sassy", item: "Eviolite", evs: { hp: 252, atk: 0, def: 220, spa: 0, spd: 36, spe: 0 }}),
    new Pokemon("Mimikyu", { ability: "Disguise", nature: "Adamant", item: "Life Orb", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Excadrill", { ability: "Sand Rush", nature: "Adamant", item: "Clear Amulet", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Blaziken", { ability: "Speed Boost", nature: "Adamant", item: "Clear Amulet", evs: { hp: 4, atk: 252, def: 4, spa: 0, spd: 4, spe: 244 }}),
    new Pokemon("Politoed", { ability: "Drizzle", nature: "Bold", item: "Sitrus Berry", evs: { hp: 252, atk: 0, def: 164, spa: 12, spd: 76, spe: 4 }}),
    new Pokemon("Smeargle", { ability: "Moody", nature: "Relaxed", item: "Focus Sash", evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Lycanroc", { ability: "Sand Rush", nature: "Jolly", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Zoroark-Hisui", { ability: "Illusion", nature: "Modest", item: "Choice Specs", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Corviknight", { ability: "Mirror Armor", nature: "Adamant", item: "Sitrus Berry", evs: { hp: 252, atk: 84, def: 4, spa: 0, spd: 92, spe: 76 }}),
 ]  
}