import { Pokemon } from "../pokemon"

export function speedMeta(regulation: string): Pokemon[] {
  if(regulation == "Reg G") {
    return regG()
  } else {
    return regH()
  }
}

export function regG(): Pokemon[] {
  return [
    new Pokemon("Urshifu-Rapid-Strike", { nature: "Adamant", item: "Choice Scarf", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Rillaboom", { nature: "Adamant", item: "Assault Vest", evs: { hp: 140, atk: 116, def: 4, spa: 0, spd: 84, spe: 164 }}),
    new Pokemon("Raging Bolt", { nature: "Modest", item: "Booster Energy", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Incineroar", { nature: "Impish", item: "Safety Goggles", evs: { hp: 252, atk: 4, def: 188, spa: 0, spd: 60, spe: 4 }}),
    new Pokemon("Iron Hands", { nature: "Adamant", item: "Assault Vest", evs: { hp: 52, atk: 76, def: 12, spa: 0, spd: 252, spe: 116 }}),
    new Pokemon("Calyrex-Shadow", { nature: "Timid", item: "Life Orb", evs: { hp: 0, atk: 0, def: 4, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Chi-Yu", { nature: "Modest", item: "Choice Scarf", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Farigiraf", { nature: "Bold", item: "Electric Seed", evs: { hp: 252, atk: 0, def: 164, spa: 0, spd: 92, spe: 0 }}),
    new Pokemon("Calyrex-Ice", { nature: "Brave", item: "Clear Amulet", evs: { hp: 244, atk: 164, def: 0, spa: 0, spd: 100, spe: 0 }}),
    new Pokemon("Flutter Mane", { nature: "Timid", item: "Booster Energy", evs: { hp: 228, atk: 0, def: 108, spa: 20, spd: 12, spe: 140 }}),
    new Pokemon("Ogerpon-Hearthflame", { nature: "Adamant", item: "Hearthflame Mask", evs: { hp: 236, atk: 84, def: 4, spa: 0, spd: 4, spe: 180 }}),
    new Pokemon("Whimsicott", { nature: "Timid", item: "Covert Cloak", evs: { hp: 156, atk: 0, def: 0, spa: 0, spd: 204, spe: 148 }}),
    new Pokemon("Miraidon", { nature: "Timid", item: "Choice Specs", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Amoonguss", { nature: "Calm", item: "Rocky Helmet", evs: { hp: 236, atk: 0, def: 196, spa: 0, spd: 76, spe: 0 }}),
    new Pokemon("Ogerpon-Cornerstone", { nature: "Jolly", item: "Cornerstone Mask", evs: { hp: 0, atk: 252, def: 4, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Clefairy", { nature: "Sassy", item: "Eviolite", evs: { hp: 252, atk: 0, def: 188, spa: 0, spd: 68, spe: 0 }}),
    new Pokemon("Tornadus", { nature: "Timid", item: "Covert Cloak", evs: { hp: 220, atk: 0, def: 20, spa: 4, spd: 12, spe: 252 }}),
    new Pokemon("Terapagos", { nature: "Bold", item: "Leftovers", evs: { hp: 172, atk: 0, def: 76, spa: 60, spd: 4, spe: 196 }}),
    new Pokemon("Chien-Pao", { nature: "Jolly", item: "Focus Sash", evs: { hp: 0, atk: 252, def: 4, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Urshifu", { nature: "Adamant", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Indeedee-F", { nature: "Bold", item: "Rocky Helmet", evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Pelipper", { nature: "Modest", item: "Safety Goggles", evs: { hp: 252, atk: 0, def: 20, spa: 36, spd: 148, spe: 52 }}),
    new Pokemon("Zamazenta-Crowned", { nature: "Impish", item: "Rusted Shield", evs: { hp: 156, atk: 0, def: 156, spa: 0, spd: 0, spe: 196 }}),
    new Pokemon("Dondozo", { nature: "Impish", item: "Leftovers", evs: { hp: 4, atk: 4, def: 116, spa: 0, spd: 212, spe: 172 }}),
    new Pokemon("Tatsugiri", { nature: "Modest", item: "Focus Sash", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Weezing-Galar", { nature: "Bold", item: "Covert Cloak", evs: { hp: 252, atk: 0, def: 0, spa: 0, spd: 236, spe: 20 }}),
    new Pokemon("Grimmsnarl", { nature: "Careful", item: "Light Clay", evs: { hp: 228, atk: 4, def: 204, spa: 0, spd: 68, spe: 4 }}),
    new Pokemon("Koraidon", { nature: "Adamant", item: "Clear Amulet", evs: { hp: 252, atk: 196, def: 4, spa: 0, spd: 28, spe: 28 }}),
    new Pokemon("Ditto", { nature: "Jolly", item: "Choice Scarf", evs: { hp: 252, atk: 0, def: 0, spa: 0, spd: 4, spe: 252 }}),
    new Pokemon("Landorus", { nature: "Modest", item: "Choice Scarf", evs: { hp: 4, atk: 0, def: 4, spa: 244, spd: 4, spe: 252 }}),
    new Pokemon("Ursaluna-Bloodmoon", { nature: "Modest", item: "Life Orb", evs: { hp: 252, atk: 0, def: 4, spa: 252, spd: 0, spe: 0 }}),
    new Pokemon("Ursaluna", { nature: "Brave", item: "Flame Orb", evs: { hp: 140, atk: 236, def: 0, spa: 0, spd: 132, spe: 0 }}),
    new Pokemon("Groudon", { nature: "Adamant", item: "Clear Amulet", evs: { hp: 164, atk: 156, def: 4, spa: 0, spd: 4, spe: 180 }}),
    new Pokemon("Volcarona", { nature: "Timid", item: "Leftovers", evs: { hp: 252, atk: 0, def: 132, spa: 0, spd: 0, spe: 124 }}),
    new Pokemon("Kyogre", { nature: "Modest", item: "Choice Scarf", evs: { hp: 132, atk: 0, def: 140, spa: 68, spd: 12, spe: 156 }}),
    new Pokemon("Smeargle", { nature: "Jolly", item: "Focus Sash", evs: { hp: 252, atk: 0, def: 4, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Ogerpon", { nature: "Adamant", item: "Loaded Dice", evs: { hp: 132, atk: 156, def: 4, spa: 0, spd: 4, spe: 212 }}),
    new Pokemon("Entei", { nature: "Adamant", item: "Choice Band", evs: { hp: 12, atk: 244, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Iron Crown", { nature: "Timid", item: "Life Orb", evs: { hp: 52, atk: 0, def: 20, spa: 252, spd: 4, spe: 180 }}),
    new Pokemon("Ogerpon-Wellspring", { nature: "Impish", item: "Wellspring Mask", evs: { hp: 252, atk: 4, def: 220, spa: 0, spd: 12, spe: 20 }}),
    new Pokemon("Mienshao", { nature: "Jolly", item: "Focus Sash", evs: { hp: 0, atk: 252, def: 4, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Iron Jugulis", { nature: "Timid", item: "Booster Energy", evs: { hp: 92, atk: 0, def: 132, spa: 52, spd: 4, spe: 228 }}),
    new Pokemon("Latios", { nature: "Timid", item: "Life Orb", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Tyranitar", { nature: "Adamant", item: "Focus Sash", evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 }}),
    new Pokemon("Maushold", { nature: "Impish", item: "Rocky Helmet", evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Iron Treads", { nature: "Jolly", item: "Choice Band", evs: { hp: 12, atk: 252, def: 4, spa: 0, spd: 20, spe: 220 }}),
    new Pokemon("Porygon2", { nature: "Sassy", item: "Eviolite", evs: { hp: 252, atk: 0, def: 140, spa: 0, spd: 116, spe: 0 }}),
    new Pokemon("Annihilape", { nature: "Jolly", item: "Choice Scarf", evs: { hp: 252, atk: 4, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Venusaur", { nature: "Modest", item: "Covert Cloak", evs: { hp: 188, atk: 0, def: 4, spa: 76, spd: 4, spe: 236 }}),
    new Pokemon("Gholdengo", { nature: "Modest", item: "Grassy Seed", evs: { hp: 244, atk: 0, def: 12, spa: 12, spd: 20, spe: 220 }}),
    new Pokemon("Scream Tail", { nature: "Timid", item: "Booster Energy", evs: { hp: 252, atk: 0, def: 4, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Kingambit", { nature: "Adamant", item: "Lum Berry", evs: { hp: 252, atk: 100, def: 4, spa: 0, spd: 148, spe: 4 }}),
    new Pokemon("Lunala", { nature: "Modest", item: "Power Herb", evs: { hp: 220, atk: 0, def: 12, spa: 180, spd: 4, spe: 92 }}),
    new Pokemon("Roaring Moon", { nature: "Jolly", item: "Booster Energy", evs: { hp: 28, atk: 220, def: 4, spa: 0, spd: 4, spe: 252 }}),
    new Pokemon("Regidrago", { nature: "Modest", item: "Life Orb", evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 68, spe: 188 }}),
    new Pokemon("Hitmontop", { nature: "Impish", item: "Rocky Helmet", evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Zacian-Crowned", { nature: "Jolly", item: "Rusted Sword", evs: { hp: 76, atk: 252, def: 0, spa: 0, spd: 0, spe: 180 }}),
    new Pokemon("Okidogi", { nature: "Adamant", item: "Assault Vest", evs: { hp: 124, atk: 252, def: 4, spa: 0, spd: 12, spe: 116 }}),
    new Pokemon("Tsareena", { nature: "Adamant", item: "Wide Lens", evs: { hp: 36, atk: 236, def: 4, spa: 0, spd: 4, spe: 228 }}),
    new Pokemon("Talonflame", { nature: "Adamant", item: "Life Orb", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Jumpluff", { nature: "Timid", item: "Covert Cloak", evs: { hp: 252, atk: 0, def: 4, spa: 36, spd: 84, spe: 108 }}),
    new Pokemon("Torkoal", { nature: "Quiet", item: "Choice Specs", evs: { hp: 252, atk: 0, def: 4, spa: 252, spd: 0, spe: 0 }}),
    new Pokemon("Dragonite", { nature: "Adamant", item: "Choice Band", evs: { hp: 156, atk: 252, def: 4, spa: 0, spd: 4, spe: 92 }}),
    new Pokemon("Moltres-Galar", { nature: "Calm", item: "Safety Goggles", evs: { hp: 244, atk: 0, def: 76, spa: 4, spd: 36, spe: 148 }}),
    new Pokemon("Comfey", { nature: "Calm", item: "Sitrus Berry", evs: { hp: 220, atk: 0, def: 172, spa: 12, spd: 76, spe: 28 }}),
    new Pokemon("Electabuzz", { nature: "Bold", item: "Eviolite", evs: { hp: 252, atk: 0, def: 180, spa: 0, spd: 76, spe: 0 }}),
    new Pokemon("Gallade", { nature: "Brave", item: "Clear Amulet", evs: { hp: 252, atk: 252, def: 4, spa: 0, spd: 0, spe: 0 }}),
    new Pokemon("Iron Leaves", { nature: "Jolly", item: "Life Orb", evs: { hp: 92, atk: 156, def: 4, spa: 0, spd: 4, spe: 252 }}),
    new Pokemon("Lilligant-Hisui", { nature: "Jolly", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Necrozma-Dawn-Wings", { nature: "Quiet", item: "Power Herb", evs: { hp: 252, atk: 0, def: 4, spa: 252, spd: 0, spe: 0 }}),
    new Pokemon("Snorlax", { nature: "Impish", item: "Leftovers", evs: { hp: 140, atk: 116, def: 252, spa: 0, spd: 0, spe: 0 }}),
    new Pokemon("Archaludon", { nature: "Modest", item: "Assault Vest", evs: { hp: 124, atk: 0, def: 12, spa: 196, spd: 116, spe: 60 }}),
    new Pokemon("Arcanine-Hisui", { nature: "Adamant", item: "Choice Band", evs: { hp: 180, atk: 196, def: 92, spa: 0, spd: 4, spe: 36 }}),
    new Pokemon("Tinkaton", { nature: "Jolly", item: "Iron Plate", evs: { hp: 204, atk: 252, def: 4, spa: 0, spd: 4, spe: 44 }}),
    new Pokemon("Iron Valiant", { nature: "Jolly", item: "Booster Energy", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Regigigas", { nature: "Adamant", item: "Life Orb", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Ting-Lu", { nature: "Impish", item: "Rocky Helmet", evs: { hp: 228, atk: 4, def: 36, spa: 0, spd: 236, spe: 4 }}),
    new Pokemon("Regieleki", { nature: "Modest", item: "Focus Sash", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Glimmora", { nature: "Bold", item: "Power Herb", evs: { hp: 252, atk: 0, def: 76, spa: 28, spd: 100, spe: 52 }}),
    new Pokemon("Cresselia", { nature: "Bold", item: "Safety Goggles", evs: { hp: 244, atk: 0, def: 220, spa: 0, spd: 44, spe: 0 }}),
    new Pokemon("Basculegion", { nature: "Adamant", item: "Choice Band", evs: { hp: 0, atk: 252, def: 4, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Brute Bonnet", { nature: "Impish", item: "Covert Cloak", evs: { hp: 252, atk: 4, def: 132, spa: 0, spd: 116, spe: 4 }}),
    new Pokemon("Armarouge", { nature: "Quiet", item: "Life Orb", evs: { hp: 252, atk: 0, def: 0, spa: 252, spd: 4, spe: 0 }}),
    new Pokemon("Alcremie", { nature: "Quiet", item: "Iron Ball", evs: { hp: 252, atk: 0, def: 108, spa: 124, spd: 24, spe: 0 }}),
    new Pokemon("Registeel", { nature: "Impish", item: "Leftovers", evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Pyroar", { nature: "Timid", item: "Choice Specs", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Iron Boulder", { nature: "Jolly", item: "Choice Band", evs: { hp: 92, atk: 252, def: 4, spa: 0, spd: 4, spe: 156 }}),
    new Pokemon("Araquanid", { nature: "Adamant", item: "Covert Cloak", evs: { hp: 140, atk: 252, def: 108, spa: 0, spd: 4, spe: 4 }}),
    new Pokemon("Mamoswine", { nature: "Adamant", item: "Assault Vest", evs: { hp: 4, atk: 252, def: 4, spa: 0, spd: 20, spe: 228 }}),
    new Pokemon("Gastrodon", { nature: "Relaxed", item: "Leftovers", evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Thundurus", { nature: "Bold", item: "Covert Cloak", evs: { hp: 252, atk: 0, def: 236, spa: 0, spd: 20, spe: 0 }}),
    new Pokemon("Goodra-Hisui", { nature: "Modest", item: "Leftovers", evs: { hp: 252, atk: 0, def: 148, spa: 4, spd: 92, spe: 12 }}),
    new Pokemon("Gothitelle", { nature: "Timid", item: "Sitrus Berry", evs: { hp: 252, atk: 0, def: 4, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Sneasler", { nature: "Adamant", item: "Psychic Seed", evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 }}),
    new Pokemon("Skeledirge", { nature: "Modest", item: "Safety Goggles", evs: { hp: 228, atk: 0, def: 100, spa: 76, spd: 92, spe: 12 }}),
    new Pokemon("Klefki", { nature: "Calm", item: "Light Clay", evs: { hp: 252, atk: 0, def: 148, spa: 4, spd: 100, spe: 4 }}),
    new Pokemon("Sableye", { nature: "Timid", item: "Focus Sash", evs: { hp: 12, atk: 0, def: 244, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Alomomola", { nature: "Sassy", item: "Rocky Helmet", evs: { hp: 68, atk: 4, def: 180, spa: 4, spd: 252, spe: 0 }}),
    new Pokemon("Umbreon", { nature: "Calm", item: "Safety Goggles", evs: { hp: 244, atk: 0, def: 228, spa: 0, spd: 36, spe: 0 }}),
    new Pokemon("Chandelure", { nature: "Modest", item: "Life Orb", evs: { hp: 188, atk: 0, def: 4, spa: 196, spd: 100, spe: 20 }}),
    new Pokemon("Walking Wake", { nature: "Timid", item: "Choice Scarf", evs: { hp: 4, atk: 0, def: 4, spa: 244, spd: 4, spe: 252 }}),
    new Pokemon("Heatran", { nature: "Modest", item: "Assault Vest", evs: { hp: 236, atk: 0, def: 4, spa: 236, spd: 12, spe: 20 }}),
    new Pokemon("Cobalion", { nature: "Bold", item: "Grassy Seed", evs: { hp: 252, atk: 0, def: 156, spa: 4, spd: 4, spe: 92 }}),
    new Pokemon("Hydreigon", { nature: "Modest", item: "Covert Cloak", evs: { hp: 212, atk: 0, def: 4, spa: 36, spd: 4, spe: 252 }}),
    new Pokemon("Iron Bundle", { nature: "Timid", item: "Focus Sash", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Mimikyu", { nature: "Adamant", item: "Life Orb", evs: { hp: 228, atk: 252, def: 28, spa: 0, spd: 0, spe: 0 }}),
    new Pokemon("Wo-Chien", { nature: "Bold", item: "Leftovers", evs: { hp: 252, atk: 0, def: 44, spa: 4, spd: 20, spe: 188 }}),
    new Pokemon("Rhyperior", { nature: "Adamant", item: "Assault Vest", evs: { hp: 172, atk: 236, def: 0, spa: 0, spd: 0, spe: 100 }}),
    new Pokemon("Bronzong", { nature: "Impish", item: "Electric Seed", evs: { hp: 252, atk: 0, def: 188, spa: 0, spd: 68, spe: 0 }}),
    new Pokemon("Rayquaza", { nature: "Adamant", item: "Clear Amulet", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Flamigo", { nature: "Jolly", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Toxapex", { nature: "Calm", item: "Leftovers", evs: { hp: 244, atk: 0, def: 116, spa: 0, spd: 148, spe: 0 }}),
    new Pokemon("Landorus-Therian", { nature: "Adamant", item: "Choice Scarf", evs: { hp: 252, atk: 4, def: 0, spa: 0, spd: 252, spe: 0 }}),
    new Pokemon("Altaria", { nature: "Calm", item: "Mental Herb", evs: { hp: 252, atk: 0, def: 12, spa: 4, spd: 116, spe: 124 }}),
    new Pokemon("Gouging Fire", { nature: "Jolly", item: "Booster Energy", evs: { hp: 84, atk: 164, def: 4, spa: 0, spd: 4, spe: 252 }}),
    new Pokemon("Dragapult", { nature: "Jolly", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Primarina", { nature: "Modest", item: "Throat Spray", evs: { hp: 252, atk: 0, def: 140, spa: 108, spd: 4, spe: 4 }}),
    new Pokemon("Ninetales-Alola", { nature: "Timid", item: "Light Clay", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Sandy Shocks", { nature: "Timid", item: "Booster Energy", evs: { hp: 44, atk: 0, def: 4, spa: 204, spd: 4, spe: 252 }}),
    new Pokemon("Eternatus", { nature: "Modest", item: "Life Orb", evs: { hp: 28, atk: 0, def: 0, spa: 236, spd: 0, spe: 244 }}),
    new Pokemon("Ceruledge", { nature: "Adamant", item: "Clear Amulet", evs: { hp: 252, atk: 116, def: 12, spa: 0, spd: 52, spe: 76 }}),
    new Pokemon("Dugtrio", { nature: "Jolly", item: "Focus Sash", evs: { hp: 0, atk: 252, def: 4, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Typhlosion-Hisui", { nature: "Timid", item: "Choice Scarf", evs: { hp: 28, atk: 0, def: 4, spa: 252, spd: 4, spe: 220 }}),
    new Pokemon("Kommo-o", { nature: "Impish", item: "Leftovers", evs: { hp: 252, atk: 4, def: 156, spa: 0, spd: 92, spe: 4 }}),
    new Pokemon("Hariyama", { nature: "Adamant", item: "Ability Shield", evs: { hp: 0, atk: 164, def: 252, spa: 0, spd: 92, spe: 0 }}),
    new Pokemon("Milotic", { nature: "Calm", item: "Leftovers", evs: { hp: 180, atk: 0, def: 156, spa: 108, spd: 36, spe: 28 }}),
    new Pokemon("Carbink", { nature: "Quiet", item: "Power Herb", evs: { hp: 252, atk: 0, def: 0, spa: 252, spd: 0, spe: 0 }}),
    new Pokemon("Oranguru", { nature: "Timid", item: "Covert Cloak", evs: { hp: 252, atk: 0, def: 0, spa: 0, spd: 4, spe: 252 }}),
    new Pokemon("Mandibuzz", { nature: "Bold", item: "Rocky Helmet", evs: { hp: 212, atk: 0, def: 116, spa: 0, spd: 180, spe: 0 }}),
    new Pokemon("Kyurem-White", { nature: "Modest", item: "Choice Specs", evs: { hp: 132, atk: 0, def: 12, spa: 252, spd: 4, spe: 108 }}),
    new Pokemon("Raichu", { nature: "Timid", item: "Assault Vest", evs: { hp: 84, atk: 0, def: 180, spa: 4, spd: 60, spe: 180 }}),
    new Pokemon("Sinistcha", { nature: "Bold", item: "Rocky Helmet", evs: { hp: 252, atk: 0, def: 132, spa: 0, spd: 124, spe: 0 }}),
    new Pokemon("Hatterene", { nature: "Quiet", item: "Life Orb", evs: { hp: 140, atk: 0, def: 0, spa: 252, spd: 116, spe: 0 }}),
    new Pokemon("Magmar", { nature: "Bold", item: "Eviolite", evs: { hp: 252, atk: 0, def: 212, spa: 4, spd: 36, spe: 4 }}),
    new Pokemon("Electivire", { nature: "Calm", item: "Leftovers", evs: { hp: 252, atk: 0, def: 0, spa: 4, spd: 252, spe: 0 }}),
    new Pokemon("Ludicolo", { nature: "Modest", item: "Choice Specs", evs: { hp: 52, atk: 0, def: 0, spa: 236, spd: 0, spe: 220 }}),
    new Pokemon("Trevenant", { nature: "Sassy", item: "Sitrus Berry", evs: { hp: 252, atk: 4, def: 0, spa: 0, spd: 252, spe: 0 }}),
 ]  
}

export function regH(): Pokemon[] {
  return [
    new Pokemon("Gholdengo", { nature: "Timid", item: "Choice Scarf", evs: { hp: 4, atk: 0, def: 4, spa: 244, spd: 4, spe: 252 }}),
    new Pokemon("Rillaboom", { nature: "Adamant", item: "Assault Vest", evs: { hp: 252, atk: 116, def: 4, spa: 0, spd: 60, spe: 76 }}),
    new Pokemon("Incineroar", { nature: "Adamant", item: "Safety Goggles", evs: { hp: 228, atk: 36, def: 4, spa: 0, spd: 36, spe: 204 }}),
    new Pokemon("Amoonguss", { nature: "Bold", item: "Sitrus Berry", evs: { hp: 236, atk: 0, def: 156, spa: 0, spd: 116, spe: 0 }}),
    new Pokemon("Archaludon", { nature: "Timid", item: "Assault Vest", evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 }}),
    new Pokemon("Kingambit", { nature: "Adamant", item: "Black Glasses", evs: { hp: 252, atk: 252, def: 0, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Pelipper", { nature: "Modest", item: "Focus Sash", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Volcarona", { nature: "Modest", item: "Leftovers", evs: { hp: 252, atk: 0, def: 60, spa: 36, spd: 4, spe: 156 }}),
    new Pokemon("Ursaluna-Bloodmoon", { nature: "Modest", item: "Life Orb", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Glimmora", { nature: "Timid", item: "Power Herb", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Dondozo", { nature: "Jolly", item: "Leftovers", evs: { hp: 4, atk: 252, def: 4, spa: 0, spd: 36, spe: 212 }}),
    new Pokemon("Basculegion", { nature: "Adamant", item: "Choice Scarf", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Tatsugiri", { nature: "Timid", item: "Choice Scarf", evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 }}),
    new Pokemon("Primarina", { nature: "Modest", item: "Throat Spray", evs: { hp: 236, atk: 0, def: 4, spa: 188, spd: 4, spe: 76 }}),
    new Pokemon("Whimsicott", { nature: "Timid", item: "Covert Cloak", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Maushold", { nature: "Jolly", item: "Safety Goggles", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Talonflame", { nature: "Jolly", item: "Covert Cloak", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Dragonite", { nature: "Adamant", item: "Choice Band", evs: { hp: 244, atk: 252, def: 4, spa: 0, spd: 4, spe: 4 }}),
    new Pokemon("Annihilape", { nature: "Jolly", item: "Choice Scarf", evs: { hp: 252, atk: 4, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Indeedee-F", { nature: "Relaxed", item: "Psychic Seed", evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Dragapult", { nature: "Adamant", item: "Choice Band", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Clefable", { nature: "Calm", item: "Sitrus Berry", evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Tyranitar", { nature: "Adamant", item: "Assault Vest", evs: { hp: 164, atk: 252, def: 4, spa: 4, spd: 0, spe: 84 }}),
    new Pokemon("Hydreigon", { nature: "Timid", item: "Life Orb", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Ursaluna", { nature: "Brave", item: "Flame Orb", evs: { hp: 252, atk: 252, def: 0, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Pawmot", { nature: "Jolly", item: "Focus Sash", evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 }}),
    new Pokemon("Torkoal", { nature: "Quiet", item: "Charcoal", evs: { hp: 252, atk: 0, def: 0, spa: 252, spd: 4, spe: 0 }}),
    new Pokemon("Palafin", { nature: "Adamant", item: "Mystic Water", evs: { hp: 252, atk: 252, def: 0, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Farigiraf", { nature: "Modest", item: "Throat Spray", evs: { hp: 236, atk: 0, def: 4, spa: 236, spd: 4, spe: 28 }}),
    new Pokemon("Gallade", { nature: "Brave", item: "Clear Amulet", evs: { hp: 252, atk: 252, def: 4, spa: 0, spd: 0, spe: 0 }}),
    new Pokemon("Murkrow", { nature: "Calm", item: "Eviolite", evs: { hp: 252, atk: 0, def: 44, spa: 0, spd: 212, spe: 0 }}),
    new Pokemon("Armarouge", { nature: "Quiet", item: "Life Orb", evs: { hp: 228, atk: 0, def: 0, spa: 252, spd: 28, spe: 0 }}),
    new Pokemon("Tauros-Paldea-Aqua", { nature: "Adamant", item: "Mirror Herb", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Typhlosion-Hisui", { nature: "Timid", item: "Choice Scarf", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Porygon2", { nature: "Quiet", item: "Eviolite", evs: { hp: 252, atk: 4, def: 124, spa: 92, spd: 36, spe: 0 }}),
    new Pokemon("Garchomp", { nature: "Jolly", item: "Choice Scarf", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Meowscarada", { nature: "Jolly", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Gastrodon", { nature: "Calm", item: "Sitrus Berry", evs: { hp: 252, atk: 0, def: 52, spa: 0, spd: 204, spe: 0 }}),
    new Pokemon("Lilligant-Hisui", { nature: "Jolly", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Hatterene", { nature: "Quiet", item: "Life Orb", evs: { hp: 212, atk: 0, def: 44, spa: 252, spd: 0, spe: 0 }}),
    new Pokemon("Kommo-o", { nature: "Impish", item: "Leftovers", evs: { hp: 76, atk: 4, def: 196, spa: 0, spd: 28, spe: 204 }}),
    new Pokemon("Grimmsnarl", { nature: "Impish", item: "Light Clay", evs: { hp: 252, atk: 0, def: 68, spa: 0, spd: 188, spe: 0 }}),
    new Pokemon("Electabuzz", { nature: "Bold", item: "Eviolite", evs: { hp: 252, atk: 0, def: 212, spa: 4, spd: 4, spe: 36 }}),
    new Pokemon("Baxcalibur", { nature: "Adamant", item: "Clear Amulet", evs: { hp: 140, atk: 196, def: 0, spa: 0, spd: 0, spe: 172 }}),
    new Pokemon("Arcanine-Hisui", { nature: "Jolly", item: "Choice Band", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Tauros-Paldea-Blaze", { nature: "Jolly", item: "Safety Goggles", evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 }}),
    new Pokemon("Sinistcha", { nature: "Calm", item: "Rocky Helmet", evs: { hp: 252, atk: 0, def: 92, spa: 4, spd: 156, spe: 4 }}),
    new Pokemon("Salamence", { nature: "Timid", item: "Choice Scarf", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Sneasler", { nature: "Jolly", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Garganacl", { nature: "Careful", item: "Leftovers", evs: { hp: 252, atk: 0, def: 4, spa: 0, spd: 252, spe: 0 }}),
    new Pokemon("Ninetales-Alola", { nature: "Timid", item: "Light Clay", evs: { hp: 252, atk: 0, def: 0, spa: 4, spd: 0, spe: 252 }}),
    new Pokemon("Sylveon", { nature: "Modest", item: "Throat Spray", evs: { hp: 60, atk: 0, def: 0, spa: 252, spd: 0, spe: 196 }}),
    new Pokemon("Decidueye-Hisui", { nature: "Adamant", item: "Razor Claw", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Gyarados", { nature: "Impish", item: "Sitrus Berry", evs: { hp: 236, atk: 4, def: 172, spa: 0, spd: 76, spe: 20 }}),
    new Pokemon("Gengar", { nature: "Timid", item: "Focus Sash", evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 }}),
    new Pokemon("Clefairy", { nature: "Sassy", item: "Eviolite", evs: { hp: 252, atk: 0, def: 220, spa: 0, spd: 36, spe: 0 }}),
    new Pokemon("Mimikyu", { nature: "Adamant", item: "Life Orb", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Excadrill", { nature: "Adamant", item: "Clear Amulet", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Blaziken", { nature: "Adamant", item: "Clear Amulet", evs: { hp: 4, atk: 252, def: 4, spa: 0, spd: 4, spe: 244 }}),
    new Pokemon("Politoed", { nature: "Bold", item: "Sitrus Berry", evs: { hp: 252, atk: 0, def: 164, spa: 12, spd: 76, spe: 4 }}),
    new Pokemon("Smeargle", { nature: "Relaxed", item: "Focus Sash", evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Lycanroc", { nature: "Jolly", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Zoroark-Hisui", { nature: "Modest", item: "Choice Specs", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Corviknight", { nature: "Adamant", item: "Sitrus Berry", evs: { hp: 252, atk: 84, def: 4, spa: 0, spd: 92, spe: 76 }}),
    new Pokemon("Dusclops", { nature: "Sassy", item: "Eviolite", evs: { hp: 252, atk: 0, def: 156, spa: 0, spd: 100, spe: 0 }}),
    new Pokemon("Weezing", { nature: "Bold", item: "Covert Cloak", evs: { hp: 252, atk: 0, def: 0, spa: 0, spd: 236, spe: 20 }}),
    new Pokemon("Magmar", { nature: "Calm", item: "Eviolite", evs: { hp: 252, atk: 0, def: 212, spa: 4, spd: 36, spe: 4 }}),
    new Pokemon("Gothitelle", { nature: "Careful", item: "Sitrus Berry", evs: { hp: 244, atk: 0, def: 228, spa: 0, spd: 36, spe: 0 }}),
    new Pokemon("Ninetales", { nature: "Timid", item: "Life Orb", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Weezing-Galar", { nature: "Modest", item: "Choice Specs", evs: { hp: 116, atk: 0, def: 4, spa: 196, spd: 100, spe: 92 }}),
    new Pokemon("Chandelure", { nature: "Timid", item: "Choice Scarf", evs: { hp: 4, atk: 0, def: 4, spa: 252, spd: 4, spe: 244 }}),
    new Pokemon("Kilowattrel", { nature: "Timid", item: "Focus Sash", evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 }}),
    new Pokemon("Overqwil", { nature: "Adamant", item: "Life Orb", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Mienshao", { nature: "Jolly", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Indeedee", { nature: "Modest", item: "Choice Scarf", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Milotic", { nature: "Bold", item: "Leftovers", evs: { hp: 252, atk: 0, def: 204, spa: 4, spd: 4, spe: 44 }}),
    new Pokemon("Delphox", { nature: "Timid", item: "Life Orb", evs: { hp: 0, atk: 0, def: 12, spa: 252, spd: 0, spe: 244 }}),
    new Pokemon("Breloom", { nature: "Jolly", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Rotom-Wash", { nature: "Modest", item: "Choice Scarf", evs: { hp: 252, atk: 0, def: 4, spa: 244, spd: 4, spe: 4 }}),
    new Pokemon("Tsareena", { nature: "Jolly", item: "Wide Lens", evs: { hp: 52, atk: 252, def: 0, spa: 0, spd: 0, spe: 204 }}),
    new Pokemon("Samurott-Hisui", { nature: "Adamant", item: "Life Orb", evs: { hp: 28, atk: 252, def: 4, spa: 0, spd: 4, spe: 220 }}),
    new Pokemon("Brambleghast", { nature: "Adamant", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Slaking", { nature: "Adamant", item: "Life Orb", evs: { hp: 0, atk: 252, def: 4, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Braviary-Hisui", { nature: "Modest", item: "Life Orb", evs: { hp: 4, atk: 0, def: 4, spa: 252, spd: 4, spe: 244 }}),
    new Pokemon("Skeledirge", { nature: "Modest", item: "Leftovers", evs: { hp: 252, atk: 0, def: 108, spa: 4, spd: 132, spe: 12 }}),
    new Pokemon("Araquanid", { nature: "Brave", item: "Clear Amulet", evs: { hp: 252, atk: 252, def: 0, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Mamoswine", { nature: "Adamant", item: "Choice Scarf", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Azumarill", { nature: "Adamant", item: "Sitrus Berry", evs: { hp: 244, atk: 252, def: 0, spa: 0, spd: 12, spe: 0 }}),
    new Pokemon("Toedscruel", { nature: "Timid", item: "Covert Cloak", evs: { hp: 196, atk: 0, def: 60, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Gardevoir", { nature: "Modest", item: "Choice Scarf", evs: { hp: 244, atk: 0, def: 84, spa: 36, spd: 4, spe: 140 }}),
    new Pokemon("Braviary", { nature: "Adamant", item: "Psychic Seed", evs: { hp: 12, atk: 252, def: 0, spa: 0, spd: 0, spe: 244 }}),
    new Pokemon("Flamigo", { nature: "Adamant", item: "Focus Sash", evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 }}),
    new Pokemon("Vivillon", { nature: "Timid", item: "Focus Sash", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Salazzle", { nature: "Timid", item: "Focus Sash", evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 }}),
    new Pokemon("Goodra-Hisui", { nature: "Modest", item: "Leftovers", evs: { hp: 252, atk: 0, def: 20, spa: 236, spd: 0, spe: 0 }}),
    new Pokemon("Kingdra", { nature: "Timid", item: "Life Orb", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Arcanine", { nature: "Jolly", item: "Safety Goggles", evs: { hp: 244, atk: 36, def: 4, spa: 0, spd: 4, spe: 220 }}),
    new Pokemon("Klefki", { nature: "Calm", item: "Light Clay", evs: { hp: 252, atk: 0, def: 148, spa: 4, spd: 100, spe: 4 }}),
    new Pokemon("Ludicolo", { nature: "Modest", item: "Life Orb", evs: { hp: 12, atk: 0, def: 4, spa: 252, spd: 4, spe: 236 }}),
    new Pokemon("Rotom-Heat", { nature: "Modest", item: "Choice Scarf", evs: { hp: 252, atk: 0, def: 20, spa: 36, spd: 20, spe: 180 }}),
    new Pokemon("Bronzong", { nature: "Relaxed", item: "Safety Goggles", evs: { hp: 252, atk: 0, def: 148, spa: 0, spd: 108, spe: 0 }}),
    new Pokemon("Chesnaught", { nature: "Adamant", item: "Sitrus Berry", evs: { hp: 228, atk: 100, def: 28, spa: 0, spd: 108, spe: 44 }}),
    new Pokemon("Ceruledge", { nature: "Adamant", item: "Clear Amulet", evs: { hp: 204, atk: 36, def: 108, spa: 0, spd: 44, spe: 116 }}),
    new Pokemon("Raichu", { nature: "Timid", item: "Focus Sash", evs: { hp: 0, atk: 0, def: 4, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Charizard", { nature: "Timid", item: "Choice Scarf", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Sableye", { nature: "Careful", item: "Eject Button", evs: { hp: 252, atk: 0, def: 148, spa: 0, spd: 104, spe: 0 }}),
    new Pokemon("Conkeldurr", { nature: "Brave", item: "Flame Orb", evs: { hp: 252, atk: 252, def: 0, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Oranguru", { nature: "Sassy", item: "Mental Herb", evs: { hp: 252, atk: 0, def: 180, spa: 0, spd: 76, spe: 0 }}),
    new Pokemon("Houndstone", { nature: "Impish", item: "Safety Goggles", evs: { hp: 252, atk: 4, def: 252, spa: 0, spd: 0, spe: 0 }}),
    new Pokemon("Ribombee", { nature: "Timid", item: "Focus Sash", evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 }}),
    new Pokemon("Empoleon", { nature: "Modest", item: "Leftovers", evs: { hp: 252, atk: 0, def: 0, spa: 252, spd: 4, spe: 0 }}),
    new Pokemon("Hydrapple", { nature: "Quiet", item: "Assault Vest", evs: { hp: 252, atk: 0, def: 0, spa: 252, spd: 4, spe: 0 }}),
    new Pokemon("Glaceon", { nature: "Modest", item: "Choice Specs", evs: { hp: 244, atk: 0, def: 0, spa: 252, spd: 12, spe: 0 }}),
    new Pokemon("Altaria", { nature: "Careful", item: "Safety Goggles", evs: { hp: 244, atk: 0, def: 228, spa: 0, spd: 36, spe: 0 }}),
    new Pokemon("Metagross", { nature: "Adamant", item: "Assault Vest", evs: { hp: 252, atk: 196, def: 4, spa: 0, spd: 44, spe: 12 }}),
    new Pokemon("Illumise", { nature: "Timid", item: "Covert Cloak", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Serperior", { nature: "Timid", item: "Choice Scarf", evs: { hp: 244, atk: 0, def: 4, spa: 4, spd: 4, spe: 252 }}),
    new Pokemon("Magnezone", { nature: "Modest", item: "Choice Scarf", evs: { hp: 252, atk: 0, def: 0, spa: 252, spd: 4, spe: 0 }}),
    new Pokemon("Malamar", { nature: "Brave", item: "Safety Goggles", evs: { hp: 252, atk: 252, def: 0, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Hariyama", { nature: "Brave", item: "Flame Orb", evs: { hp: 252, atk: 252, def: 0, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Kleavor", { nature: "Adamant", item: "Choice Scarf", evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 }}),
    new Pokemon("Tinkaton", { nature: "Jolly", item: "Sitrus Berry", evs: { hp: 252, atk: 4, def: 52, spa: 0, spd: 4, spe: 196 }}),
    new Pokemon("Espeon", { nature: "Modest", item: "Choice Specs", evs: { hp: 36, atk: 0, def: 12, spa: 236, spd: 4, spe: 220 }}),
    new Pokemon("Comfey", { nature: "Calm", item: "Sitrus Berry", evs: { hp: 188, atk: 0, def: 156, spa: 4, spd: 76, spe: 84 }}),
    new Pokemon("Quaquaval", { nature: "Jolly", item: "Choice Scarf", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Alcremie", { nature: "Quiet", item: "Covert Cloak", evs: { hp: 252, atk: 0, def: 116, spa: 140, spd: 0, spe: 0 }}),
    new Pokemon("Mandibuzz", { nature: "Calm", item: "Leftovers", evs: { hp: 252, atk: 0, def: 52, spa: 4, spd: 196, spe: 4 }}),
    new Pokemon("Toxicroak", { nature: "Adamant", item: "Clear Amulet", evs: { hp: 20, atk: 236, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Persian-Alola", { nature: "Timid", item: "Assault Vest", evs: { hp: 252, atk: 0, def: 100, spa: 4, spd: 84, spe: 68 }}),
    new Pokemon("Basculegion-F", { nature: "Modest", item: "Choice Scarf", evs: { hp: 0, atk: 0, def: 4, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Toxtricity", { nature: "Timid", item: "Choice Specs", evs: { hp: 252, atk: 0, def: 4, spa: 60, spd: 12, spe: 180 }}),
    new Pokemon("Venusaur", { nature: "Modest", item: "Covert Cloak", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Typhlosion", { nature: "Timid", item: "Choice Scarf", evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 }}),
    new Pokemon("Yanmega", { nature: "Timid", item: "Focus Sash", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Inteleon", { nature: "Timid", item: "Scope Lens", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Orthworm", { nature: "Impish", item: "Sitrus Berry", evs: { hp: 212, atk: 0, def: 36, spa: 0, spd: 252, spe: 4 }}),
    new Pokemon("Bellibolt", { nature: "Modest", item: "Assault Vest", evs: { hp: 252, atk: 0, def: 0, spa: 212, spd: 44, spe: 0 }}),
    new Pokemon("Porygon-Z", { nature: "Timid", item: "Choice Scarf", evs: { hp: 0, atk: 0, def: 4, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Scrafty", { nature: "Adamant", item: "Assault Vest", evs: { hp: 252, atk: 156, def: 60, spa: 0, spd: 36, spe: 0 }}),
    new Pokemon("Snorlax", { nature: "Brave", item: "Sitrus Berry", evs: { hp: 180, atk: 76, def: 252, spa: 0, spd: 0, spe: 0 }}),
    new Pokemon("Stonjourner", { nature: "Adamant", item: "Choice Scarf", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Bruxish", { nature: "Jolly", item: "Choice Scarf", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Vikavolt", { nature: "Modest", item: "Magnet", evs: { hp: 244, atk: 0, def: 0, spa: 252, spd: 12, spe: 0 }}),
    new Pokemon("Magmortar", { nature: "Modest", item: "Charcoal", evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 }}),
    new Pokemon("Oricorio-Sensu", { nature: "Modest", item: "Focus Sash", evs: { hp: 0, atk: 0, def: 4, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Weavile", { nature: "Jolly", item: "Focus Sash", evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 }}),
    new Pokemon("Perrserker", { nature: "Jolly", item: "Chople Berry", evs: { hp: 252, atk: 4, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Hitmontop", { nature: "Adamant", item: "Clear Amulet", evs: { hp: 252, atk: 252, def: 0, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Drednaw", { nature: "Adamant", item: "Choice Band", evs: { hp: 28, atk: 196, def: 4, spa: 0, spd: 28, spe: 252 }}),
    new Pokemon("Blastoise", { nature: "Modest", item: "Choice Scarf", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Staraptor", { nature: "Adamant", item: "Choice Scarf", evs: { hp: 164, atk: 252, def: 4, spa: 0, spd: 4, spe: 84 }}),
    new Pokemon("Infernape", { nature: "Modest", item: "Life Orb", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Scizor", { nature: "Adamant", item: "Clear Amulet", evs: { hp: 252, atk: 156, def: 4, spa: 0, spd: 28, spe: 68 }}),
    new Pokemon("Umbreon", { nature: "Bold", item: "Mirror Herb", evs: { hp: 252, atk: 0, def: 140, spa: 0, spd: 116, spe: 0 }}),
    new Pokemon("Slowbro-Galar", { nature: "Quiet", item: "Covert Cloak", evs: { hp: 252, atk: 0, def: 0, spa: 156, spd: 100, spe: 0 }}),
    new Pokemon("Rotom-Mow", { nature: "Modest", item: "Choice Scarf", evs: { hp: 60, atk: 0, def: 4, spa: 252, spd: 4, spe: 188 }}),
    new Pokemon("Greninja", { nature: "Timid", item: "Loaded Dice", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Frosmoth", { nature: "Modest", item: "Leftovers", evs: { hp: 12, atk: 0, def: 4, spa: 252, spd: 4, spe: 236 }}),
    new Pokemon("Torterra", { nature: "Adamant", item: "White Herb", evs: { hp: 68, atk: 252, def: 4, spa: 0, spd: 8, spe: 176 }}),
    new Pokemon("Duraludon", { nature: "Timid", item: "Eviolite", evs: { hp: 100, atk: 0, def: 0, spa: 0, spd: 156, spe: 252 }}),
    new Pokemon("Shiftry", { nature: "Adamant", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Muk-Alola", { nature: "Adamant", item: "Figy Berry", evs: { hp: 220, atk: 196, def: 52, spa: 0, spd: 4, spe: 36 }}),
    new Pokemon("Drifblim", { nature: "Timid", item: "Grassy Seed", evs: { hp: 4, atk: 0, def: 220, spa: 28, spd: 132, spe: 124 }}),
    new Pokemon("Krookodile", { nature: "Jolly", item: "Choice Scarf", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Abomasnow", { nature: "Modest", item: "Assault Vest", evs: { hp: 252, atk: 0, def: 0, spa: 252, spd: 4, spe: 0 }}),
    new Pokemon("Electrode-Hisui", { nature: "Timid", item: "Choice Specs", evs: { hp: 60, atk: 0, def: 0, spa: 252, spd: 0, spe: 196 }}),
    new Pokemon("Cinderace", { nature: "Jolly", item: "Choice Scarf", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Jolteon", { nature: "Timid", item: "Focus Sash", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Espathra", { nature: "Modest", item: "Focus Sash", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Lapras", { nature: "Calm", item: "Leftovers", evs: { hp: 252, atk: 0, def: 196, spa: 4, spd: 52, spe: 4 }}),
    new Pokemon("Cetitan", { nature: "Adamant", item: "Sitrus Berry", evs: { hp: 4, atk: 52, def: 164, spa: 0, spd: 164, spe: 124 }}),
    new Pokemon("Hawlucha", { nature: "Adamant", item: "Grassy Seed", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Barraskewda", { nature: "Adamant", item: "Choice Band", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Jumpluff", { nature: "Jolly", item: "Covert Cloak", evs: { hp: 252, atk: 4, def: 84, spa: 0, spd: 4, spe: 164 }}),
    new Pokemon("Noivern", { nature: "Timid", item: "Focus Sash", evs: { hp: 0, atk: 0, def: 4, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Slowking", { nature: "Sassy", item: "Sitrus Berry", evs: { hp: 236, atk: 0, def: 196, spa: 0, spd: 76, spe: 0 }}),
    new Pokemon("Reuniclus", { nature: "Quiet", item: "Life Orb", evs: { hp: 124, atk: 0, def: 92, spa: 244, spd: 44, spe: 0 }}),
    new Pokemon("Dachsbun", { nature: "Calm", item: "Leftovers", evs: { hp: 252, atk: 0, def: 4, spa: 0, spd: 252, spe: 0 }}),
    new Pokemon("Lucario", { nature: "Adamant", item: "Choice Scarf", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Hippowdon", { nature: "Impish", item: "Rocky Helmet", evs: { hp: 252, atk: 0, def: 92, spa: 0, spd: 164, spe: 0 }}),
    new Pokemon("Eelektross", { nature: "Modest", item: "Assault Vest", evs: { hp: 152, atk: 0, def: 0, spa: 252, spd: 104, spe: 0 }}),
    new Pokemon("Lilligant", { nature: "Modest", item: "Focus Sash", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Sceptile", { nature: "Timid", item: "Focus Sash", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Froslass", { nature: "Timid", item: "Focus Sash", evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 }}),
    new Pokemon("Pachirisu", { nature: "Bold", item: "Sitrus Berry", evs: { hp: 252, atk: 0, def: 156, spa: 0, spd: 100, spe: 0 }}),
    new Pokemon("Rabsca", { nature: "Quiet", item: "Covert Cloak", evs: { hp: 228, atk: 0, def: 84, spa: 196, spd: 0, spe: 0 }}),
    new Pokemon("Cyclizar", { nature: "Jolly", item: "Covert Cloak", evs: { hp: 252, atk: 4, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Arboliva", { nature: "Relaxed", item: "Leftovers", evs: { hp: 180, atk: 0, def: 156, spa: 0, spd: 172, spe: 0 }}),
    new Pokemon("Toxapex", { nature: "Bold", item: "Binding Band", evs: { hp: 252, atk: 0, def: 140, spa: 0, spd: 116, spe: 0 }}),
    new Pokemon("Electivire", { nature: "Adamant", item: "Clear Amulet", evs: { hp: 68, atk: 252, def: 4, spa: 0, spd: 4, spe: 180 }}),
    new Pokemon("Slowking-Galar", { nature: "Sassy", item: "Sitrus Berry", evs: { hp: 252, atk: 0, def: 12, spa: 0, spd: 240, spe: 0 }}),
    new Pokemon("Oricorio-Pom-Pom", { nature: "Timid", item: "Focus Sash", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Mudsdale", { nature: "Adamant", item: "Assault Vest", evs: { hp: 252, atk: 36, def: 76, spa: 0, spd: 140, spe: 4 }}),
    new Pokemon("Coalossal", { nature: "Relaxed", item: "Leftovers", evs: { hp: 180, atk: 0, def: 156, spa: 0, spd: 172, spe: 0 }}),
    new Pokemon("Gliscor", { nature: "Careful", item: "Toxic Orb", evs: { hp: 212, atk: 4, def: 4, spa: 0, spd: 252, spe: 36 }}),
    new Pokemon("Houndoom", { nature: "Timid", item: "Safety Goggles", evs: { hp: 76, atk: 0, def: 4, spa: 196, spd: 4, spe: 228 }}),
    new Pokemon("Exeggutor", { nature: "Timid", item: "Focus Sash", evs: { hp: 0, atk: 0, def: 4, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Trevenant", { nature: "Adamant", item: "Sitrus Berry", evs: { hp: 252, atk: 76, def: 116, spa: 0, spd: 60, spe: 4 }}),
    new Pokemon("Grumpig", { nature: "Bold", item: "Aguav Berry", evs: { hp: 236, atk: 0, def: 116, spa: 0, spd: 156, spe: 0 }}),
    new Pokemon("Poliwrath", { nature: "Adamant", item: "Sitrus Berry", evs: { hp: 100, atk: 196, def: 36, spa: 0, spd: 36, spe: 140 }}),
    new Pokemon("Vaporeon", { nature: "Bold", item: "Leftovers", evs: { hp: 252, atk: 0, def: 252, spa: 4, spd: 0, spe: 0 }}),
    new Pokemon("Swampert", { nature: "Quiet", item: "Safety Goggles", evs: { hp: 252, atk: 0, def: 0, spa: 196, spd: 60, spe: 0 }}),
    new Pokemon("Lokix", { nature: "Adamant", item: "Life Orb", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Rampardos", { nature: "Brave", item: "Life Orb", evs: { hp: 0, atk: 252, def: 84, spa: 0, spd: 168, spe: 0 }}),
    new Pokemon("Cloyster", { nature: "Adamant", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Golurk", { nature: "Brave", item: "Assault Vest", evs: { hp: 60, atk: 156, def: 36, spa: 4, spd: 252, spe: 0 }}),
    new Pokemon("Meowstic", { nature: "Calm", item: "Light Clay", evs: { hp: 252, atk: 0, def: 108, spa: 4, spd: 140, spe: 4 }}),
    new Pokemon("Arbok", { nature: "Adamant", item: "Clear Amulet", evs: { hp: 252, atk: 252, def: 4, spa: 0, spd: 0, spe: 0 }}),
    new Pokemon("Dewgong", { nature: "Sassy", item: "Covert Cloak", evs: { hp: 252, atk: 0, def: 220, spa: 0, spd: 36, spe: 0 }}),
    new Pokemon("Dragalge", { nature: "Modest", item: "Assault Vest", evs: { hp: 232, atk: 0, def: 20, spa: 252, spd: 0, spe: 0 }}),
 ]  
}