import { Pokemon } from "../pokemon"

export function speedMeta(regulation: string): Pokemon[] {
  if(regulation == "Reg G") {
    return regG()
  } else {
    return regH()
  }
}

export function regG(): Pokemon[] {
  return [
    new Pokemon("Urshifu-Rapid-Strike", { ability: "Unseen Fist", nature: "Adamant", item: "Choice Scarf", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Rillaboom", { ability: "Grassy Surge", nature: "Adamant", item: "Assault Vest", evs: { hp: 140, atk: 116, def: 4, spa: 0, spd: 84, spe: 164 }}),
    new Pokemon("Raging Bolt", { ability: "Protosynthesis", nature: "Modest", item: "Booster Energy", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Incineroar", { ability: "Intimidate", nature: "Impish", item: "Safety Goggles", evs: { hp: 252, atk: 4, def: 188, spa: 0, spd: 60, spe: 4 }}),
    new Pokemon("Iron Hands", { ability: "Quark Drive", nature: "Adamant", item: "Assault Vest", evs: { hp: 52, atk: 76, def: 12, spa: 0, spd: 252, spe: 116 }}),
    new Pokemon("Calyrex-Shadow", { ability: "As One (Spectrier)", nature: "Timid", item: "Life Orb", evs: { hp: 0, atk: 0, def: 4, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Chi-Yu", { ability: "Beads of Ruin", nature: "Modest", item: "Choice Scarf", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Farigiraf", { ability: "Armor Tail", nature: "Bold", item: "Electric Seed", evs: { hp: 252, atk: 0, def: 164, spa: 0, spd: 92, spe: 0 }}),
    new Pokemon("Calyrex-Ice", { ability: "As One (Glastrier)", nature: "Brave", item: "Clear Amulet", evs: { hp: 244, atk: 164, def: 0, spa: 0, spd: 100, spe: 0 }}),
    new Pokemon("Flutter Mane", { ability: "Protosynthesis", nature: "Timid", item: "Booster Energy", evs: { hp: 228, atk: 0, def: 108, spa: 20, spd: 12, spe: 140 }}),
    new Pokemon("Ogerpon-Hearthflame", { ability: "Mold Breaker", nature: "Adamant", item: "Hearthflame Mask", evs: { hp: 236, atk: 84, def: 4, spa: 0, spd: 4, spe: 180 }}),
    new Pokemon("Whimsicott", { ability: "Prankster", nature: "Timid", item: "Covert Cloak", evs: { hp: 156, atk: 0, def: 0, spa: 0, spd: 204, spe: 148 }}),
    new Pokemon("Miraidon", { ability: "Hadron Engine", nature: "Timid", item: "Choice Specs", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Amoonguss", { ability: "Regenerator", nature: "Calm", item: "Rocky Helmet", evs: { hp: 236, atk: 0, def: 196, spa: 0, spd: 76, spe: 0 }}),
    new Pokemon("Ogerpon-Cornerstone", { ability: "Sturdy", nature: "Jolly", item: "Cornerstone Mask", evs: { hp: 0, atk: 252, def: 4, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Clefairy", { ability: "Friend Guard", nature: "Sassy", item: "Eviolite", evs: { hp: 252, atk: 0, def: 188, spa: 0, spd: 68, spe: 0 }}),
    new Pokemon("Tornadus", { ability: "Prankster", nature: "Timid", item: "Covert Cloak", evs: { hp: 220, atk: 0, def: 20, spa: 4, spd: 12, spe: 252 }}),
    new Pokemon("Terapagos", { ability: "Tera Shift", nature: "Bold", item: "Leftovers", evs: { hp: 172, atk: 0, def: 76, spa: 60, spd: 4, spe: 196 }}),
    new Pokemon("Chien-Pao", { ability: "Sword of Ruin", nature: "Jolly", item: "Focus Sash", evs: { hp: 0, atk: 252, def: 4, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Urshifu", { ability: "Unseen Fist", nature: "Adamant", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Indeedee-F", { ability: "Psychic Surge", nature: "Bold", item: "Rocky Helmet", evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Pelipper", { ability: "Drizzle", nature: "Modest", item: "Safety Goggles", evs: { hp: 252, atk: 0, def: 20, spa: 36, spd: 148, spe: 52 }}),
    new Pokemon("Zamazenta-Crowned", { ability: "Dauntless Shield", nature: "Impish", item: "Rusted Shield", evs: { hp: 156, atk: 0, def: 156, spa: 0, spd: 0, spe: 196 }}),
    new Pokemon("Dondozo", { ability: "Unaware", nature: "Impish", item: "Leftovers", evs: { hp: 4, atk: 4, def: 116, spa: 0, spd: 212, spe: 172 }}),
    new Pokemon("Tatsugiri", { ability: "Commander", nature: "Modest", item: "Focus Sash", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Weezing-Galar", { ability: "Neutralizing Gas", nature: "Bold", item: "Covert Cloak", evs: { hp: 252, atk: 0, def: 0, spa: 0, spd: 236, spe: 20 }}),
    new Pokemon("Grimmsnarl", { ability: "Prankster", nature: "Careful", item: "Light Clay", evs: { hp: 228, atk: 4, def: 204, spa: 0, spd: 68, spe: 4 }}),
    new Pokemon("Koraidon", { ability: "Orichalcum Pulse", nature: "Adamant", item: "Clear Amulet", evs: { hp: 252, atk: 196, def: 4, spa: 0, spd: 28, spe: 28 }}),
    new Pokemon("Ditto", { ability: "Imposter", nature: "Jolly", item: "Choice Scarf", evs: { hp: 252, atk: 0, def: 0, spa: 0, spd: 4, spe: 252 }}),
    new Pokemon("Landorus", { ability: "Sheer Force", nature: "Modest", item: "Choice Scarf", evs: { hp: 4, atk: 0, def: 4, spa: 244, spd: 4, spe: 252 }}),
    new Pokemon("Ursaluna-Bloodmoon", { ability: "Mind's Eye", nature: "Modest", item: "Life Orb", evs: { hp: 252, atk: 0, def: 4, spa: 252, spd: 0, spe: 0 }}),
    new Pokemon("Ursaluna", { ability: "Guts", nature: "Brave", item: "Flame Orb", evs: { hp: 140, atk: 236, def: 0, spa: 0, spd: 132, spe: 0 }}),
    new Pokemon("Groudon", { ability: "Drought", nature: "Adamant", item: "Clear Amulet", evs: { hp: 164, atk: 156, def: 4, spa: 0, spd: 4, spe: 180 }}),
    new Pokemon("Volcarona", { ability: "Flame Body", nature: "Timid", item: "Leftovers", evs: { hp: 252, atk: 0, def: 132, spa: 0, spd: 0, spe: 124 }}),
    new Pokemon("Kyogre", { ability: "Drizzle", nature: "Modest", item: "Choice Scarf", evs: { hp: 132, atk: 0, def: 140, spa: 68, spd: 12, spe: 156 }}),
    new Pokemon("Smeargle", { ability: "Moody", nature: "Jolly", item: "Focus Sash", evs: { hp: 252, atk: 0, def: 4, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Ogerpon", { ability: "Defiant", nature: "Adamant", item: "Loaded Dice", evs: { hp: 132, atk: 156, def: 4, spa: 0, spd: 4, spe: 212 }}),
    new Pokemon("Entei", { ability: "Inner Focus", nature: "Adamant", item: "Choice Band", evs: { hp: 12, atk: 244, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Iron Crown", { ability: "Quark Drive", nature: "Timid", item: "Life Orb", evs: { hp: 52, atk: 0, def: 20, spa: 252, spd: 4, spe: 180 }}),
    new Pokemon("Ogerpon-Wellspring", { ability: "Water Absorb", nature: "Impish", item: "Wellspring Mask", evs: { hp: 252, atk: 4, def: 220, spa: 0, spd: 12, spe: 20 }}),
    new Pokemon("Mienshao", { ability: "Inner Focus", nature: "Jolly", item: "Focus Sash", evs: { hp: 0, atk: 252, def: 4, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Iron Jugulis", { ability: "Quark Drive", nature: "Timid", item: "Booster Energy", evs: { hp: 92, atk: 0, def: 132, spa: 52, spd: 4, spe: 228 }}),
    new Pokemon("Latios", { ability: "Levitate", nature: "Timid", item: "Life Orb", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Tyranitar", { ability: "Sand Stream", nature: "Adamant", item: "Focus Sash", evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 }}),
    new Pokemon("Maushold", { ability: "Friend Guard", nature: "Impish", item: "Rocky Helmet", evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Iron Treads", { ability: "Quark Drive", nature: "Jolly", item: "Choice Band", evs: { hp: 12, atk: 252, def: 4, spa: 0, spd: 20, spe: 220 }}),
    new Pokemon("Porygon2", { ability: "Download", nature: "Sassy", item: "Eviolite", evs: { hp: 252, atk: 0, def: 140, spa: 0, spd: 116, spe: 0 }}),
    new Pokemon("Annihilape", { ability: "Defiant", nature: "Jolly", item: "Choice Scarf", evs: { hp: 252, atk: 4, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Venusaur", { ability: "Chlorophyll", nature: "Modest", item: "Covert Cloak", evs: { hp: 188, atk: 0, def: 4, spa: 76, spd: 4, spe: 236 }}),
    new Pokemon("Gholdengo", { ability: "Good as Gold", nature: "Modest", item: "Grassy Seed", evs: { hp: 244, atk: 0, def: 12, spa: 12, spd: 20, spe: 220 }}),
    new Pokemon("Scream Tail", { ability: "Protosynthesis", nature: "Timid", item: "Booster Energy", evs: { hp: 252, atk: 0, def: 4, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Kingambit", { ability: "Defiant", nature: "Adamant", item: "Lum Berry", evs: { hp: 252, atk: 100, def: 4, spa: 0, spd: 148, spe: 4 }}),
    new Pokemon("Lunala", { ability: "Shadow Shield", nature: "Modest", item: "Power Herb", evs: { hp: 220, atk: 0, def: 12, spa: 180, spd: 4, spe: 92 }}),
    new Pokemon("Roaring Moon", { ability: "Protosynthesis", nature: "Jolly", item: "Booster Energy", evs: { hp: 28, atk: 220, def: 4, spa: 0, spd: 4, spe: 252 }}),
    new Pokemon("Regidrago", { ability: "Dragon's Maw", nature: "Modest", item: "Life Orb", evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 68, spe: 188 }}),
    new Pokemon("Hitmontop", { ability: "Intimidate", nature: "Impish", item: "Rocky Helmet", evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Zacian-Crowned", { ability: "Intrepid Sword", nature: "Jolly", item: "Rusted Sword", evs: { hp: 76, atk: 252, def: 0, spa: 0, spd: 0, spe: 180 }}),
    new Pokemon("Okidogi", { ability: "Guard Dog", nature: "Adamant", item: "Assault Vest", evs: { hp: 124, atk: 252, def: 4, spa: 0, spd: 12, spe: 116 }}),
    new Pokemon("Tsareena", { ability: "Queenly Majesty", nature: "Adamant", item: "Wide Lens", evs: { hp: 36, atk: 236, def: 4, spa: 0, spd: 4, spe: 228 }}),
    new Pokemon("Talonflame", { ability: "Gale Wings", nature: "Adamant", item: "Life Orb", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Jumpluff", { ability: "Chlorophyll", nature: "Timid", item: "Covert Cloak", evs: { hp: 252, atk: 0, def: 4, spa: 36, spd: 84, spe: 108 }}),
    new Pokemon("Torkoal", { ability: "Drought", nature: "Quiet", item: "Choice Specs", evs: { hp: 252, atk: 0, def: 4, spa: 252, spd: 0, spe: 0 }}),
    new Pokemon("Dragonite", { ability: "Inner Focus", nature: "Adamant", item: "Choice Band", evs: { hp: 156, atk: 252, def: 4, spa: 0, spd: 4, spe: 92 }}),
    new Pokemon("Moltres-Galar", { ability: "Berserk", nature: "Calm", item: "Safety Goggles", evs: { hp: 244, atk: 0, def: 76, spa: 4, spd: 36, spe: 148 }}),
    new Pokemon("Comfey", { ability: "Triage", nature: "Calm", item: "Sitrus Berry", evs: { hp: 220, atk: 0, def: 172, spa: 12, spd: 76, spe: 28 }}),
    new Pokemon("Electabuzz", { ability: "Vital Spirit", nature: "Bold", item: "Eviolite", evs: { hp: 252, atk: 0, def: 180, spa: 0, spd: 76, spe: 0 }}),
    new Pokemon("Gallade", { ability: "Sharpness", nature: "Brave", item: "Clear Amulet", evs: { hp: 252, atk: 252, def: 4, spa: 0, spd: 0, spe: 0 }}),
    new Pokemon("Iron Leaves", { ability: "Quark Drive", nature: "Jolly", item: "Life Orb", evs: { hp: 92, atk: 156, def: 4, spa: 0, spd: 4, spe: 252 }}),
    new Pokemon("Lilligant-Hisui", { ability: "Chlorophyll", nature: "Jolly", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Necrozma-Dawn-Wings", { ability: "Prism Armor", nature: "Quiet", item: "Power Herb", evs: { hp: 252, atk: 0, def: 4, spa: 252, spd: 0, spe: 0 }}),
    new Pokemon("Snorlax", { ability: "Thick Fat", nature: "Impish", item: "Leftovers", evs: { hp: 140, atk: 116, def: 252, spa: 0, spd: 0, spe: 0 }}),
    new Pokemon("Archaludon", { ability: "Stamina", nature: "Modest", item: "Assault Vest", evs: { hp: 124, atk: 0, def: 12, spa: 196, spd: 116, spe: 60 }}),
    new Pokemon("Arcanine-Hisui", { ability: "Intimidate", nature: "Adamant", item: "Choice Band", evs: { hp: 180, atk: 196, def: 92, spa: 0, spd: 4, spe: 36 }}),
    new Pokemon("Tinkaton", { ability: "Mold Breaker", nature: "Jolly", item: "Iron Plate", evs: { hp: 204, atk: 252, def: 4, spa: 0, spd: 4, spe: 44 }}),
    new Pokemon("Iron Valiant", { ability: "Quark Drive", nature: "Jolly", item: "Booster Energy", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Regigigas", { ability: "Slow Start", nature: "Adamant", item: "Life Orb", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Ting-Lu", { ability: "Vessel of Ruin", nature: "Impish", item: "Rocky Helmet", evs: { hp: 228, atk: 4, def: 36, spa: 0, spd: 236, spe: 4 }}),
    new Pokemon("Regieleki", { ability: "Transistor", nature: "Modest", item: "Focus Sash", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Glimmora", { ability: "Toxic Debris", nature: "Bold", item: "Power Herb", evs: { hp: 252, atk: 0, def: 76, spa: 28, spd: 100, spe: 52 }}),
    new Pokemon("Cresselia", { ability: "Levitate", nature: "Bold", item: "Safety Goggles", evs: { hp: 244, atk: 0, def: 220, spa: 0, spd: 44, spe: 0 }}),
    new Pokemon("Basculegion", { ability: "Swift Swim", nature: "Adamant", item: "Choice Band", evs: { hp: 0, atk: 252, def: 4, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Brute Bonnet", { ability: "Protosynthesis", nature: "Impish", item: "Covert Cloak", evs: { hp: 252, atk: 4, def: 132, spa: 0, spd: 116, spe: 4 }}),
    new Pokemon("Armarouge", { ability: "Flash Fire", nature: "Quiet", item: "Life Orb", evs: { hp: 252, atk: 0, def: 0, spa: 252, spd: 4, spe: 0 }}),
    new Pokemon("Alcremie", { ability: "Sweet Veil", nature: "Quiet", item: "Iron Ball", evs: { hp: 252, atk: 0, def: 108, spa: 124, spd: 24, spe: 0 }}),
    new Pokemon("Registeel", { ability: "Clear Body", nature: "Impish", item: "Leftovers", evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Pyroar", { ability: "Unnerve", nature: "Timid", item: "Choice Specs", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Iron Boulder", { ability: "Quark Drive", nature: "Jolly", item: "Choice Band", evs: { hp: 92, atk: 252, def: 4, spa: 0, spd: 4, spe: 156 }}),
    new Pokemon("Araquanid", { ability: "Water Bubble", nature: "Adamant", item: "Covert Cloak", evs: { hp: 140, atk: 252, def: 108, spa: 0, spd: 4, spe: 4 }}),
    new Pokemon("Mamoswine", { ability: "Thick Fat", nature: "Adamant", item: "Assault Vest", evs: { hp: 4, atk: 252, def: 4, spa: 0, spd: 20, spe: 228 }}),
    new Pokemon("Gastrodon", { ability: "Storm Drain", nature: "Relaxed", item: "Leftovers", evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Thundurus", { ability: "Prankster", nature: "Bold", item: "Covert Cloak", evs: { hp: 252, atk: 0, def: 236, spa: 0, spd: 20, spe: 0 }}),
    new Pokemon("Goodra-Hisui", { ability: "Sap Sipper", nature: "Modest", item: "Leftovers", evs: { hp: 252, atk: 0, def: 148, spa: 4, spd: 92, spe: 12 }}),
    new Pokemon("Gothitelle", { ability: "Shadow Tag", nature: "Timid", item: "Sitrus Berry", evs: { hp: 252, atk: 0, def: 4, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Sneasler", { ability: "Unburden", nature: "Adamant", item: "Psychic Seed", evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 }}),
    new Pokemon("Skeledirge", { ability: "Unaware", nature: "Modest", item: "Safety Goggles", evs: { hp: 228, atk: 0, def: 100, spa: 76, spd: 92, spe: 12 }}),
    new Pokemon("Klefki", { ability: "Prankster", nature: "Calm", item: "Light Clay", evs: { hp: 252, atk: 0, def: 148, spa: 4, spd: 100, spe: 4 }}),
    new Pokemon("Sableye", { ability: "Prankster", nature: "Timid", item: "Focus Sash", evs: { hp: 12, atk: 0, def: 244, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Alomomola", { ability: "Regenerator", nature: "Sassy", item: "Rocky Helmet", evs: { hp: 68, atk: 4, def: 180, spa: 4, spd: 252, spe: 0 }}),
    new Pokemon("Umbreon", { ability: "Inner Focus", nature: "Calm", item: "Safety Goggles", evs: { hp: 244, atk: 0, def: 228, spa: 0, spd: 36, spe: 0 }}),
    new Pokemon("Chandelure", { ability: "Flash Fire", nature: "Modest", item: "Life Orb", evs: { hp: 188, atk: 0, def: 4, spa: 196, spd: 100, spe: 20 }}),
    new Pokemon("Walking Wake", { ability: "Protosynthesis", nature: "Timid", item: "Choice Scarf", evs: { hp: 4, atk: 0, def: 4, spa: 244, spd: 4, spe: 252 }}),
    new Pokemon("Heatran", { ability: "Flash Fire", nature: "Modest", item: "Assault Vest", evs: { hp: 236, atk: 0, def: 4, spa: 236, spd: 12, spe: 20 }}),
    new Pokemon("Cobalion", { ability: "Justified", nature: "Bold", item: "Grassy Seed", evs: { hp: 252, atk: 0, def: 156, spa: 4, spd: 4, spe: 92 }}),
    new Pokemon("Hydreigon", { ability: "Levitate", nature: "Modest", item: "Covert Cloak", evs: { hp: 212, atk: 0, def: 4, spa: 36, spd: 4, spe: 252 }}),
    new Pokemon("Iron Bundle", { ability: "Quark Drive", nature: "Timid", item: "Focus Sash", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Mimikyu", { ability: "Disguise", nature: "Adamant", item: "Life Orb", evs: { hp: 228, atk: 252, def: 28, spa: 0, spd: 0, spe: 0 }}),
    new Pokemon("Wo-Chien", { ability: "Tablets of Ruin", nature: "Bold", item: "Leftovers", evs: { hp: 252, atk: 0, def: 44, spa: 4, spd: 20, spe: 188 }}),
    new Pokemon("Rhyperior", { ability: "Lightning Rod", nature: "Adamant", item: "Assault Vest", evs: { hp: 172, atk: 236, def: 0, spa: 0, spd: 0, spe: 100 }}),
    new Pokemon("Bronzong", { ability: "Levitate", nature: "Impish", item: "Electric Seed", evs: { hp: 252, atk: 0, def: 188, spa: 0, spd: 68, spe: 0 }}),
    new Pokemon("Rayquaza", { ability: "Air Lock", nature: "Adamant", item: "Clear Amulet", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Flamigo", { ability: "Scrappy", nature: "Jolly", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Toxapex", { ability: "Regenerator", nature: "Calm", item: "Leftovers", evs: { hp: 244, atk: 0, def: 116, spa: 0, spd: 148, spe: 0 }}),
    new Pokemon("Landorus-Therian", { ability: "Intimidate", nature: "Adamant", item: "Choice Scarf", evs: { hp: 252, atk: 4, def: 0, spa: 0, spd: 252, spe: 0 }}),
    new Pokemon("Altaria", { ability: "Cloud Nine", nature: "Calm", item: "Mental Herb", evs: { hp: 252, atk: 0, def: 12, spa: 4, spd: 116, spe: 124 }}),
    new Pokemon("Gouging Fire", { ability: "Protosynthesis", nature: "Jolly", item: "Booster Energy", evs: { hp: 84, atk: 164, def: 4, spa: 0, spd: 4, spe: 252 }}),
    new Pokemon("Dragapult", { ability: "Clear Body", nature: "Jolly", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Primarina", { ability: "Liquid Voice", nature: "Modest", item: "Throat Spray", evs: { hp: 252, atk: 0, def: 140, spa: 108, spd: 4, spe: 4 }}),
    new Pokemon("Ninetales-Alola", { ability: "Snow Warning", nature: "Timid", item: "Light Clay", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Sandy Shocks", { ability: "Protosynthesis", nature: "Timid", item: "Booster Energy", evs: { hp: 44, atk: 0, def: 4, spa: 204, spd: 4, spe: 252 }}),
    new Pokemon("Eternatus", { ability: "Pressure", nature: "Modest", item: "Life Orb", evs: { hp: 28, atk: 0, def: 0, spa: 236, spd: 0, spe: 244 }}),
    new Pokemon("Ceruledge", { ability: "Flash Fire", nature: "Adamant", item: "Clear Amulet", evs: { hp: 252, atk: 116, def: 12, spa: 0, spd: 52, spe: 76 }}),
    new Pokemon("Dugtrio", { ability: "Arena Trap", nature: "Jolly", item: "Focus Sash", evs: { hp: 0, atk: 252, def: 4, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Typhlosion-Hisui", { ability: "Blaze", nature: "Timid", item: "Choice Scarf", evs: { hp: 28, atk: 0, def: 4, spa: 252, spd: 4, spe: 220 }}),
    new Pokemon("Kommo-o", { ability: "Overcoat", nature: "Impish", item: "Leftovers", evs: { hp: 252, atk: 4, def: 156, spa: 0, spd: 92, spe: 4 }}),
    new Pokemon("Hariyama", { ability: "Thick Fat", nature: "Adamant", item: "Ability Shield", evs: { hp: 0, atk: 164, def: 252, spa: 0, spd: 92, spe: 0 }}),
    new Pokemon("Milotic", { ability: "Competitive", nature: "Calm", item: "Leftovers", evs: { hp: 180, atk: 0, def: 156, spa: 108, spd: 36, spe: 28 }}),
    new Pokemon("Carbink", { ability: "Clear Body", nature: "Quiet", item: "Power Herb", evs: { hp: 252, atk: 0, def: 0, spa: 252, spd: 0, spe: 0 }}),
    new Pokemon("Oranguru", { ability: "Symbiosis", nature: "Timid", item: "Covert Cloak", evs: { hp: 252, atk: 0, def: 0, spa: 0, spd: 4, spe: 252 }}),
    new Pokemon("Mandibuzz", { ability: "Overcoat", nature: "Bold", item: "Rocky Helmet", evs: { hp: 212, atk: 0, def: 116, spa: 0, spd: 180, spe: 0 }}),
    new Pokemon("Kyurem-White", { ability: "Turboblaze", nature: "Modest", item: "Choice Specs", evs: { hp: 132, atk: 0, def: 12, spa: 252, spd: 4, spe: 108 }}),
    new Pokemon("Raichu", { ability: "Lightning Rod", nature: "Timid", item: "Assault Vest", evs: { hp: 84, atk: 0, def: 180, spa: 4, spd: 60, spe: 180 }}),
    new Pokemon("Sinistcha", { ability: "Hospitality", nature: "Bold", item: "Rocky Helmet", evs: { hp: 252, atk: 0, def: 132, spa: 0, spd: 124, spe: 0 }}),
    new Pokemon("Hatterene", { ability: "Magic Bounce", nature: "Quiet", item: "Life Orb", evs: { hp: 140, atk: 0, def: 0, spa: 252, spd: 116, spe: 0 }}),
    new Pokemon("Magmar", { ability: "Vital Spirit", nature: "Bold", item: "Eviolite", evs: { hp: 252, atk: 0, def: 212, spa: 4, spd: 36, spe: 4 }}),
    new Pokemon("Electivire", { ability: "Motor Drive", nature: "Calm", item: "Leftovers", evs: { hp: 252, atk: 0, def: 0, spa: 4, spd: 252, spe: 0 }}),
    new Pokemon("Ludicolo", { ability: "Swift Swim", nature: "Modest", item: "Choice Specs", evs: { hp: 52, atk: 0, def: 0, spa: 236, spd: 0, spe: 220 }}),
    new Pokemon("Trevenant", { ability: "Harvest", nature: "Sassy", item: "Sitrus Berry", evs: { hp: 252, atk: 4, def: 0, spa: 0, spd: 252, spe: 0 }}),
 ]  
}

export function regH(): Pokemon[] {
  return [
    new Pokemon("Gholdengo", { ability: "Good as Gold", nature: "Timid", item: "Choice Scarf", evs: { hp: 4, atk: 0, def: 4, spa: 244, spd: 4, spe: 252 }}),
    new Pokemon("Rillaboom", { ability: "Grassy Surge", nature: "Adamant", item: "Assault Vest", evs: { hp: 252, atk: 116, def: 4, spa: 0, spd: 60, spe: 76 }}),
    new Pokemon("Incineroar", { ability: "Intimidate", nature: "Adamant", item: "Safety Goggles", evs: { hp: 228, atk: 36, def: 4, spa: 0, spd: 36, spe: 204 }}),
    new Pokemon("Amoonguss", { ability: "Regenerator", nature: "Bold", item: "Sitrus Berry", evs: { hp: 236, atk: 0, def: 156, spa: 0, spd: 116, spe: 0 }}),
    new Pokemon("Archaludon", { ability: "Stamina", nature: "Timid", item: "Assault Vest", evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 }}),
    new Pokemon("Kingambit", { ability: "Defiant", nature: "Adamant", item: "Black Glasses", evs: { hp: 252, atk: 252, def: 0, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Pelipper", { ability: "Drizzle", nature: "Modest", item: "Focus Sash", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Volcarona", { ability: "Flame Body", nature: "Modest", item: "Leftovers", evs: { hp: 252, atk: 0, def: 60, spa: 36, spd: 4, spe: 156 }}),
    new Pokemon("Ursaluna-Bloodmoon", { ability: "Mind's Eye", nature: "Modest", item: "Life Orb", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Glimmora", { ability: "Toxic Debris", nature: "Timid", item: "Power Herb", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Dondozo", { ability: "Unaware", nature: "Jolly", item: "Leftovers", evs: { hp: 4, atk: 252, def: 4, spa: 0, spd: 36, spe: 212 }}),
    new Pokemon("Basculegion", { ability: "Swift Swim", nature: "Adamant", item: "Choice Scarf", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Tatsugiri", { ability: "Commander", nature: "Timid", item: "Choice Scarf", evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 }}),
    new Pokemon("Primarina", { ability: "Liquid Voice", nature: "Modest", item: "Throat Spray", evs: { hp: 236, atk: 0, def: 4, spa: 188, spd: 4, spe: 76 }}),
    new Pokemon("Whimsicott", { ability: "Prankster", nature: "Timid", item: "Covert Cloak", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Maushold", { ability: "Friend Guard", nature: "Jolly", item: "Safety Goggles", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Talonflame", { ability: "Gale Wings", nature: "Jolly", item: "Covert Cloak", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Dragonite", { ability: "Inner Focus", nature: "Adamant", item: "Choice Band", evs: { hp: 244, atk: 252, def: 4, spa: 0, spd: 4, spe: 4 }}),
    new Pokemon("Annihilape", { ability: "Defiant", nature: "Jolly", item: "Choice Scarf", evs: { hp: 252, atk: 4, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Indeedee-F", { ability: "Psychic Surge", nature: "Relaxed", item: "Psychic Seed", evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Dragapult", { ability: "Clear Body", nature: "Adamant", item: "Choice Band", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Clefable", { ability: "Unaware", nature: "Calm", item: "Sitrus Berry", evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Tyranitar", { ability: "Sand Stream", nature: "Adamant", item: "Assault Vest", evs: { hp: 164, atk: 252, def: 4, spa: 4, spd: 0, spe: 84 }}),
    new Pokemon("Hydreigon", { ability: "Levitate", nature: "Timid", item: "Life Orb", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Ursaluna", { ability: "Guts", nature: "Brave", item: "Flame Orb", evs: { hp: 252, atk: 252, def: 0, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Pawmot", { ability: "Natural Cure", nature: "Jolly", item: "Focus Sash", evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 }}),
    new Pokemon("Torkoal", { ability: "Drought", nature: "Quiet", item: "Charcoal", evs: { hp: 252, atk: 0, def: 0, spa: 252, spd: 4, spe: 0 }}),
    new Pokemon("Palafin", { ability: "Zero to Hero", nature: "Adamant", item: "Mystic Water", evs: { hp: 252, atk: 252, def: 0, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Farigiraf", { ability: "Armor Tail", nature: "Modest", item: "Throat Spray", evs: { hp: 236, atk: 0, def: 4, spa: 236, spd: 4, spe: 28 }}),
    new Pokemon("Gallade", { ability: "Sharpness", nature: "Brave", item: "Clear Amulet", evs: { hp: 252, atk: 252, def: 4, spa: 0, spd: 0, spe: 0 }}),
    new Pokemon("Murkrow", { ability: "Prankster", nature: "Calm", item: "Eviolite", evs: { hp: 252, atk: 0, def: 44, spa: 0, spd: 212, spe: 0 }}),
    new Pokemon("Armarouge", { ability: "Flash Fire", nature: "Quiet", item: "Life Orb", evs: { hp: 228, atk: 0, def: 0, spa: 252, spd: 28, spe: 0 }}),
    new Pokemon("Tauros-Paldea-Aqua", { ability: "Intimidate", nature: "Adamant", item: "Mirror Herb", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Typhlosion-Hisui", { ability: "Blaze", nature: "Timid", item: "Choice Scarf", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Porygon2", { ability: "Download", nature: "Quiet", item: "Eviolite", evs: { hp: 252, atk: 4, def: 124, spa: 92, spd: 36, spe: 0 }}),
    new Pokemon("Garchomp", { ability: "Rough Skin", nature: "Jolly", item: "Choice Scarf", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Meowscarada", { ability: "Overgrow", nature: "Jolly", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Gastrodon", { ability: "Storm Drain", nature: "Calm", item: "Sitrus Berry", evs: { hp: 252, atk: 0, def: 52, spa: 0, spd: 204, spe: 0 }}),
    new Pokemon("Lilligant-Hisui", { ability: "Chlorophyll", nature: "Jolly", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Hatterene", { ability: "Magic Bounce", nature: "Quiet", item: "Life Orb", evs: { hp: 212, atk: 0, def: 44, spa: 252, spd: 0, spe: 0 }}),
    new Pokemon("Kommo-o", { ability: "Overcoat", nature: "Impish", item: "Leftovers", evs: { hp: 76, atk: 4, def: 196, spa: 0, spd: 28, spe: 204 }}),
    new Pokemon("Grimmsnarl", { ability: "Prankster", nature: "Impish", item: "Light Clay", evs: { hp: 252, atk: 0, def: 68, spa: 0, spd: 188, spe: 0 }}),
    new Pokemon("Electabuzz", { ability: "Vital Spirit", nature: "Bold", item: "Eviolite", evs: { hp: 252, atk: 0, def: 212, spa: 4, spd: 4, spe: 36 }}),
    new Pokemon("Baxcalibur", { ability: "Thermal Exchange", nature: "Adamant", item: "Clear Amulet", evs: { hp: 140, atk: 196, def: 0, spa: 0, spd: 0, spe: 172 }}),
    new Pokemon("Arcanine-Hisui", { ability: "Intimidate", nature: "Jolly", item: "Choice Band", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Tauros-Paldea-Blaze", { ability: "Intimidate", nature: "Jolly", item: "Safety Goggles", evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 }}),
    new Pokemon("Sinistcha", { ability: "Hospitality", nature: "Calm", item: "Rocky Helmet", evs: { hp: 252, atk: 0, def: 92, spa: 4, spd: 156, spe: 4 }}),
    new Pokemon("Salamence", { ability: "Intimidate", nature: "Timid", item: "Choice Scarf", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Sneasler", { ability: "Poison Touch", nature: "Jolly", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Garganacl", { ability: "Purifying Salt", nature: "Careful", item: "Leftovers", evs: { hp: 252, atk: 0, def: 4, spa: 0, spd: 252, spe: 0 }}),
    new Pokemon("Ninetales-Alola", { ability: "Snow Warning", nature: "Timid", item: "Light Clay", evs: { hp: 252, atk: 0, def: 0, spa: 4, spd: 0, spe: 252 }}),
    new Pokemon("Sylveon", { ability: "Pixilate", nature: "Modest", item: "Throat Spray", evs: { hp: 60, atk: 0, def: 0, spa: 252, spd: 0, spe: 196 }}),
    new Pokemon("Decidueye-Hisui", { ability: "Scrappy", nature: "Adamant", item: "Razor Claw", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Gyarados", { ability: "Intimidate", nature: "Impish", item: "Sitrus Berry", evs: { hp: 236, atk: 4, def: 172, spa: 0, spd: 76, spe: 20 }}),
    new Pokemon("Gengar", { ability: "Cursed Body", nature: "Timid", item: "Focus Sash", evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 }}),
    new Pokemon("Clefairy", { ability: "Friend Guard", nature: "Sassy", item: "Eviolite", evs: { hp: 252, atk: 0, def: 220, spa: 0, spd: 36, spe: 0 }}),
    new Pokemon("Mimikyu", { ability: "Disguise", nature: "Adamant", item: "Life Orb", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Excadrill", { ability: "Sand Rush", nature: "Adamant", item: "Clear Amulet", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Blaziken", { ability: "Speed Boost", nature: "Adamant", item: "Clear Amulet", evs: { hp: 4, atk: 252, def: 4, spa: 0, spd: 4, spe: 244 }}),
    new Pokemon("Politoed", { ability: "Drizzle", nature: "Bold", item: "Sitrus Berry", evs: { hp: 252, atk: 0, def: 164, spa: 12, spd: 76, spe: 4 }}),
    new Pokemon("Smeargle", { ability: "Moody", nature: "Relaxed", item: "Focus Sash", evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Lycanroc", { ability: "Sand Rush", nature: "Jolly", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Zoroark-Hisui", { ability: "Illusion", nature: "Modest", item: "Choice Specs", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Corviknight", { ability: "Mirror Armor", nature: "Adamant", item: "Sitrus Berry", evs: { hp: 252, atk: 84, def: 4, spa: 0, spd: 92, spe: 76 }}),
    new Pokemon("Dusclops", { ability: "Pressure", nature: "Sassy", item: "Eviolite", evs: { hp: 252, atk: 0, def: 156, spa: 0, spd: 100, spe: 0 }}),
    new Pokemon("Weezing", { ability: "Neutralizing Gas", nature: "Bold", item: "Covert Cloak", evs: { hp: 252, atk: 0, def: 0, spa: 0, spd: 236, spe: 20 }}),
    new Pokemon("Magmar", { ability: "Vital Spirit", nature: "Calm", item: "Eviolite", evs: { hp: 252, atk: 0, def: 212, spa: 4, spd: 36, spe: 4 }}),
    new Pokemon("Gothitelle", { ability: "Shadow Tag", nature: "Careful", item: "Sitrus Berry", evs: { hp: 244, atk: 0, def: 228, spa: 0, spd: 36, spe: 0 }}),
    new Pokemon("Ninetales", { ability: "Drought", nature: "Timid", item: "Life Orb", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Weezing-Galar", { ability: "Neutralizing Gas", nature: "Modest", item: "Choice Specs", evs: { hp: 116, atk: 0, def: 4, spa: 196, spd: 100, spe: 92 }}),
    new Pokemon("Chandelure", { ability: "Flash Fire", nature: "Timid", item: "Choice Scarf", evs: { hp: 4, atk: 0, def: 4, spa: 252, spd: 4, spe: 244 }}),
    new Pokemon("Kilowattrel", { ability: "Competitive", nature: "Timid", item: "Focus Sash", evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 }}),
    new Pokemon("Overqwil", { ability: "Swift Swim", nature: "Adamant", item: "Life Orb", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Mienshao", { ability: "Inner Focus", nature: "Jolly", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Indeedee", { ability: "Psychic Surge", nature: "Modest", item: "Choice Scarf", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Milotic", { ability: "Competitive", nature: "Bold", item: "Leftovers", evs: { hp: 252, atk: 0, def: 204, spa: 4, spd: 4, spe: 44 }}),
    new Pokemon("Delphox", { ability: "Blaze", nature: "Timid", item: "Life Orb", evs: { hp: 0, atk: 0, def: 12, spa: 252, spd: 0, spe: 244 }}),
    new Pokemon("Breloom", { ability: "Technician", nature: "Jolly", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Rotom-Wash", { ability: "Levitate", nature: "Modest", item: "Choice Scarf", evs: { hp: 252, atk: 0, def: 4, spa: 244, spd: 4, spe: 4 }}),
    new Pokemon("Tsareena", { ability: "Queenly Majesty", nature: "Jolly", item: "Wide Lens", evs: { hp: 52, atk: 252, def: 0, spa: 0, spd: 0, spe: 204 }}),
    new Pokemon("Samurott-Hisui", { ability: "Sharpness", nature: "Adamant", item: "Life Orb", evs: { hp: 28, atk: 252, def: 4, spa: 0, spd: 4, spe: 220 }}),
    new Pokemon("Brambleghast", { ability: "Wind Rider", nature: "Adamant", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Slaking", { ability: "Truant", nature: "Adamant", item: "Life Orb", evs: { hp: 0, atk: 252, def: 4, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Braviary-Hisui", { ability: "Tinted Lens", nature: "Modest", item: "Life Orb", evs: { hp: 4, atk: 0, def: 4, spa: 252, spd: 4, spe: 244 }}),
    new Pokemon("Skeledirge", { ability: "Unaware", nature: "Modest", item: "Leftovers", evs: { hp: 252, atk: 0, def: 108, spa: 4, spd: 132, spe: 12 }}),
    new Pokemon("Araquanid", { ability: "Water Bubble", nature: "Brave", item: "Clear Amulet", evs: { hp: 252, atk: 252, def: 0, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Mamoswine", { ability: "Oblivious", nature: "Adamant", item: "Choice Scarf", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Azumarill", { ability: "Huge Power", nature: "Adamant", item: "Sitrus Berry", evs: { hp: 244, atk: 252, def: 0, spa: 0, spd: 12, spe: 0 }}),
    new Pokemon("Toedscruel", { ability: "Mycelium Might", nature: "Timid", item: "Covert Cloak", evs: { hp: 196, atk: 0, def: 60, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Gardevoir", { ability: "Trace", nature: "Modest", item: "Choice Scarf", evs: { hp: 244, atk: 0, def: 84, spa: 36, spd: 4, spe: 140 }}),
    new Pokemon("Braviary", { ability: "Defiant", nature: "Adamant", item: "Psychic Seed", evs: { hp: 12, atk: 252, def: 0, spa: 0, spd: 0, spe: 244 }}),
    new Pokemon("Flamigo", { ability: "Scrappy", nature: "Adamant", item: "Focus Sash", evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 }}),
    new Pokemon("Vivillon", { ability: "Compound Eyes", nature: "Timid", item: "Focus Sash", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Salazzle", { ability: "Oblivious", nature: "Timid", item: "Focus Sash", evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 }}),
    new Pokemon("Goodra-Hisui", { ability: "Sap Sipper", nature: "Modest", item: "Leftovers", evs: { hp: 252, atk: 0, def: 20, spa: 236, spd: 0, spe: 0 }}),
    new Pokemon("Kingdra", { ability: "Swift Swim", nature: "Timid", item: "Life Orb", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Arcanine", { ability: "Intimidate", nature: "Jolly", item: "Safety Goggles", evs: { hp: 244, atk: 36, def: 4, spa: 0, spd: 4, spe: 220 }}),
    new Pokemon("Klefki", { ability: "Prankster", nature: "Calm", item: "Light Clay", evs: { hp: 252, atk: 0, def: 148, spa: 4, spd: 100, spe: 4 }}),
    new Pokemon("Ludicolo", { ability: "Swift Swim", nature: "Modest", item: "Life Orb", evs: { hp: 12, atk: 0, def: 4, spa: 252, spd: 4, spe: 236 }}),
    new Pokemon("Rotom-Heat", { ability: "Levitate", nature: "Modest", item: "Choice Scarf", evs: { hp: 252, atk: 0, def: 20, spa: 36, spd: 20, spe: 180 }}),
    new Pokemon("Bronzong", { ability: "Levitate", nature: "Relaxed", item: "Safety Goggles", evs: { hp: 252, atk: 0, def: 148, spa: 0, spd: 108, spe: 0 }}),
    new Pokemon("Chesnaught", { ability: "Bulletproof", nature: "Adamant", item: "Sitrus Berry", evs: { hp: 228, atk: 100, def: 28, spa: 0, spd: 108, spe: 44 }}),
    new Pokemon("Ceruledge", { ability: "Flash Fire", nature: "Adamant", item: "Clear Amulet", evs: { hp: 204, atk: 36, def: 108, spa: 0, spd: 44, spe: 116 }}),
    new Pokemon("Raichu", { ability: "Lightning Rod", nature: "Timid", item: "Focus Sash", evs: { hp: 0, atk: 0, def: 4, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Charizard", { ability: "Solar Power", nature: "Timid", item: "Choice Scarf", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Sableye", { ability: "Prankster", nature: "Careful", item: "Eject Button", evs: { hp: 252, atk: 0, def: 148, spa: 0, spd: 104, spe: 0 }}),
    new Pokemon("Conkeldurr", { ability: "Guts", nature: "Brave", item: "Flame Orb", evs: { hp: 252, atk: 252, def: 0, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Oranguru", { ability: "Inner Focus", nature: "Sassy", item: "Mental Herb", evs: { hp: 252, atk: 0, def: 180, spa: 0, spd: 76, spe: 0 }}),
    new Pokemon("Houndstone", { ability: "Sand Rush", nature: "Impish", item: "Safety Goggles", evs: { hp: 252, atk: 4, def: 252, spa: 0, spd: 0, spe: 0 }}),
    new Pokemon("Ribombee", { ability: "Shield Dust", nature: "Timid", item: "Focus Sash", evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 }}),
    new Pokemon("Empoleon", { ability: "Competitive", nature: "Modest", item: "Leftovers", evs: { hp: 252, atk: 0, def: 0, spa: 252, spd: 4, spe: 0 }}),
    new Pokemon("Hydrapple", { ability: "Regenerator", nature: "Quiet", item: "Assault Vest", evs: { hp: 252, atk: 0, def: 0, spa: 252, spd: 4, spe: 0 }}),
    new Pokemon("Glaceon", { ability: "Snow Cloak", nature: "Modest", item: "Choice Specs", evs: { hp: 244, atk: 0, def: 0, spa: 252, spd: 12, spe: 0 }}),
    new Pokemon("Altaria", { ability: "Cloud Nine", nature: "Careful", item: "Safety Goggles", evs: { hp: 244, atk: 0, def: 228, spa: 0, spd: 36, spe: 0 }}),
    new Pokemon("Metagross", { ability: "Clear Body", nature: "Adamant", item: "Assault Vest", evs: { hp: 252, atk: 196, def: 4, spa: 0, spd: 44, spe: 12 }}),
    new Pokemon("Illumise", { ability: "Prankster", nature: "Timid", item: "Covert Cloak", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Serperior", { ability: "Contrary", nature: "Timid", item: "Choice Scarf", evs: { hp: 244, atk: 0, def: 4, spa: 4, spd: 4, spe: 252 }}),
    new Pokemon("Magnezone", { ability: "Sturdy", nature: "Modest", item: "Choice Scarf", evs: { hp: 252, atk: 0, def: 0, spa: 252, spd: 4, spe: 0 }}),
    new Pokemon("Malamar", { ability: "Contrary", nature: "Brave", item: "Safety Goggles", evs: { hp: 252, atk: 252, def: 0, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Hariyama", { ability: "Guts", nature: "Brave", item: "Flame Orb", evs: { hp: 252, atk: 252, def: 0, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Kleavor", { ability: "Sharpness", nature: "Adamant", item: "Choice Scarf", evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 }}),
    new Pokemon("Tinkaton", { ability: "Mold Breaker", nature: "Jolly", item: "Sitrus Berry", evs: { hp: 252, atk: 4, def: 52, spa: 0, spd: 4, spe: 196 }}),
    new Pokemon("Espeon", { ability: "Magic Bounce", nature: "Modest", item: "Choice Specs", evs: { hp: 36, atk: 0, def: 12, spa: 236, spd: 4, spe: 220 }}),
    new Pokemon("Comfey", { ability: "Triage", nature: "Calm", item: "Sitrus Berry", evs: { hp: 188, atk: 0, def: 156, spa: 4, spd: 76, spe: 84 }}),
    new Pokemon("Quaquaval", { ability: "Moxie", nature: "Jolly", item: "Choice Scarf", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Alcremie", { ability: "Sweet Veil", nature: "Quiet", item: "Covert Cloak", evs: { hp: 252, atk: 0, def: 116, spa: 140, spd: 0, spe: 0 }}),
    new Pokemon("Mandibuzz", { ability: "Overcoat", nature: "Calm", item: "Leftovers", evs: { hp: 252, atk: 0, def: 52, spa: 4, spd: 196, spe: 4 }}),
    new Pokemon("Toxicroak", { ability: "Dry Skin", nature: "Adamant", item: "Clear Amulet", evs: { hp: 20, atk: 236, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Persian-Alola", { ability: "Fur Coat", nature: "Timid", item: "Assault Vest", evs: { hp: 252, atk: 0, def: 100, spa: 4, spd: 84, spe: 68 }}),
    new Pokemon("Basculegion-F", { ability: "Swift Swim", nature: "Modest", item: "Choice Scarf", evs: { hp: 0, atk: 0, def: 4, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Toxtricity", { ability: "Punk Rock", nature: "Timid", item: "Choice Specs", evs: { hp: 252, atk: 0, def: 4, spa: 60, spd: 12, spe: 180 }}),
    new Pokemon("Venusaur", { ability: "Chlorophyll", nature: "Modest", item: "Covert Cloak", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Typhlosion", { ability: "Flash Fire", nature: "Timid", item: "Choice Scarf", evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 }}),
    new Pokemon("Yanmega", { ability: "Speed Boost", nature: "Timid", item: "Focus Sash", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Inteleon", { ability: "Sniper", nature: "Timid", item: "Scope Lens", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Orthworm", { ability: "Earth Eater", nature: "Impish", item: "Sitrus Berry", evs: { hp: 212, atk: 0, def: 36, spa: 0, spd: 252, spe: 4 }}),
    new Pokemon("Bellibolt", { ability: "Electromorphosis", nature: "Modest", item: "Assault Vest", evs: { hp: 252, atk: 0, def: 0, spa: 212, spd: 44, spe: 0 }}),
    new Pokemon("Porygon-Z", { ability: "Adaptability", nature: "Timid", item: "Choice Scarf", evs: { hp: 0, atk: 0, def: 4, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Scrafty", { ability: "Intimidate", nature: "Adamant", item: "Assault Vest", evs: { hp: 252, atk: 156, def: 60, spa: 0, spd: 36, spe: 0 }}),
    new Pokemon("Snorlax", { ability: "Thick Fat", nature: "Brave", item: "Sitrus Berry", evs: { hp: 180, atk: 76, def: 252, spa: 0, spd: 0, spe: 0 }}),
    new Pokemon("Stonjourner", { ability: "Power Spot", nature: "Adamant", item: "Choice Scarf", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Bruxish", { ability: "Dazzling", nature: "Jolly", item: "Choice Scarf", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Vikavolt", { ability: "Levitate", nature: "Modest", item: "Magnet", evs: { hp: 244, atk: 0, def: 0, spa: 252, spd: 12, spe: 0 }}),
    new Pokemon("Magmortar", { ability: "Vital Spirit", nature: "Modest", item: "Charcoal", evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 }}),
    new Pokemon("Oricorio-Sensu", { ability: "Dancer", nature: "Modest", item: "Focus Sash", evs: { hp: 0, atk: 0, def: 4, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Weavile", { ability: "Pressure", nature: "Jolly", item: "Focus Sash", evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 }}),
    new Pokemon("Perrserker", { ability: "Steely Spirit", nature: "Jolly", item: "Chople Berry", evs: { hp: 252, atk: 4, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Hitmontop", { ability: "Intimidate", nature: "Adamant", item: "Clear Amulet", evs: { hp: 252, atk: 252, def: 0, spa: 0, spd: 4, spe: 0 }}),
    new Pokemon("Drednaw", { ability: "Swift Swim", nature: "Adamant", item: "Choice Band", evs: { hp: 28, atk: 196, def: 4, spa: 0, spd: 28, spe: 252 }}),
    new Pokemon("Blastoise", { ability: "Torrent", nature: "Modest", item: "Choice Scarf", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Staraptor", { ability: "Intimidate", nature: "Adamant", item: "Choice Scarf", evs: { hp: 164, atk: 252, def: 4, spa: 0, spd: 4, spe: 84 }}),
    new Pokemon("Infernape", { ability: "Blaze", nature: "Modest", item: "Life Orb", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Scizor", { ability: "Technician", nature: "Adamant", item: "Clear Amulet", evs: { hp: 252, atk: 156, def: 4, spa: 0, spd: 28, spe: 68 }}),
    new Pokemon("Umbreon", { ability: "Inner Focus", nature: "Bold", item: "Mirror Herb", evs: { hp: 252, atk: 0, def: 140, spa: 0, spd: 116, spe: 0 }}),
    new Pokemon("Slowbro-Galar", { ability: "Regenerator", nature: "Quiet", item: "Covert Cloak", evs: { hp: 252, atk: 0, def: 0, spa: 156, spd: 100, spe: 0 }}),
    new Pokemon("Rotom-Mow", { ability: "Levitate", nature: "Modest", item: "Choice Scarf", evs: { hp: 60, atk: 0, def: 4, spa: 252, spd: 4, spe: 188 }}),
    new Pokemon("Greninja", { ability: "Torrent", nature: "Timid", item: "Loaded Dice", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Frosmoth", { ability: "Ice Scales", nature: "Modest", item: "Leftovers", evs: { hp: 12, atk: 0, def: 4, spa: 252, spd: 4, spe: 236 }}),
    new Pokemon("Torterra", { ability: "Shell Armor", nature: "Adamant", item: "White Herb", evs: { hp: 68, atk: 252, def: 4, spa: 0, spd: 8, spe: 176 }}),
    new Pokemon("Duraludon", { ability: "Stalwart", nature: "Timid", item: "Eviolite", evs: { hp: 100, atk: 0, def: 0, spa: 0, spd: 156, spe: 252 }}),
    new Pokemon("Shiftry", { ability: "Wind Rider", nature: "Adamant", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Muk-Alola", { ability: "Gluttony", nature: "Adamant", item: "Figy Berry", evs: { hp: 220, atk: 196, def: 52, spa: 0, spd: 4, spe: 36 }}),
    new Pokemon("Drifblim", { ability: "Unburden", nature: "Timid", item: "Grassy Seed", evs: { hp: 4, atk: 0, def: 220, spa: 28, spd: 132, spe: 124 }}),
    new Pokemon("Krookodile", { ability: "Intimidate", nature: "Jolly", item: "Choice Scarf", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Abomasnow", { ability: "Snow Warning", nature: "Modest", item: "Assault Vest", evs: { hp: 252, atk: 0, def: 0, spa: 252, spd: 4, spe: 0 }}),
    new Pokemon("Electrode-Hisui", { ability: "Soundproof", nature: "Timid", item: "Choice Specs", evs: { hp: 60, atk: 0, def: 0, spa: 252, spd: 0, spe: 196 }}),
    new Pokemon("Cinderace", { ability: "Libero", nature: "Jolly", item: "Choice Scarf", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Jolteon", { ability: "Volt Absorb", nature: "Timid", item: "Focus Sash", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Espathra", { ability: "Speed Boost", nature: "Modest", item: "Focus Sash", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Lapras", { ability: "Water Absorb", nature: "Calm", item: "Leftovers", evs: { hp: 252, atk: 0, def: 196, spa: 4, spd: 52, spe: 4 }}),
    new Pokemon("Cetitan", { ability: "Slush Rush", nature: "Adamant", item: "Sitrus Berry", evs: { hp: 4, atk: 52, def: 164, spa: 0, spd: 164, spe: 124 }}),
    new Pokemon("Hawlucha", { ability: "Unburden", nature: "Adamant", item: "Grassy Seed", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Barraskewda", { ability: "Swift Swim", nature: "Adamant", item: "Choice Band", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Jumpluff", { ability: "Chlorophyll", nature: "Jolly", item: "Covert Cloak", evs: { hp: 252, atk: 4, def: 84, spa: 0, spd: 4, spe: 164 }}),
    new Pokemon("Noivern", { ability: "Infiltrator", nature: "Timid", item: "Focus Sash", evs: { hp: 0, atk: 0, def: 4, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Slowking", { ability: "Regenerator", nature: "Sassy", item: "Sitrus Berry", evs: { hp: 236, atk: 0, def: 196, spa: 0, spd: 76, spe: 0 }}),
    new Pokemon("Reuniclus", { ability: "Overcoat", nature: "Quiet", item: "Life Orb", evs: { hp: 124, atk: 0, def: 92, spa: 244, spd: 44, spe: 0 }}),
    new Pokemon("Dachsbun", { ability: "Well-Baked Body", nature: "Calm", item: "Leftovers", evs: { hp: 252, atk: 0, def: 4, spa: 0, spd: 252, spe: 0 }}),
    new Pokemon("Lucario", { ability: "Inner Focus", nature: "Adamant", item: "Choice Scarf", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Hippowdon", { ability: "Sand Stream", nature: "Impish", item: "Rocky Helmet", evs: { hp: 252, atk: 0, def: 92, spa: 0, spd: 164, spe: 0 }}),
    new Pokemon("Eelektross", { ability: "Levitate", nature: "Modest", item: "Assault Vest", evs: { hp: 152, atk: 0, def: 0, spa: 252, spd: 104, spe: 0 }}),
    new Pokemon("Lilligant", { ability: "Chlorophyll", nature: "Modest", item: "Focus Sash", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Sceptile", { ability: "Unburden", nature: "Timid", item: "Focus Sash", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Froslass", { ability: "Cursed Body", nature: "Timid", item: "Focus Sash", evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 }}),
    new Pokemon("Pachirisu", { ability: "Volt Absorb", nature: "Bold", item: "Sitrus Berry", evs: { hp: 252, atk: 0, def: 156, spa: 0, spd: 100, spe: 0 }}),
    new Pokemon("Rabsca", { ability: "Telepathy", nature: "Quiet", item: "Covert Cloak", evs: { hp: 228, atk: 0, def: 84, spa: 196, spd: 0, spe: 0 }}),
    new Pokemon("Cyclizar", { ability: "Regenerator", nature: "Jolly", item: "Covert Cloak", evs: { hp: 252, atk: 4, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Arboliva", { ability: "Seed Sower", nature: "Relaxed", item: "Leftovers", evs: { hp: 180, atk: 0, def: 156, spa: 0, spd: 172, spe: 0 }}),
    new Pokemon("Toxapex", { ability: "Regenerator", nature: "Bold", item: "Binding Band", evs: { hp: 252, atk: 0, def: 140, spa: 0, spd: 116, spe: 0 }}),
    new Pokemon("Electivire", { ability: "Vital Spirit", nature: "Adamant", item: "Clear Amulet", evs: { hp: 68, atk: 252, def: 4, spa: 0, spd: 4, spe: 180 }}),
    new Pokemon("Slowking-Galar", { ability: "Regenerator", nature: "Sassy", item: "Sitrus Berry", evs: { hp: 252, atk: 0, def: 12, spa: 0, spd: 240, spe: 0 }}),
    new Pokemon("Oricorio-Pom-Pom", { ability: "Dancer", nature: "Timid", item: "Focus Sash", evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Mudsdale", { ability: "Stamina", nature: "Adamant", item: "Assault Vest", evs: { hp: 252, atk: 36, def: 76, spa: 0, spd: 140, spe: 4 }}),
    new Pokemon("Coalossal", { ability: "Flash Fire", nature: "Relaxed", item: "Leftovers", evs: { hp: 180, atk: 0, def: 156, spa: 0, spd: 172, spe: 0 }}),
    new Pokemon("Gliscor", { ability: "Poison Heal", nature: "Careful", item: "Toxic Orb", evs: { hp: 212, atk: 4, def: 4, spa: 0, spd: 252, spe: 36 }}),
    new Pokemon("Houndoom", { ability: "Flash Fire", nature: "Timid", item: "Safety Goggles", evs: { hp: 76, atk: 0, def: 4, spa: 196, spd: 4, spe: 228 }}),
    new Pokemon("Exeggutor", { ability: "Chlorophyll", nature: "Timid", item: "Focus Sash", evs: { hp: 0, atk: 0, def: 4, spa: 252, spd: 0, spe: 252 }}),
    new Pokemon("Trevenant", { ability: "Harvest", nature: "Adamant", item: "Sitrus Berry", evs: { hp: 252, atk: 76, def: 116, spa: 0, spd: 60, spe: 4 }}),
    new Pokemon("Grumpig", { ability: "Gluttony", nature: "Bold", item: "Aguav Berry", evs: { hp: 236, atk: 0, def: 116, spa: 0, spd: 156, spe: 0 }}),
    new Pokemon("Poliwrath", { ability: "Swift Swim", nature: "Adamant", item: "Sitrus Berry", evs: { hp: 100, atk: 196, def: 36, spa: 0, spd: 36, spe: 140 }}),
    new Pokemon("Vaporeon", { ability: "Water Absorb", nature: "Bold", item: "Leftovers", evs: { hp: 252, atk: 0, def: 252, spa: 4, spd: 0, spe: 0 }}),
    new Pokemon("Swampert", { ability: "Torrent", nature: "Quiet", item: "Safety Goggles", evs: { hp: 252, atk: 0, def: 0, spa: 196, spd: 60, spe: 0 }}),
    new Pokemon("Lokix", { ability: "Tinted Lens", nature: "Adamant", item: "Life Orb", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Rampardos", { ability: "Sheer Force", nature: "Brave", item: "Life Orb", evs: { hp: 0, atk: 252, def: 84, spa: 0, spd: 168, spe: 0 }}),
    new Pokemon("Cloyster", { ability: "Skill Link", nature: "Adamant", item: "Focus Sash", evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 }}),
    new Pokemon("Golurk", { ability: "No Guard", nature: "Brave", item: "Assault Vest", evs: { hp: 60, atk: 156, def: 36, spa: 4, spd: 252, spe: 0 }}),
    new Pokemon("Meowstic", { ability: "Prankster", nature: "Calm", item: "Light Clay", evs: { hp: 252, atk: 0, def: 108, spa: 4, spd: 140, spe: 4 }}),
    new Pokemon("Arbok", { ability: "Intimidate", nature: "Adamant", item: "Clear Amulet", evs: { hp: 252, atk: 252, def: 4, spa: 0, spd: 0, spe: 0 }}),
    new Pokemon("Dewgong", { ability: "Thick Fat", nature: "Sassy", item: "Covert Cloak", evs: { hp: 252, atk: 0, def: 220, spa: 0, spd: 36, spe: 0 }}),
    new Pokemon("Dragalge", { ability: "Adaptability", nature: "Modest", item: "Assault Vest", evs: { hp: 232, atk: 0, def: 20, spa: 252, spd: 0, spe: 0 }}),
 ]  
}