name: Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

  build:
    name: Build
    runs-on: ubuntu-24.04
    needs: install-dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-24.04
    needs: install-dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: ./coverage/vgc-multicalc/lcov.info

  lint:
    name: Lint
    runs-on: ubuntu-24.04
    needs: install-dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run check

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-24.04
    needs:
      - build
      - unit-tests
      - lint

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: "http://localhost:4200"
          browser: chrome
          quiet: true

  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main'
    needs: e2e-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci && npm install -g @angular/cli

      - name: Deploy
        run: ng deploy --cname=vgcmulticalc.com --name="robsonbittencourt" --email=robson.luizv@gmail.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sonarqube:
    name: SonarQube
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main'
    needs: deploy

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Coverage Reports
        uses: actions/download-artifact@v4
        with:
          name: coverage-reports

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
