name: Deploy Main Branch
on:
  workflow_dispatch:

env:
  NODE_VERSION: "24.15.0"

jobs:
  deploy:
    name: Deploy Main Branch
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Checkout latest tag
        run: git checkout $(git tag --sort=-creatordate | head -n 1)

      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/browser
          cname: vgcmulticalc.com
          user_name: robsonbittencourt
          user_email: robson.luizv@gmail.com
