name: Rollback
on:
  workflow_dispatch:

env:
  NODE_VERSION: "24.15.0"

jobs:
  rollback:
    name: Rollback
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Checkout previous tag
        run: |
          PREVIOUS_TAG=$(git tag --sort=-creatordate | sed -n '2p')
          echo "Rolling back to $PREVIOUS_TAG"
          git checkout $PREVIOUS_TAG

      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci && npm install -g @angular/cli

      - name: Deploy
        run: ng deploy --cname=vgcmulticalc.com --name="robsonbittencourt" --email=robson.luizv@gmail.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
